### ISSUE TITLE
Searching the tree (similar to filter)

### ISSUE THREAD

**Issue by denkomanceski** [500tech/angular-tree-component#118]
Hi, what is the best way to search for a node in the tree by some function (just like filter), but without any side effects (ex: filter is hiding the nodes). I just want to receive the list of nodes. I need this to programatically focus a node on the tree that his name contains something (I will focus the first node of the filtered list)

The true flag in the filterNodes is still hiding the ones that did not match the comparison. I just want to list back. I can of course iterate the tree on my own recursively but maybe there is already an easier way :)

Edit: Searching like this seems to be okay:

```
let arr = [] 
let iter = (node) => {
      arr.push(...node.filter(child => {
        if (child.children)
          iter(child.children);
        return child.data.key == this.displayedNode.value.patternKey
      }));
    }
 iter(this.tree.treeModel.roots);
console.log(arr)
```

**Comment by adamkleingit** [comment]
Currently there's no built-in iteration over treeNodes, but I can add it.

Something like this maybe:
```
treeModel.forEachNode((node) => ...)
```
?

**Comment by denkomanceski** [comment]
ye, or treeModel.findNodes((node) => ...)
Could you also check (https://github.com/500tech/angular2-tree-component/issues/98#event-873634289) about _calculateExpandedNodes() to recreate the state but on an async nodes?

**Comment by gRoussac** [comment]
Hi,

``` 
tree.treeModel.filterNodes((node: TreeNode) => searchNodes(node, text), false);
````

If searchNodes here always returns true, then you nodes are not hidden and you can make a comparison in it to save matching nodes. Imho there is no really need of a second function.

**Comment by adamkleingit** [comment]
We now have a `doForAll` method that iterates over the tree

**Comment by marcolazzara** [comment]
Hi,

can you please post a full example about using filter?
