### ISSUE TITLE
Performance issues with large trees

### ISSUE THREAD

**Issue by Krisa** [500tech/angular-tree-component#121]
That's a nice plugin but there are serious performance issues by large trees. A node with only 1000 children will take 10-15s to load on Chrome (latest version). 10K nodes will simply crash the window after 1 minute or so of freeze. 

Is there anything which could be improved on this side?

**Comment by adamkleingit** [comment]
I plan to introduce performance support for large trees in the near future.
Did you investigate why it happens?

2 options:
- Change detection takes too long - In such case I need to export another
TreeComponent that allow OnPush strategy.
- Too many DOM elements - In such case I need to allow virtual scrolling.

I want to eventually introduce both.

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by Krisa** [comment]
No sorry, didn't spend time to investigate. I'm not so sure which strategy is the best to be honest. A performant alternative would be to delegate some listener to a document listener, or overall component listener, but that would be quite dirty I think... ( `renderer.listen(elementRef.nativeElement, 'click', (event) => {...})`)

I dont know how well the more "Angular" method are performing with a massive number of nodes.

**Comment by Provson** [comment]
Hi,

With 100 elements, the tree takes 40 sec to load.
38 sec for the Event Dom Click.
Someone has a solution ?

**Comment by bhavyaw** [comment]
+1

**Comment by denkomanceski** [comment]
@Provson its probably something from your side that is the problem.. I can load a lot of nodes without any problems..

**Comment by stestaub** [comment]
I have the same problem. When I open a node with ~1500 children, it takes about 30 seconds in chrome. I did some profiling and it seems to be the addEventListener method the most time consuming operation.

**Comment by JulienNexonia** [comment]
+1

**Comment by istiti** [comment]
+1

**Comment by alsh76** [comment]
I have same issue. My tree consists of about 200 2nd level nodes. Each of them has 0-10 children. There are no 4th level nodes.  

Collapsing / expanding of the whole tree takes about 5 second. Maybe it would be appropriate in the first time but second and other time it is annoying a bit 

Children of 2nd level nodes are loaded dynamically. After the tree data updating I call  `this.tree.treeModel.update()` and it updates the tree view with 3 second delay despite of small number of new children (usually less that 10)

Any ideas about performance improving? I would appreciate any advice

**Comment by denkomanceski** [comment]
Maybe the author can explain in brief what was his idea of optimizing it, so I can try and make a pull request? That would really help

**Comment by istiti** [comment]
Virtual repeat!! Logical

**Comment by alsh76** [comment]
Also it would be nice to have lazy loading mechanism to update/refresh only current node and its children. 

`getChildren `  is not called for me after node expanding and I am forced to update whole tree

```
options = {
  getChildren: (node:TreeNode) => {
    return request('/api/children/' + node.id);
  }
}
```

**Comment by adamkleingit** [comment]
Hey guys,
I was in sickness leave for a long time.
Did anyone check what makes it slow?

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by alsh76** [comment]
I have to mention delays in production version are not such significant. Collapsing / expanding of the tree takes about 1 second. That is acceptable for me

Nevertheless [jsTree](https://github.com/vakata/jstree) jquery plugin renders the tree faster a bit and supports lazy loading

**Comment by webnugget** [comment]
Hi Guys,
i just did some profiling with chrome,#
![image](https://cloud.githubusercontent.com/assets/3836420/22499264/f8fe9332-e85d-11e6-8dee-25fd82611c49.png)

i'm not very good at interpreting this, but it looks like a change detection issue.

The node for the tree are generated with the following function inside onInit.
So The Tree has 10000 toplevel nodes, with 4 Children. This is a realistic size for my app, but it's way to slow.

````
buildnodes(){
    let newNodes = [];
    for(let i=0;i<10000;i++){
      newNodes.push({
        id: i,
        name: 'root'+i,
        children: [
          { id: 'child-'+(i+1), name: 'child-1-from-' +i},
          { id: 'child-'+(i+2), name: 'child-2-from-' +i},
          { id: 'child-'+(i+3), name: 'child-3-from-' +i},
          { id: 'child-'+(i+4), name: 'child-4-from-' +i}
        ]
      });


    }
    return newNodes;
  }
````

**Comment by adamkleingit** [comment]
Hey guys,
I'll work on this during the weekend. I hope I can solve it in a couple of days, I'll keep you posted

**Comment by anselpeters** [comment]
looking forward to seeing this one resolved.. great component btw.. thanks for your effort on this one

**Comment by adamkleingit** [comment]
It's really close to being finished

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by denkomanceski** [comment]
It it going to be infinite tree ? :D

**Comment by adamkleingit** [comment]
Infinite no. But you can load 10,000 nodes and the tree should scroll
smoothly (when you enableProdMode())

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by Krisa** [comment]
Do the nodes always stay in the DOM once loaded, or are they "dynamically" removed (from the DOM, but kept in memory) when, for example, a node is collapsed?

**Comment by adamkleingit** [comment]
They are dynamically destroyed and created.
When a node is collapsed - that's already supported in the tree (I use ngIf
for the children).
The virtual scroll feature will also make sure that only the nodes in the
current viewport are on the DOM, and allow the user to feel a smooth scroll
as if the entire tree is rendered

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by Krisa** [comment]
Wow that sounds great, I assume then it can support much more than 10k nodes, the limit being actually regarding the memory, so something like way above 100K if not millions .. ?

**Comment by adamkleingit** [comment]
Well, there will be 3 limits:
- browser limit of the viewport height, which will allow for around 0.5 million nodes - depending on their height.
- client side memory of holding all of the nodes
- heavy client side actions, like filtering or drag and drop / dynamically updating the tree (which forces to recalculate the node positions)

**Comment by albrechta** [comment]
Yesterday, I experimented with version 3.0.2 and virtual scrolling. There is an issue with large node templates (e.g. height 150px). If I start to scroll down slowly from the top of the tree, the content suddenly jumps and a couple of nodes are skipped (disappear from the viewport).

I think it is related to the number of tree nodes that are part of the tree node collection initially. The number of elements in the DOM is not constant at the beginning. It increases as I start scrolling down. My guess is that this results in this odd jump because some property (height?) is recalculated. 

Is there a way to fix the number of elements? Once the number of tree nodes is not changing anymore, scrolling works.

**Comment by adamkleingit** [comment]
Hi @albrechta @Krisa @Provson @anselpeters  @alsh76 ,
can you try with 3.1.0 - it looks like it's stable and solved virtual scrolling.
Use `enableProdMode()` with many nodes.

Thanks

**Comment by istiti** [comment]
this plugin not works correctly after all theses changes ! i use 3.1.0 and when open child sometimes  the tree's noeuds are cutted, is there a documentations for this virtual scroll, do I need specify height of each node ? do I need height somewhere ? is there a example to realize this virtual scroll :S 

dammage

**Comment by Provson** [comment]
1) create 2 directives (draggable and droppable)
2) Draggable code :
`import { Directive, Input, ElementRef, AfterContentInit, OnDestroy } from '@angular/core';

@Directive({
    selector: '[makeDraggable]'
})
export class MakeDraggable implements AfterContentInit, OnDestroy {
    //Contient l'objet que l'on veut déplacer
    @Input('makeDraggable') data: any;

    constructor(private _elementRef: ElementRef) { }

    ngAfterContentInit() {
        //On récupère le native element
        let el = this._elementRef.nativeElement;

        // Set the draggable attribute to the element
        el.draggable = 'true';

        el.addEventListener('dragstart', (e) => {
            if (e.stopPropagation) {
                e.stopPropagation();
            }

            el.classList.add('dragStart')
            e.dataTransfer.effectAllowed = 'move';
            e.dataTransfer.setData('text', JSON.stringify(this.data));
        });

        // Remove the drag-src class
        el.addEventListener('dragend', (e) => {
            e.preventDefault();
            el.classList.remove('dragStart')
        });
    }

    //On supprime les event listener
    ngOnDestroy() {
        let el = this._elementRef.nativeElement;

        el.removeEventListener('dragstart');
        el.removeEventListener('dragend');
    }
}`
3) Droppable code :
`import { Directive, AfterContentInit, ElementRef, Output, EventEmitter, OnDestroy, NgZone } from '@angular/core';

@Directive({
    selector: '[makeDroppable]'
})
export class MakeDroppable implements AfterContentInit, OnDestroy {
    //Evenement emit lors du drop
    @Output() dropped: EventEmitter<number> = new EventEmitter();

    constructor(private _elementRef: ElementRef, private ngZone: NgZone) { }

    ngAfterContentInit() {
        //On récupère le native element
        let el = this._elementRef.nativeElement;

        this.ngZone.runOutsideAngular(() => {
            //Ajout class over
            el.addEventListener('dragenter', (e) => {
                el.classList.add('over');
            });

            //Suppression class over
            el.addEventListener('dragleave', (e) => {
                el.classList.remove('over');
            });

            //Ajout class move
            el.addEventListener('dragover', (e) => {
                if (e.preventDefault) {
                    e.preventDefault();
                }

                e.dataTransfer.dropEffect = 'move';
                return false;
            });
        });


        let self = this;
        //Au drop, on emet un event avec l'objet que l'on drop
        el.addEventListener('drop', (e) => {
            this.ngZone.run(() => {
                if (e.stopPropagation) {
                    e.stopPropagation();
                }

                el.classList.remove('over');
                let data: any = JSON.parse(e.dataTransfer.getData('text'));

                self.dropped.emit(data.id);

                return false;
            })
        })
    }

    //On supprime tous les event listener
    ngOnDestroy() {
        let el = this._elementRef.nativeElement;

        el.removeEventListener('dragenter');
        el.removeEventListener('dragleave');
        el.removeEventListener('dragover');
        el.removeEventListener('drop');
    }
}`

4) For html element with need to be draggable :
`<button class="btn btn-primary btn-sm" [makeDraggable]="'MyData">Yolo</button>`

5) For html with need to be droppable :
`<div makeDroppable (dropped)="onDrop($event)"></div>`

The slowness comes from Angular. Iwas obliged to use 'ngZone'.

**Comment by albrechta** [comment]
@adamkleingit Unfortunately, scrolling is still an issue with large nodes (e.g. height of node is 150px). The problem is not performace anymore but the virtual scrolling, which scrolls too fast. If I scroll through a tree, a node changes 2 or three levels as you recalculate the marginTop.

**Comment by adamkleingit** [comment]
Can you share your code?
Which browser + OS version?
Thanks

**Comment by adamkleingit** [comment]
@albrechta did you set the `nodeHeight` property on the `options`?
You can set it to either a number or a function.

If you have, and there's still a problem - please re-open the issue and paste your code.

Thanks!

**Comment by ibookhotel** [comment]
Hi All,

Really great component.

Thanks for great effort. I spent last two week learning and working with component.

Is it possible to attach event on virtual scroll to trigger fetching data form server and appending to current node being scrolled? 

It basically like infinite scroll per child node.

Thanks!

**Comment by faizanu94** [comment]
Hi,
I'm also facing performance issues working with large trees (>5K nodes) when below function is called on the tree.

**(click)="tree.treeModel.expandAll()"**

The performance is relatively slow at the event of expand() compared to collapse().

I came across plenty of solutions in this thread, [issue# 173](https://github.com/500tech/angular-tree-component/issues/173) & [issue# 463](https://github.com/500tech/angular-tree-component/issues/463) and have tried some of them as well, but still this is not solved.

Please suggest which one is the correct one, specially in terms of performance?

Thanks,
Faizan

**Comment by somdesp** [comment]
Hello, the problem has been resolved, I have a case with 3000 nodes, and it still has slow loading problems
