### ISSUE TITLE
2.8.0 Ngc error, can't resolve module ./components/deprecated-loading.component

### ISSUE THREAD

**Issue by arendjantetteroo** [500tech/angular-tree-component#162]
I've updated from 2.6.0 to 2.8.0 in order for AOT to work. 

I now get thise error when running ngc
[13:38:40]  ngc started ... 
can't resolve module ./components/deprecated-loading.component from /home/arie/NetBeansProjects/ionic2/node_modules/angular2-tree-component/dist/angular2-tree-component.d.ts
[13:38:42]  build prod failed: Cannot read property 'LoadingComponent' of undefined, resolving symbol 
            DeprecatedTreeModule in 
            /home/arie/NetBeansProjects/ionic2/node_modules/angular2-tree-component/dist/angular2-tree-component.d.ts, 
            resolving symbol DeprecatedTreeModule in 
            /home/arie/NetBeansProjects/ionic2/node_modules/angular2-tree-component/dist/angular2-tree-component.d.ts 
[13:38:42]  ionic-app-script task: "build" 
[13:38:42]  Error: Cannot read property 'LoadingComponent' of undefined, resolving symbol DeprecatedTreeModule in 
            /home/arie/NetBeansProjects/ionic2/node_modules/angular2-tree-component/dist/angular2-tree-component.d.ts, 
            resolving symbol DeprecatedTreeModule in 
            /home/arie/NetBeansProjects/ionic2/node_modules/angular2-tree-component/dist/angular2-tree-component.d.ts 
Error: Cannot read property 'LoadingComponent' of undefined, resolving symbol DeprecatedTreeModule in /home/arie/NetBeansProjects/ionic2/node_modules/angular2-tree-component/dist/angular2-tree-component.d.ts, resolving symbol DeprecatedTreeModule in /home/arie/NetBeansProjects/ionic2/node_modules/angular2-tree-component/dist/angular2-tree-component.d.ts

I'm trying to include this in an ionic2 project based on ionic 2.0.0 which still uses angular 2.2.1. 

Any ideas? Should it work with angular 2.2.1 or do we need angular 2.3 minimal?

**Comment by adamkleingit** [comment]
Hey,
I will check it.
By the way - why not move to the non-deprecated module? The deprecated one will be gone one day.

**Comment by arendjantetteroo** [comment]
@adamkleingit Thanks for the response. 

I'm just including this in my app.module.ts:
import { TreeModule } from 'angular2-tree-component';

I'm not using the deprecated one anywhere. So i'm not sure why it wants to include it. 
I assume it has something to do with the typings.

**Comment by arendjantetteroo** [comment]
Thanks for that hint, if i remove all deprecated files and from metatata in angular2-tree-component directory in node_modules, it compiles fine.

**Comment by arendjantetteroo** [comment]
Ok, did some more testing. If i remove only the Deprecated mentions in the metadata file, it compiles fine. 
It works ok without that in the metatdata file, but might be needed for others that need the deprecated methods? 

Now what would be the best way forward? 
- Add a 3.0 version without the deprecated items so they are not included in the metadata.json? 

How can i get this version with the metadata that works in my node_modules?

**Comment by arendjantetteroo** [comment]
As a temporary workaround i copy a patched metadata.json into the node_modules/angular2-tree-component directory after installing with npm. That works for now.

**Comment by coreyroth** [comment]
I am using this component in Ionic 2 and I am getting this error as well when it runs ngc.  I'll try the workaround.

**Comment by adamkleingit** [comment]
That's very strange, why would it fail only on the deprecated modules... Any idea?
I haven't tried this with ionic yet.

**Comment by arendjantetteroo** [comment]
I assume it has something to do with the used ngc/angular/typescript version in ionic2 which is 2.2.1 and typescript 2.0.9, But my knowledge here is still rather limited.
