### ISSUE TITLE
Memory Leaks when expanding / collapsing

### ISSUE THREAD

**Issue by adamkleingit** [500tech/angular-tree-component#167]
When expanding / collapsing nodes, there's a memory leak in the number of nodes and listeners on the page.

**Comment by oudinia** [comment]
Hello adam,
Are there any advancements on this bug ? 
It might be a blocking issue for me, should I try and solve at the source ?
Thanks,
O.D.

**Comment by jskrzypek** [comment]
I'm starting to investigate this. #goodnessSquad

**Comment by itzik25b** [comment]
I this I encountered this issue, when i have a tree with lots of nodes after expending few nodes my app gets super slow, memory/cpu usage gets high, and i can see lots of events reported in the console (verbose level).
can you confirm that it's related to the defect you have reported? can you tell when a fix is expected?

![image](https://user-images.githubusercontent.com/16287085/32315062-48ad38d4-bfb3-11e7-8b55-71c9d3de37c3.png)
