### ISSUE TITLE
Browser crashed with No provider for Renderer on angular-cli project 

### ISSUE THREAD

**Issue by 24hours** [500tech/angular-tree-component#168]
Hi, 

I have recently switch from webpack 1 to angular-cli to bundle my project. After I made the switch, chrome started to throw an error `no provider for Renderer` 

It work fine before the switch. 
here is the line that causing error [constructor(public renderer: Renderer) {}](https://github.com/500tech/angular2-tree-component/blob/master/lib/models/tree.model.ts#L33)

I found related problem in stackoverflow [Renderer cannot be used in Service?](http://stackoverflow.com/questions/34710408/renderer-cannot-be-used-in-service) The error actually make sense considering injectable should never use renderer service. 

Do you guys have any intention / idea to solve this issue ?

**Comment by adamkleingit** [comment]
Hey,
next version of the tree will not use the renderer in the service.
Hope to have it out in a few days
Thanks

**Comment by adamkleingit** [comment]
The next version will take some more time than expected. Will try to solve this issue individually ASAP

**Comment by adamkleingit** [comment]
Fixed in 3.2.4
