### ISSUE TITLE
AllowDrag only make single nodes draggable - not whole tree

### ISSUE THREAD

**Issue by manuelfink** [500tech/angular-tree-component#172]
Is it anyhow possible to make single tree nodes dragable?

I tried allowDrag:true as an key of the element like isExpanded, but this seems not to be supported yet?

allowDrag as a function (node): boolean like allowDrop also does not seem to be implemented yet.

Anyone else has similar requirements or started implementing anything like this?

**Comment by adamkleingit** [comment]
#176 should solve this

**Comment by adamkleingit** [comment]
Merged #176 will be released in the coming version

**Comment by adamkleingit** [comment]
Fixed in 3.2.4
