### ISSUE TITLE
DnD performance - drop zone showing with high delay

### ISSUE THREAD

**Issue by manuelfink** [500tech/angular-tree-component#173]
I do have performance issues with drag n drop.

Draging an element, highlighting the drop area takes about 2-15s. This makes it especially hard to hit the smaller drop areas eg. between two nodes then sorting elements within a tree or getting the spot to push it before the next higher category, but not as a child in the category before.

Has anyone these issues too?

This issue exists with pretty small trees with 20 items. I think this may not be correlating to the large trees issue https://github.com/500tech/angular2-tree-component/issues/121 though.

v.2.8.1

**Comment by eusokolov** [comment]
Hello.
I have the same problem.

**Comment by adamkleingit** [comment]
Hey, which browser are you using? Can you share link to code / plunkr?
Do you get this also with the tree demo:?
rawgit.com/500tech/angular2-tree-component/master/example/cli/dist/index.html
(click allowDrag button first)

**Comment by adamkleingit** [comment]
@manuelfink @eusokolov any new data that would help solve this?

**Comment by eusokolov** [comment]
@adamkleingit Hello, Adam
Sorry for late response. I received new information reg issue and see that tree has more than 500 nodes. Looks like performance of drag and drop correlating with https://github.com/500tech/angular2-tree-component/issues/121

**Comment by manuelfink** [comment]
@adamkleingit I'm stuck with a project thus cannot dig into profiling right now. 

I think my issue may correlate with rerendering the screen pretty often. I do have longer sessions on the tree with data / model updates refreshing the tree. It's not best customer experience but not a killer right now either. However have not had time to further investigate yet. 

But I guess this may also get solved with the issue changing to dragula.

**Comment by manuelfink** [comment]
Browser is chrome on Mac, latest version. But also had similar issues on Firefox and Safari

**Comment by adamkleingit** [comment]
Hey,
the performance version is almost done - in a very short time it will be officially released

**Comment by manuelfink** [comment]
Any news on the performance version?

**Comment by adamkleingit** [comment]
Yes, 3.2.3 with `useVirtualScroll` option set to true
