### ISSUE TITLE
Generate children node without tracking data causing impact in input field

### ISSUE THREAD

**Issue by hunglu** [500tech/angular-tree-component#181]
Hi, 

I have an issue to enter value into input for each node. 

Cause TreeNodeChildren generates each TreeNode using ngFor but it missing a tracked by index of each data. so it affects data other node data in case of user edit.

Please help to fix this.

Line 16 in tree-node-children.component.ts
Line 34 in tree.component.ts

**Comment by adamkleingit** [comment]
Hi,
I don't understand how 'track by' affects the input? Can you share your
code?

Anyway, thanks for noting - next version of the tree will have a 'track by'
clause

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633
