### ISSUE TITLE
Ng2MobxModule is not an NgModule

### ISSUE THREAD

**Issue by SimonaMilchevska** [500tech/angular-tree-component#188]
Hi,

Prevously I was using the angular2-tree-component with SystemJs and it was working great. 
Now I moved to Webpack, and I get this error while compile: 
**ERROR in Ng2MobxModule is not an NgModule**
The version I am using is 2.8.1

Here is the sample code:

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import {Http} from "@angular/http";
import { AppComponent } from './app.component';
import {TreeModule} from "angular2-tree-component/dist/angular2-tree-component";

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    TreeModule
  ],
  providers: [ ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Any suggestions, ideas ?

**Comment by adamkleingit** [comment]
I accidentally released a beta version with bugs 2.8.1-performance. I think you might have installed it.
Can you install 2.8.2 (or 2.8.1 explicitly) and check if it solves it?

**Comment by nlynn12** [comment]
I'm also having this problem with version 3.2.0

**Comment by adamkleingit** [comment]
@nlynn12 
Are you using SystemJS?

**Comment by nlynn12** [comment]
No, I took a copy of your repo and inserted the lib folder directly in my existing Angular CLI project, as I need to make some changes to fit my needs.

**Comment by adamkleingit** [comment]
So makes sense you have to run `npm install --save ng2-mobx`, if you just copy the `lib` folder then you have to manually install the dependencies.
BTW, if you have to make changes it's recommended to do a fork - that way you can keep up to date with the changes.
Also, please make sure to open issues only if the problem occurs in the original library, not if you copy the code inside your app (which is not how you are supposed to use it).

Thanks for understanding!
