### ISSUE TITLE
After node selection 'getActiveNodes()' returns empty array

### ISSUE THREAD

**Issue by showoffer** [500tech/angular-tree-component#197]
Angular 2.4.4
Angular2-tree-component 3.1.0

After 2.8.0 -> 3.1.0 upgrade getActiveNodes() returns an empty array. In 2.8.0 this method returned an array of selected nodes.

**Comment by adamkleingit** [comment]
Bug with MobX indexes getting turned into strings. Should be solved.
Thanks for reporting.

**Comment by adamkleingit** [comment]
You can work with treeModel.activeNodeIds in the meantime until fixed, or keep track of the expanded nodes using events.

**Comment by showoffer** [comment]
@adamkleingit thank you. I will switch to the new version after next more or less stable release.

**Comment by svcninja** [comment]
Same here. activeNodeIds works fine.

**Comment by adamkleingit** [comment]
Fixed in 3.2.1 - please upgrade

**Comment by showoffer** [comment]
@adamkleingit thank you!

**Comment by cripolgon** [comment]
@adamkleingit Hi! I have the same issue and I am using the version ^5.0.0. I am using Angular v 4.4.0. 

`const nodes = tree.treeModel.getActiveNodes();`

It is invoked when I click a button and I click this button when I already click some checkboxes but this code return me empty Array. Why?

**Comment by illiden** [comment]
me too not working when I'm used getActiveNodes();
so I try with getFocusedNode() then it work and return node data.
