### ISSUE TITLE
Event: onInitialized and onUpdate do not include TreeNode with event object

### ISSUE THREAD

**Issue by SnackyPete** [500tech/angular-tree-component#203]
Hi,

Although the TreeNode model is included with all other events, it is not included with `onInitialized` and `onUpdate`.  I've modified the code to include them (see the two `fireEvent` calls below), but have not had time to create a project and merge request.

```
  @action update() {
    // Rebuild tree:
    let virtualRootConfig = {
      virtual: true,
      [this.options.childrenField]: this.nodes
    };

    this.virtualRoot = new TreeNode(virtualRootConfig, null, this, 0);

    this.roots = this.virtualRoot.children;

    // Fire event:
    if (this.firstUpdate) {
      if (this.roots) {
        this.fireEvent({ eventName: TREE_EVENTS.onInitialized, node: this.virtualRoot });
        this.firstUpdate = false;
        this._calculateExpandedNodes();
      }
    } else {
      this.fireEvent({ eventName: TREE_EVENTS.onUpdateData, node: this.virtualRoot });
    }
  }
```

**Comment by adamkleingit** [comment]
Hey,
the `update` and `onInitialized` are not on a specific node, that's why it's not included.
You can access the treeModel using a ref on the tree component.

I just added `treeModel` attribute to all events - please upgrade to 3.2.1
