### ISSUE TITLE
lib name

### ISSUE THREAD

**Issue by istiti** [500tech/angular-tree-component#205]
hi angular2 is not adequat name, what are you thinking about
### ngx-tree
which is not taken atm

**Comment by adamkleingit** [comment]
Hey, changed to angular-tree-component.
Thanks

**Comment by istiti** [comment]
nice, +1

ps: isn't it anti pattern calling angular lib with "component" suffix while all is component and the lib is module in fact

**Comment by istiti** [comment]
we know google didn't succeed  because of their name,  but this lib will have more impact, be more pro/clean known, fast to find ...  if called **ngx-tree** ( just search if still available and found https://github.com/e-cloud/ngx-tree)

another thing is as asked months ago, remove mobx, keep lib as green as possible, no dep. and this ngx-tree remove it (didn't tried yet but awesome, will move on it if works because ngx-tree is exactly what I would have proposed to angular-tree-component)

another point is avoid support angular2 (certainly little code to keep it possible but bette remove it, size is important) 

this is not critic, angular-tree-component is awesome and easytouse lib,  just make it better and go ahead with **NO-EMOTION** 

@adamkleingit  @e-cloud please find agreement
