### ISSUE TITLE
Error: trackBy must be a function, but received undefined

### ISSUE THREAD

**Issue by pixvs** [500tech/angular-tree-component#206]
Hi, i getting this error when upgrading to lastest version 3.1.0 , 2.8.2 works fine for me

![image](https://cloud.githubusercontent.com/assets/4992691/23576595/8c478cb0-006f-11e7-8d39-c4e5d0da6af8.png)

Thank you

**Comment by ghybs** [comment]
Hi,

Looks like it fails with angular `2.4.1`:
https://plnkr.co/edit/crXt0CkBsQmg1Hx6cRiC?p=preview

But with lastest Angular2 (i.e. `2.4.9` as of today), it works:
https://plnkr.co/edit/mZTQ9xnikhMwoOvkfiLl?p=preview

(with dependencies: lodash `4.6.1`, mobx `3.1.0` or `3.1.3`, ng2-mobx `1.2.9`)

Hope this helps.

**Comment by adamkleingit** [comment]
Fixed in 3.2.1 - please upgrade
