### ISSUE TITLE
Need help regarding styling

### ISSUE THREAD

**Issue by debslab** [500tech/angular-tree-component#209]
I am using following style to add a line after each node as shown in image.
.tree .node-wrapper:after {
    content: "";
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 1px;
    background-color: #d4d6da;
}
![image](https://cloud.githubusercontent.com/assets/7782545/23638566/63a6a052-0308-11e7-9166-21621e6b7c04.png)

But I want the line to start from beginning, not with corresponding node location as shown in image. Please help me out.

**Comment by adamkleingit** [comment]
Hi,
You can use the following option (10 is an example):
```
{
  levelPadding: 10
}
```
And then you can style the entire row, because the padding is achieved on a per node basis, and not for the entire children

**Comment by debslab** [comment]
thanks a lot
