### ISSUE TITLE
Reduce bundle size

### ISSUE THREAD

**Issue by adamkleingit** [500tech/angular-tree-component#211]
For some reason the entire lodash package is being bundled and not tree shaken.
Option 1 - solve it.
Option 2 - include lodash modularized packages instead of lodash-es.

**Comment by Gillardo** [comment]
love to see this in next version.

**Comment by istiti** [comment]
any news here ?

cc @adamkleingit

**Comment by istiti** [comment]
i think this cause my app blockin on 92% and cause build durning 10mn !  because webpack try to minify and create bundle of whole lodash-es, hope this import will be fixed asap, thanks

**Comment by Gillardo** [comment]
Now you mention it @istiti my webpack also freeses at 92%, always wondered why

**Comment by achimha** [comment]
You can see how angular-tree-component and its dependencies make up about 50% of the total size of a fairly large code module. loadash-es is the major issue but mbox.js is also rather large and monolithic.

<img width="820" alt="screen shot 2017-04-12 at 10 14 52" src="https://cloud.githubusercontent.com/assets/6816140/24947956/001bed4e-1f69-11e7-846f-524e2d1c2a3d.png">

**Comment by istiti** [comment]
Reason is import certainly but not only this one... maybe if you import many times same and complet  lib in different chunk this will take long time to finish. So be sure you import right part of each lib example import {do} from "rxjs/add/operator/do"

**Comment by adamkleingit** [comment]
Hey,

Need to turn all lodash imports to direct import like you suggested.
That is a very fast fix that could solve half of the problem.

About compilation time - node modules shouldn't be compiled, maybe it's
because of lodash-es instead of lodash?

Anybody has time to tackle this one and make a PR?

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by istiti** [comment]
if it's only correct import I did it directly here on github but donno for "mobx" never use it ... https://github.com/500tech/angular-tree-component/pulls

**Comment by achimha** [comment]
It would probably be better to combine all your PR into a single one that can be directly applied.

**Comment by istiti** [comment]
As said did from gothub dont know if i can but still not ready for mobx @adamkleingit can help

Ps: i can't success to build project :S

**Comment by adamkleingit** [comment]
@istiti thanks for the PR, I had to use require eventually to cherry-pick the lodash methods eventually.
Also added uglification - now the bundle is 100KB (MobX is half of it, but not sure there's anything I can do about it).

Will be released in the coming version

**Comment by adamkleingit** [comment]
Fixed in 3.3.0

**Comment by istiti** [comment]
I wonder if this is fixed cause with 3.3.0 I get:

![image](https://cloud.githubusercontent.com/assets/2789203/25116655/5db19d88-240e-11e7-8341-e8cc98bf972e.png)

**Comment by achimha** [comment]
It works for me with 3.3.0, I only get the individual lodash components.

**Comment by istiti** [comment]
thanks @achimha  can you fast paste webpack-bundle-analyzer screenshot ? cauz not sure if it's normal  I have bundle like that mobx.js lodash mobx-angular angular-tree-component

**Comment by achimha** [comment]
![screen shot 2017-04-18 at 09 24 33](https://cloud.githubusercontent.com/assets/6816140/25119016/decdd698-2418-11e7-879a-6c1832d398bd.png)

**Comment by istiti** [comment]
ok it's like me.
Do we really need these big lib mobyx.js + lodash + mobx-angular

**Comment by achimha** [comment]
mobx is included by mobx-angular in a monolithic fashion, not really an issue of this library.

**Comment by istiti** [comment]
@achimha and what about lodash? whois importing whole lodash lib ? 
cause lodash is about 135KB
and mobx.js 109kb
and  mobx-angualr 55kb

my imports looks like:
`import {TreeComponent, TreeNode} from 'angular-tree-component';`

**Comment by elvirdolic** [comment]
Why mobx is used anyway rxjs and subjects are already their. What are the arguments to use it for the tree?

**Comment by istiti** [comment]
https://github.com/mobxjs/mobx/wiki/Mobx-vs-Reactive-Stream-Libraries-(RxJS,-Bacon,-etc)

Even I admit too rxjs will be sufficient. Sadly due to mobx and angular-mobx and other 3rd party lib: tomorrow if I have choice with another tree lib I will move on it :(
