### ISSUE TITLE
Request style for checked node

### ISSUE THREAD

**Issue by debslab** [500tech/angular-tree-component#213]
Hi,
    After adding checkbox before tree nodes, I want to style the nodes depending on checkbox state. I see that styles are handled in this location - https://github.com/500tech/angular-tree-component/blob/024202a9faa10cdf56ec083598654a431b6d841f/lib/components/tree-node.component.ts#L33. How can I add a style there for node.checked state.

Thank you

**Comment by debslab** [comment]
I am able to fix this by adding following in actionMapping, hence closing this issue.
nodeClass: (node:TreeNode) => {if (node.data.checked) return 'tree-node-checked'; else return ''; }

**Comment by adamkleingit** [comment]
Awesome, glad you solved by yourself!

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by finalxcode** [comment]
thanks
