### ISSUE TITLE
Using Self Referential Model In Tree

### ISSUE THREAD

**Issue by MstfTkrsln** [500tech/angular-tree-component#214]
Hi, How can I use (bind) a self referential model for this component?

the model like this

`export class Container{
  constructor(
    public id:number,
    public name:string,
    public type:string,
    public parent:Container,
    expanded:Boolean
  ) { }
}
`

Thank you

**Comment by adamkleingit** [comment]
Hi,
The tree needs a 'children' attribute with an array of children.
I suggest you transform the Container class to an object of the desired
structure by the tree component.
The expanded nodes by the way are kept separately from the nodes. You can
listen to expand events and update the Container accordingly

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633
