### ISSUE TITLE
Allow usage of perfect scrollbar

### ISSUE THREAD

**Issue by dhilgarth** [500tech/angular-tree-component#216]
I am trying to use perfect scrollbar instead of the normal scrollbars.
I am adding the `perfect-scrollbar` directive to `tree-root`. However, it is only working after I manually removed `overflow: auto` from `tree-viewport`.

I can't remove that style using CSS as shadow piercing CSS selectors have been deprecated.

Any ideas on how I can use perfect scrollbar with this component?

**Comment by adamkleingit** [comment]
If I add ViewEncapsulation.None to the viewport - will that solve the
problem?

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by adamkleingit** [comment]
@dhilgarth any updates?

**Comment by dhilgarth** [comment]
Adam, I am not sure actually. I am not familiar enough with that feature to answer your question. As of now, I have solved it by using the deprecated piercing CSS selector.

**Comment by adamkleingit** [comment]
Hi.
Actually, you are not supposed to override that.
Are you using virtualScroll?
If not - I suggest you wrap the tree with your own div and put the perfect scrollbar on that div.
