### ISSUE TITLE
TreeModel.getNodeById() throws exception if nodes are empty or null

### ISSUE THREAD

**Issue by dojchek** [500tech/angular-tree-component#217]
Hi,

Using version 3.2.3 on Angular 2.3.0
When [nodes] input parameter is initialized with empty array or null, getNodeById(id) method throws an exception:
```
TypeError: Cannot read property 'toString' of null
```

This also happens with getNodeBy() method.

**Comment by adamkleingit** [comment]
Hi,
Can you make a pull request to fix?

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by dojchek** [comment]
I can look into it and possibly solve it and do a PR, but will happen in a couple of days. Currently too overscheduled.

**Comment by adamkleingit** [comment]
Fixed in latest version
