### ISSUE TITLE
treeModel.filterNodes behaves weird when compiled with AOT   

### ISSUE THREAD

**Issue by snehasis** [500tech/angular-tree-component#218]
Hi,

The tree component works perfectly when compiled as JIT , but when compiled the same code with AOT it started behaving weird when you do the tree.treeModel.filterNodes(text, true);

When you enter any data on the search input , it JIT it display the Parent and Filtered Child Node properly , but on AOT it Opens up all the Parent Nodes and overlap with each Other like the Attached ScreenShot.

It only happens on the AOT compilation, not sure why the same thing never happened on JIT compilation.
![error-aot-angular-tree-3 2 3](https://cloud.githubusercontent.com/assets/1704267/23848467/6e629ac4-07fd-11e7-8587-7c6ce452fb36.png)

Thank you

**Comment by debslab** [comment]
in jit as well, I am able to see issue. Along with it, the nodes which don't match the search term are no more hidden although hidden attribute is set

**Comment by debslab** [comment]
If I put useVirtualScroll: true in options, then the issue goes away for me. But again scroll bar comes for even small tree.

**Comment by adamkleingit** [comment]
Will be fixed in the coming version

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by adamkleingit** [comment]
Hi @debslab , @snehasis  fixed in 3.2.4, can you verify?
