### ISSUE TITLE
bundle size

### ISSUE THREAD

**Issue by istiti** [500tech/angular-tree-component#221]
In my angular4 app I use this plugin and I wonder why my vendor bundle is multiplied by 1.5 when using angular-tree-component it's big, I just wonder if it's normal size 

without angular-tree-component  vendor = **564 Ko**
with angular-tree-component vendor  = **823 Ko**

mobx and ng2-mobx is about 150kb
and lodash-es is about 600kb
 
![image](https://cloud.githubusercontent.com/assets/2789203/23943191/e52a03c8-096e-11e7-8cbe-868e8443853d.png)

how can we optimize this and remove mobx and lodash for this component

v. 3.2.3

cc @adamkleingit

**Comment by adamkleingit** [comment]
Hi,
are you using webpack?

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by istiti** [comment]
yes im (angular cli rc2) 

when I disable angular-tree-component i don't have lodash-es modx.js and angular-tree-component size  (lodash is big as angular core) 

@adamkleingit

**Comment by adamkleingit** [comment]
Yes something is broken with the tree shaking - this is a duplicate of #211

**Comment by istiti** [comment]
ok will close this one and hope fix will soon be available

cc @adamkleingit
