### ISSUE TITLE
Custom template usage require additional providers

### ISSUE THREAD

**Issue by 12kb** [500tech/angular-tree-component#222]
Hello!

`TreeVirtualScroll` and `TreeModel` providers registered in tree-root and viewport components.
So that, if I'm trying to override full node template, I need to include this providers into my component.
So, may be better to register providers on component? Or at least document it?

Thank you

**Comment by adamkleingit** [comment]
Hi,
Will be fixed in coming version.

All the best

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by ismailcherri** [comment]
@12kb Thanks! You saved hours of poking around :)

**Comment by adamkleingit** [comment]
Hi @ismailcherri @12kb , fixed in 3.2.4 - can you verify?

**Comment by 12kb** [comment]
@adamkleingit Thanks for fixing! 👍 
@ismailcherri Glad to be useful :)
