### ISSUE TITLE
'Binding to event property 'onActivate' is disallowed for security reasons'

### ISSUE THREAD

**Issue by olastor** [500tech/angular-tree-component#223]
I've encountered this error with version `^3.2.3` and angular-cli version `3.10.10` when trying to bind the `onActivate` event. Don't know what to do.

![bug](https://cloud.githubusercontent.com/assets/7479641/23960879/767952ae-09a9-11e7-91b3-a47652a70e6c.png)

**Comment by adamkleingit** [comment]
Need to remove 'on' in all events and make a deprecation warning.
Who wants to make a pull request?

**Comment by olastor** [comment]
can somebody reproduce this error? I tested it on another machine with the same version of angular cli and it worked without any errors. Will try to find the cause of this warning, since it doesn't seem to be a trivial error.

**Comment by adamkleingit** [comment]
@olastor it looks like you used brackets `[onDeactivate]` instead of paranthesis `(onDeactivate)` to bind to outputs.

**Comment by adamkleingit** [comment]
@olastor did it solve it for you? I'm closing the issue, if it persists please re-open

**Comment by picheli20** [comment]
The problem is not the brackets/paranthesis... Is it correct `[onDeactivate]` but the problem is the prefix `on`, if you remove it should works.
