### ISSUE TITLE
Tree not displaying when not in view (ng2-bootstrap tabs)

### ISSUE THREAD

**Issue by Gillardo** [500tech/angular-tree-component#227]
I have updated to the latest version yesterday (3.2.3) along with updating to angular4.  It seems that the tree works fine, when it is in view straight away, but if it is not, its doesnt render at all. This was all working when i was using the old version 1.3.5

If you use it with ng2-bootstrap tabs and your tree is on the first tabs, works fine.  If you put the tree on the second tab (or any tab that aint first), then the tree never renders??

**Comment by Gillardo** [comment]
I have even created a demo of this, please find attached which replicates the error.  You will notice that there are 2 routes.

**Comment by samueldweber** [comment]
Did you manage do fix it? if so how?

**Comment by jgolebiewski** [comment]
I have same problem. How did you solve this problem ?
