### ISSUE TITLE
TreeNodeExpander encapsulation

### ISSUE THREAD

**Issue by ismailcherri** [500tech/angular-tree-component#230]
Hi,

The ViewEncapsulation setting for the TreeNodeExpanderComponent is set to 'None' which makes it harder to override the style. What should we do to overcome this? (beside editing library files)

Regards

**Comment by adamkleingit** [comment]
Hi,

The reasoning behind using ViewEncapsulation.None was to make it **easier** to override.
If you provide more specific CSS rules it will work, for example instead of:
```
.toggle-children {
  background-image: url(...)
}
```
You can do:
```
.my-custom-tree .toggle-children {
  background-image: url(...)
}
```

**Comment by adamkleingit** [comment]
Hi @ismailcherri , did this help? Are you still having trouble? Thanks

**Comment by ismailcherri** [comment]
Hi, sorry for the delayed response.
I managed to work on it by adding my custom classes.
However, the problem occurs if the parent component has its encapsulation set to Emulated, this is the case when you want to set CSS styling special to this component. All the elements will get the special CSS selectors except for the TreeNodeExpander.
Ideally, it would be better if this behavior can be controlled, though I'm not sure if this is possible with Angular.

**Comment by adamkleingit** [comment]
I'm not sure what's the best approach here.
Anyway, I'm closing the issue.

Thanks
