### ISSUE TITLE
installation warning

### ISSUE THREAD

**Issue by isaklafleur** [500tech/angular-tree-component#233]
Angular tree component v3.2.4.

I have installed the latest Angular 4 version with Angular Cli.

After I try to install the Angular tree component (following the instructions: https://angular2-tree.readme.io/docs/getting-started)

$ npm install --save angular-tree-component

**I get these warnings:**
eclass-tree@0.0.0 /Users/isaklafleur/Coding/GitHub/angular-tree-component
└─┬ angular-tree-component@3.2.4
  ├── UNMET PEER DEPENDENCY @angular/core@^2.3.0
  ├── lodash-es@4.17.4
  ├── mobx@3.1.8
  └── ng2-mobx@1.2.9

npm WARN ng2-mobx@1.2.9 requires a peer of @angular/core@^2.3.0 but none w
as installed.

Can I just ignore these warning or do I need to install Angular2 as well?

**Comment by istiti** [comment]
same issue after run npm update to last version any fix

**Comment by adamkleingit** [comment]
Will be fixed in coming version

**Comment by adamkleingit** [comment]
Fixed in 3.3.0
