### ISSUE TITLE
tree is undefined onInitialized

### ISSUE THREAD

**Issue by yaronmil** [500tech/angular-tree-component#236]
Hi,
hooking to the onInitialized event ,trying to manipulate the tree.
 tree is undefined 
using this : 

```
@ViewChild(TreeComponent)
  private tree: TreeComponent;
```
accordingly to documentation the onInitialized  is 

> Good for performing actions immediately on init

**Comment by adamkleingit** [comment]
Hi @yaronmil ,
I can't reproduce. Can you share your code?

**Comment by ganipadela** [comment]
@adamkleingit My onInitialize event is not getting fired
