### ISSUE TITLE
Adding TreeNode module make loading time expand on Angular 4

### ISSUE THREAD

**Issue by pmcuong120394** [500tech/angular-tree-component#237]
I'm using Angular Tree Component in my project. 
With out it. My project loading time is just 2-3seconds

But if i'm import TreeModule in to my module.. It make the loading time expand over 14 seconds..
I figured out that it depend on how much html i'm using..If i'm use just blank html page..it's just normal...
But if i add more html...It expand the loading time.

![image](https://cloud.githubusercontent.com/assets/25000619/24737499/077234ba-1a44-11e7-9ec3-110edcd369a8.png)

I wonder what affect to arrayslice..Am i missing something in config..Or treemodule affect to my code...

"devDependencies": {
    "@angular/animations": "^4.0.0",
        "@angular/common": "~4.0.0",
        "@angular/compiler": "~4.0.0",
        "@angular/compiler-cli": "^4.0.0",
        "@angular/core": "~4.0.0",
        "@angular/flex-layout": "2.0.0-rc.1",
        "@angular/forms": "^4.0.0",
        "@angular/http": "^4.0.0",
        "@angular/material": "git+https://github.com/angular/material2-builds.git",
        "@angular/platform-browser": "~4.0.0",
        "@angular/platform-browser-dynamic": "~4.0.0",
        "@angular/platform-server": "~4.0.0",
        "@angular/router": "^4.0.0",
        "@swimlane/ngx-datatable": "^7.1.1",
        "@types/elasticsearch": "^5.0.13",
        "@types/jasmine": "^2.5.45",
        "@types/node": "^7.0.8",
        "@types/lodash": "^4.14.50",
        "angular-tree-component": "^3.2.4",
        "angular2-template-loader": "^0.6.2",
        "autoprefixer": "^6.7.7",
        "awesome-typescript-loader": "^3.1.2",
        "clean-webpack-plugin": "^0.1.16",
        "copy-webpack-plugin": "^4.0.0",
        "core-js": "^2.4.0",
        "cpx": "^1.5.0",
        "cross-env": "^3.2.4",
        "css-loader": "^0.27.3",
        "extract-text-webpack-plugin": "2.0.0-beta.4",
        "file-loader": "^0.10.1",
        "fs-extra": "^2.1.2",
        "gh-pages": "^0.12.0",
        "gulp": "^3.9.1",
        "gulp-sftp": "^0.1.5",
        "hammerjs": "^2.0.8",
        "html-webpack-plugin": "^2.22.0",
        "istanbul-instrumenter-loader": "^2.0.0",
        "jasmine-core": "^2.5.2",
        "jasmine-spec-reporter": "^3.2.0",
        "karma": "^1.5.0",
        "karma-chrome-launcher": "^2.0.0",
        "karma-coverage": "^1.1.1",
        "karma-jasmine": "^1.0.2",
        "karma-mocha-reporter": "^2.2.3",
        "karma-remap-coverage": "^0.1.3",
        "karma-sourcemap-loader": "^0.3.7",
        "lodash": "^4.17.4",
        "mathjs": "^3.9.1",
        "moment": "^2.17.1",
        "karma-webpack": "^2.0.3",
        "node-sass": "^4.5.1",
        "npm-run-all": "^4.0.2",
        "postcss": "^5.2.16",
        "postcss-loader": "^1.3.3",
        "raw-loader": "^0.5.1",
        "protractor": "^5.1.1",
        "replace": "^0.3.0",
        "rimraf": "^2.6.1",
        "rxjs": "^5.2.0",
        "sass-loader": "^6.0.3",
        "source-map-loader": "^0.2.0",
        "style-loader": "^0.16.0",
        "to-string-loader": "^1.1.5",
        "ts-helpers": "^1.1.2",
        "ts-node": "^3.0.2",
        "tslint": "^4.5.1",
        "tslint-config-swimlane": "^2.0.1",
        "tslint-loader": "^3.4.3",
        "typescript": "^2.2.1",
        "url-loader": "^0.5.8",
        "webpack": "^2.3.1",
        "webpack-combine-loaders": "^2.0.3",
        "webpack-dev-server": "^2.4.2",
        "webpack-merge": "^4.1.0",
        "webpack-notifier": "^1.5.0",
        "wrench": "^1.5.9",
        "zone.js": "^0.8.5"
  },

Above is all package i'm using.

Thank for your help 👍

**Comment by pmcuong120394** [comment]
Actually. If i open a new tab..And open the web..it's just normal (around 2s loading time) but if i refresh...It's spend over 10 seconds @@

**Comment by pmcuong120394** [comment]
Just figured out that it just slow with project after update to angular 4..with angular 2. It's just fine

**Comment by adamkleingit** [comment]
@pmcuong120394 so with or without the tree it makes no difference?

**Comment by pmcuong120394** [comment]
with the tree :"((
But only if i use angular 4..with angular 2..it's all fine
