### ISSUE TITLE
Angular 4 support issue

### ISSUE THREAD

**Issue by tokuduz** [500tech/angular-tree-component#238]
Hi,

Thank for you component and ur support for Angular 4. But there is an issue with Angular 4, since 
angular/cli 1.0.0, request all @angular packages to be  at least ^4.0.0. Problem is that you are using "ng2-mobx@1.2.9" which requires @angular/core@^2.3.0.  ng2-mobx is now mobx-angular from version 1.4.1, which have support for Angular 4. So please update ur dependencies or you want me to submit PR. 

[EDIT] - actually it isn't a  problem, but a warning that can be easily resolved.

Thank you,
TK

**Comment by adamkleingit** [comment]
Hi,
if you can submit a PR that will be fantastic.

Thanks

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by tokuduz** [comment]
Hi,
I am currently without a time to make a PR. I will try to do so in near future if nobody will do it.
