### ISSUE TITLE
VirtualScroll and nodeHeight Parameter

### ISSUE THREAD

**Issue by elvirdolic** [500tech/angular-tree-component#248]
Im using latest version 3.2.4 

I have a tree where the nodes are attached from server and then I have a deepLink to a Node. What I want todo is to to acviate this requested Node and set the scrollPosition to this node.

Im doing this, after the tree has all necessary nodes.
```

const node: TreeNode = this.treeComponent.treeModel.getNodeById(this.selectedTreeNodeCode);
if (node) {
                    this.treeComponent.treeModel.collapseAll();
                    node.setActiveAndVisible();
 }

```
node is selected and active => works fine but the problem is that the node is not visible because the scroll bar does not scroll

` options: ITreeOptions = { idField: 'code', nodeHeight: 50, useVirtualScroll: true };
`
the nodeHeight => what is the node Height here, should padding be inlucde dor not? I don't now the exactly nodeHeight because this can change if the screen gets smaller or the text is longer

![image](https://cloud.githubusercontent.com/assets/17769458/25001526/32ff9282-2046-11e7-950c-a2afadc1230b.png)

**Comment by adamkleingit** [comment]
Hi @elvirdolic ,
1) Maybe try inside a setTimeout function (to make sure tree is already rendered).
2) You can supply a function that receives the node and returns its height if you have variable heights.
Using virtual scroll is only possible if you can supply a height per node.
3) BTW, How many nodes do you have? Virtual scroll is only relevant if you're displaying hundreds or thousands of nodes.

**Comment by elvirdolic** [comment]
If the tree is completely loaded we will have about 3k nodes. 

When we should use virtual scrolling is there any suggestion?

**Comment by adamkleingit** [comment]
I think you should try without it and see how it behaves. Depends how complex your node templates are, what actions do you allow etc.
