### ISSUE TITLE
Invariant failed: Since strict-mode is enabled, changing observed observable values outside actions is not allowed.

### ISSUE THREAD

**Issue by orgilor** [500tech/angular-tree-component#256]
Hi,
As you can see from the picture below, when i used the basic example from the docs, with MobX and implemented the tree component, i got the following error:
![capture](https://cloud.githubusercontent.com/assets/11899264/25139689/ad067cb6-2466-11e7-85df-a923aceb072e.PNG)

What is the right way to integrate the tree component with MobX (Angular 4.0.1)?
Thanks.

**Comment by adamkleingit** [comment]
Will be released soon in 3.3.1
