### ISSUE TITLE
AOT issue

### ISSUE THREAD

**Issue by ghaiat** [500tech/angular-tree-component#261]
Hi,

Since the last version 3.3.1, i m having this error when building my app in aot:

`ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 77:13 in the original .ts file), resolving symbol action in /Users/xxx/node_modules/mobx/lib/mobx.d.ts, resolving symbol TreeNodeCollectionComponent in /Users/xxx/node_modules/angular-tree-component/dist/components/tree-node-collection.component.d.ts
`

**Comment by jskrzypek** [comment]
This is reproducible by creating a fresh clone of the repo and running `npm run prepublishOnly`

I think I have a fix, however

**Comment by jskrzypek** [comment]
Ok this error is actually caused by `action` being imported from `mobx` instead of `mobx-angular`

**Comment by istiti** [comment]
please can this be accepted  can't build project

cc @adamkleingit

**Comment by adamkleingit** [comment]
Fixed in 3.4.0 - can you verify?

**Comment by ghaiat** [comment]
yep, it works
