### ISSUE TITLE
Unable to retain filters after updating the tree.

### ISSUE THREAD

**Issue by RohitRane** [500tech/angular-tree-component#266]
Hi,

I am using angular2-tree-component version 2.6.0

I am using `tree.treeModel.filterNodes("text", true); ` to filter on the tree via a text box. Also I constantly poll the server every 15 seconds to keep my tree update with any new additional nodes/ or any nodes  deleted on server using `tree.treeModel.update();`.

Now problem is that on running update applied filter gets removed. As a workaround I tried 

```
tree.treeModel.update();
tree.treeModel.filterNodes("text", true);
```
Nothing happened
Next I tried ,

tree.treeModel.update();
```
 setTimeout(() => {
     tree.treeModel.filterNodes("text", true);
})   
```        
This works, but for a fraction of a second between updating the tree and reapplying the filter, I can see the entire tree .. Is there any solution for this?

Thanks in advance.

**Comment by pandawi** [comment]
in your template, for the tree element add `(onUpdateData)="tree.treeModel.filterNodes("text", true);"`

**Comment by adamkleingit** [comment]
@RohitRane 
In the latest version the filter is saved as a list of IDs, so it should work if you have unique IDs for your nodes
