### ISSUE TITLE
Demo on angular2-tree.readme.io page not working in IE11

### ISSUE THREAD

**Issue by vihorlat** [500tech/angular-tree-component#272]
Hi,

Demo on _https://angular2-tree.readme.io/_ webpage never loads (only shows Loading...) in my IE 11  in neither of these versions: v2.8.0,v3.1.0,v3.2.0,v3.3.0
Javascript console shows  
`SCRIPT5007: Unable to get property 'apply' of undefined or null reference`
`vendor.bundle.js (18615,5)`
and it navigates to this function:
```
function combine(options) {
    return ((Object)).assign.apply(((Object)), [{}].concat(options));
}
```
IE version:
![image](https://cloud.githubusercontent.com/assets/11267965/25273958/5c61930c-268e-11e7-96b8-ed09bd3e461d.png)

**Comment by adamkleingit** [comment]
Yes, it's a small fix in the example polyfills - will be fixed.
