### ISSUE TITLE
Focus not set after filtering 

### ISSUE THREAD

**Issue by AngularTx** [500tech/angular-tree-component#275]
Hi ,

When we use the filter functionality , when something is entered and the tree is searched and result is shown , the tree is not focussed for traverse if the user wants to traverse the list without using mouse. 
user needs to use the mouse to focus and then use the keyboard keys to traverse. 

Is there any option where the first tree node could be focussed after search is done ? 

Also is there a possibility to highlight the first searched children ?

**Comment by adamkleingit** [comment]
For focusing the tree for key navigation you can call `treeModel.setFocus(value)`
For focusing on the first node you can call `treeModel.getVisibleRoots()[0].focus()`

**Comment by rubyduby** [comment]
Hi Adam,

I have a problem i can't figure out:

I am using an input field as a searchbox and i am listening for 'Tab' and 'ArrowDown' events, to change my focus to the tree. I followed your advise and after hitting one of these keys the first node is indeed highlighted. However my input still has focus and i cannot go on and use keyboard navigation. 

Is there a way to switch focus to the tree from another input?

**Comment by Smitha-Patil** [comment]
I am also facing the same problem. Did any one find a solution?
