### ISSUE TITLE
Add DragEnter event and allow the allowDrop function to be overridden from inside that

### ISSUE THREAD

**Issue by parasjain95** [500tech/angular-tree-component#277]
This will allow to carry out time consuming actions in only entering the target element. Which will solve the issue of performing operation in dragover event and computations will be performed limited number of times. In dragover the calculations are performed even if we are over the same element. This makes it very costly operation if we put allowdrop in that. 
My code inside allow drop takes about 70 milliseconds. And if dragover is called about 50 times then total time for one drag is about 70*50 ms, i.e., 3500 ms or 3.5 sec. This is useless as same operation has been performed multiple times. It would be so much better to achive the same using dragenter. Kindly add dragenter to this library as soon as possiblem or suggest me another way to achieve what i want.

Thank you.

**Comment by tobiasbrenner** [comment]
Hallo @parasjain95 ,

I totally agree with you. This is a issue for me too. I'd love to see it fixed.
