### ISSUE TITLE
Tree Component jumps selection on select

### ISSUE THREAD

**Issue by tashoecraft** [500tech/angular-tree-component#278]
Hi,

When my tree has around greater than 15 nodes, a selection can cause a jump. I've been able to reproduce it consistently if you click a bottom node and it shoots to the middle of the view, but sometimes it happens in a less reproducible way. 

Here is a gif of what I am talking about: http://g.recordit.co/AAFQPHoLDf.gif .

I can understand if this is an intended behavior, as sometimes a node is too low to fully be seen and when clicked it is brought into view, but is there a way to turn it off/make is less jarring? 

There is a time in the gif when I click "test16" which is just below center, and it jumps as well. So it's not allows a bottom node. 

I'm using angular 4.0.2 and tree component 3.3.1, my options are for the component are 
      nodeHeight: 50,
      useVirtualScroll: true,
      dropSlotHeight: 0 ,

I know useVirtualScroll is intended for very large trees, but I was experiencing the issue with very small trees before I turned it on. While the example tree is only about 60 nodes, the tree could be very large as this is a google drive picker and it all depends on the user for how big the tree will be.

**Comment by tashoecraft** [comment]
After digging through the component, I'm pretty sure the styles my designer put in are messing with it calculating scrolling

**Comment by chuihinwai** [comment]
What were the styles that caused this problem? I'm experiencing similar behaviour. Although mine jumps occasionally, which is extra harder to track down this bug
