### ISSUE TITLE
Filtering on other properties than name

### ISSUE THREAD

**Issue by tomasznastaly** [500tech/angular-tree-component#279]
Hi,
It seems to me, that filtering on other properties doesn't work. 
Example from documentation:
  filterFn(value, treeModel: TreeModel) {
    treeModel.filterNodes((node) => {
      fuzzysearch(value, node.data.name)
    });
  }

If i replace the name with other data property from my objects:
  filterFn(value, treeModel: TreeModel) {
    treeModel.filterNodes((node) => {
      fuzzysearch(value, node.data.qualifications)
    });
  }
it stops working.

When i search by name, it works correctly.

When i switch to node.data.qualifactions (string) and I fill input with searched value, then the whole tree disappears. 

So it's possible to filter by other values?

**Comment by adamkleingit** [comment]
Hi,
The example has a bug, because the filter function doesn't return a value.
It should be:
```
treeModel.filterNodes((node) => fuzzysearch(value, node.data.name));
```

I'll fix the example
