### ISSUE TITLE
node dropped over a parent should be appended in the end, not in the beginning

### ISSUE THREAD

**Issue by parasjain95** [500tech/angular-tree-component#282]
1) It is usually expected that on dropping over a parent the node will be appended in the end and not in the beginning. Kindly make this change. I need to use it for an important project. 
2) Also parent should not be allowed to be moved over children. If someone tries to drag a node then it must be either collapsed while doing so or something else must be done to achieve this

**Comment by adamkleingit** [comment]
1. That makes sense, although because of backwards compatibility I prefer not to make this change now. You can override actionMapping.mouse.drop and provide your own function
2. The tree prevents dropping a parent onto a child

**Comment by parasjain95** [comment]
yes i have overriden it for me. It was just a suggestion for a little betterment. Thanks
