### ISSUE TITLE
provide a way to add the hover and select over the element with class "node-wrapper".

### ISSUE THREAD

**Issue by parasjain95** [500tech/angular-tree-component#284]
I want to have full width of a node and just the children should apper as tabbed. The hover must apper over entire row and not just the content of the node. Can you provide something for that? Or is it possible to achieve the same using existing options? 
I have added a screenshot of what i want to achieve. Kindly help.
Thank you.
![navigation pane](https://cloud.githubusercontent.com/assets/18498327/25572018/424cc89c-2e54-11e7-8ae2-7b48d10e39d0.PNG)

**Comment by adamkleingit** [comment]
Hi,
you can achieve this with levelPadding option.
All the best

**Comment by johaven** [comment]
Hi, just one question: is there a way to apply click on node wrapper (and not on node-content-wrapper) ?

**Comment by johaven** [comment]
A temporary solution pending a cleaner way:
```javascript
<tree-root [nodes]="nodes" [options]="options" (click)="onClick($event)"></tree-root>

onClick(event) {
        event.preventDefault()
        if (event.target.className === 'node-wrapper') {
            event.target.lastElementChild.click()
        }
    }
```
Ugly but working :)
