### ISSUE TITLE
cant override .node-drop-slot.is-dragging-over 

### ISSUE THREAD

**Issue by parasjain95** [500tech/angular-tree-component#285]
I want to give my own styling to drop slot on dragging over using ".node-drop-slot.is-dragging-over " but nothing is working. Kindly help.
Thank you.

**Comment by adamkleingit** [comment]
Hey,
overriding with a more specific selector in styles.scss works for me

**Comment by parasjain95** [comment]
Ok. Thanks for your reply.
There is one more way. Add attribute override to body tag - <body override>
and add [override] before every css that you want to override. eg:-
[override].node-drop-slot.is-dragging-over {
 // your custom css
}
