### ISSUE TITLE
Changes not reflected immediately when functions call from another application

### ISSUE THREAD

**Issue by parasjain95** [500tech/angular-tree-component#286]
I am using this library inside another application (can't reveal). When i make a change to that application, I call a function to reflect the same in the navigation pane. But the changes are reflected only after i click back to the area where my navigation pane exists. Why are these changes not showing immediately after an operation? What can i do to achieve it? Kindly help.
Thank you

**Comment by adamkleingit** [comment]
Hi,
Can you explain a bit more?
What do you change and what do you expect to see in the UI?

**Comment by parasjain95** [comment]
I am using this library using cefSharp browser in another application. So when i make a change like rename, delete or insert, i have called corresponding functions of angular. And i am sure those are executed perfectly but the view is not updated until i click somewhere on the browser pane.

**Comment by adamkleingit** [comment]
Angular's change detection starts working automatically if something happens on the browser (setTimeout, ajax, event listener fired) using ZoneJS.
It sounds like ZoneJS doesn't work with cefSharp and is not an issue specifically with the tree module.

**Comment by parasjain95** [comment]
I found the solution. I just called the change detection method from angular and it works. I made the tree variable global to create an interface for cefsharp due to which change detection was not working automatically.

**Comment by parasjain95** [comment]
You can close this issue. As the only solution is to call change detection method from angular
