### ISSUE TITLE
useVirtualScroll with custom templates

### ISSUE THREAD

**Issue by obiwan007** [500tech/angular-tree-component#289]
Still having problems using virtual scroll option.
I'm using a rather complex custom styling/template for the tree Elements, but it renders really nice in non virtual mode. 
If I switch it on, nothing is shown at all in the tree...
Here are my Options:

`this.customTemplateStringOptions = {
      displayField: 'displayName',
      isExpandedField: 'isExpanded',
      idField: 'uriKey',
      getChildren: this.getChildren.bind(this),
      allowDrag: false,
      actionMapping,
      useVirtualScroll: true,
      nodeHeight: 32
    };`

Here is the html what Chrome is rendering:

```
<tree-root _ngcontent-c3="" class="treeGrid" fxflex="" style="flex: 1 1 1e-09px; box-sizing: border-box; -webkit-box-flex: 1;" ng-reflect-options="[object Object]" ng-reflect-flex="" ng-reflect-class-base="treeGrid" ng-reflect-nodes="[object Object]">
    <tree-viewport _nghost-c13="">
    <!----><!---->
      <div _ngcontent-c13="" style="height: 378px;">
        
      <div class="tree">
        <!--bindings={
  "ng-reflect-ng-if": "[object Object]"
}-->
    <tree-node-collection ng-reflect-nodes="[object Object]" ng-reflect-tree-model="[object Object]" ng-reflect-templates="[object Object]">
    <!----><!---->
      <div style="margin-top: 0px;">
        <!--bindings={
            "ng-reflect-ng-for-of": "",
            "ng-reflect-ng-for-track-by": "function (index, node) {\n     "
          }-->
      </div>
    
  </tree-node-collection>
        <!--bindings={
  "ng-reflect-ng-if": "false"
}-->
      </div>
    
      </div>
    
  </tree-viewport>
  </tree-root>_

```
The template is based on
 <ng-template #treeNodeFullTemplate

We are using @angular/flex-layout.
angular-tree-component: "3.5.0"

**Comment by obiwan007** [comment]
Fixed it - forgot to add the 
this.tree.sizeChanged(); 
call.
Unfortunately the rendering is not as smooth as without virtual scroll but the performance with >1000 nodes is way better.

**Comment by grimace** [comment]
I don't understand where ( from what context ) do I call "this.tree.sizeChanged()"?
