### ISSUE TITLE
id = 0 for node is replaced with uuid()

### ISSUE THREAD

**Issue by erasethis** [500tech/angular-tree-component#290]
For our root node we have 

    let root = {
       id: 0,
       name: 'All'
    };

We can't easily change that, it's hardwired in our DB via

    parentId === 0

for top level elements. The problem is, this ID is replaced with a UUID somewhere down the line, because 0 evaluates to falsy.

    constructor(public data: any, public parent: TreeNode, public treeModel: TreeModel, index: number) {
       this.id = this.id || uuid(); // Make sure there's a unique ID
       this.index = index;

       if (this.getField('children')) {
          this._initChildren();
       }

       this.allowDrop = this.allowDropUnbound.bind(this);
    }

By the way, this is version 3.3.1 but the offending code is the same in the current repo.

**Comment by adamkleingit** [comment]
Hey @erasethis 
Thanks for the PR - I made a comment

**Comment by adamkleingit** [comment]
Fixed and released
