### ISSUE TITLE
How to differentiate between making an element as first child and dropping it over the parent?

### ISSUE THREAD

**Issue by parasjain95** [500tech/angular-tree-component#293]
If i drop a node as first child and if i drop it over the parent, in both the cases i get same information, i.e. from, to.parent and index. So if i want to change the functionality to append a node in the end instead of beginning. How can i do it? I need this difference for allowDrop and drop both.

**Comment by adamkleingit** [comment]
Hi,
I will add a `dropOnNode` boolean value to the `to` object in the coming release

**Comment by parasjain95** [comment]
Ok. So if it will be true then it will be on the parent node and if it will be false then it will be first child?

**Comment by adamkleingit** [comment]
Yes.
Added in 3.7.0

**Comment by parasjain95** [comment]
Thank you. You are doing a great job. I am extensively using your library. I wish it gets popular enough like extJs is.
