### ISSUE TITLE
type {} is not assignable to type 'IActionMapping'.

### ISSUE THREAD

**Issue by avneeshroks** [500tech/angular-tree-component#296]
Hi,

I am using "angular-tree-component": "^3.4.0", and i am trying to do somthing like this,

`const actionMapping:IActionMapping = {
  mouse: {
    drop: (tree : Page, node : any, $event : any, {from, to}) => {
      console.log(node);
      console.log(from);
      console.log(to);
      TREE_ACTIONS.MOVE_NODE;
    }
  }
};`

as mentioned in documentation, over here https://angular2-tree.readme.io/docs/action-mapping

but i am facing error as :

`{ mouse: { drop: (tree: Page, node: any, $event: any, {from, to}: { from: any; to: any; }) => voi...' is not assignable to type 'IActionMapping'.`

Any help will be appriciated.

Thanks.

**Comment by adamkleingit** [comment]
What's the `Page` type you are trying to use for `tree`? The correct type is `TreeModel`:
```
import { TreeModel } from 'angular-tree-component';
```
