### ISSUE TITLE
isHidden field is no longer functioning at all

### ISSUE THREAD

**Issue by waynechaw** [500tech/angular-tree-component#297]
I have set the isHidden field to true but the node is not being hidden. I also tried changing the default hidden field to something else like "hidden" (isHiddenField: 'hidden')  but still doesn't work. This is happening in 3.5. We were using 2.2 before and it was working.

example code: 

```                    
nodes = [
  {
    id: 1,
    name: 'root1',
    isExpanded: true,
    children: [
      {
        id: 2,
        name: 'child1',
        isHidden: true
      }, {
        id: 3,
        name: 'child2'
      }
    ]
  }
];
```

child1 still displays in tree

just tried multiple versions, v2.8 is the last version in which hiding nodes is working

**Comment by cimachris** [comment]
I am having this same issue.  
v3.6.0
Same setup as above.

**Comment by adamkleingit** [comment]
@cimachris @waynechaw 
True, this is a breaking change.
You can use `show` or `hide` or `setIsHidden(true / false)` methods on the TreeNode instead.
Alternatively - call `treeModel.setIsHidden({ id }, true / false)` and pass it the node ID.

Please let me know if it works for you

**Comment by amunra2112** [comment]
Can you please update your documentation https://angular2-tree.readme.io/docs/inputs as this field is still described there.

**Comment by adamkleingit** [comment]
Updated.
Also updated here:
https://dash.readme.io/legacy/project/angular2-tree/v3.7.0/docs/filtering

**Comment by waynechaw** [comment]
https://angular2-tree.readme.io/docs/options#ishiddenfield

still mentions the hidden field here

**Comment by cimachris** [comment]
I got it working.  

import { TreeComponent } from 'angular-tree-component';

--in my export class
@ViewChild(TreeComponent)
private tree: TreeComponent;



-- in some of my code on buttons
this.tree.treeModel.setIsHidden({id: 'taskSummary'}, true);

**Comment by WeiChienHsing** [comment]
if I want to hide some of my nodes when initializing the tree, how can I do it ?
