### ISSUE TITLE
Can't dynamically add a node inside another node

### ISSUE THREAD

**Issue by joyanta** [500tech/angular-tree-component#301]
Hi,

I have global tracks what node is selected (THIS WORKS):

class TreeNodeSelection {
    constructor(public tree: TreeModel, public node: TreeNode) {    
    }
}
let treeNodeCurrentSelection: TreeNodeSelection;

//
@ViewChild('tree') tree: TreeComponent;
 nodes: any[];

// then I have ........PERFECT and works... but look down......
 this._someService.rootNodeCreationSource$.subscribe(rootNode => {
            this.tree.treeModel.nodes.push(rootNode);
            this.tree.treeModel.update();
            ///treeNodeCurrentSelection = new TreeNodeSelection(this.tree.treeModel, rootNode);
 });

// The followoing DOES NOT ----------NOT WORK AT ALL--------------.
this._service .nodeCreationSource$
            .subscribe(createdNode => {
                let newItem: TreeNode = new TreeNode(createdNode ,
                    treeNodeCurrentSelection.node,
                    treeNodeCurrentSelection.tree,
                    treeNodeCurrentSelection.node.children.length);

                treeNodeCurrentSelection.node.children.push(newItem); <----I can see the node 

                treeNodeCurrentSelection.tree.update(); //BOOM IT DID NOT WORK
            });

JUST TO LET YOU KNOW ...NO NULLS are the issues
 treeNodeCurrentSelection.node.children.push(newItem); <----works
treeNodeCurrentSelection.tree.update(); doesn't....

Can send us a proper example of adding a node ...
not like like the example u already have

    addNode(tree) {
        this.nodes[0].children.push({
            name: 'a new child'
        });
        tree.treeModel.update();
    }

**Comment by parasjain95** [comment]
you should use, 
this.nodes[0].data.children.push('your node');

It will work perfectly fine. It is mentioned in the documentation that you must use data property to access uuid, children

**Comment by adamkleingit** [comment]
Hi,
you shouldn't create TreeNode's or push to treeModel.nodes by yourself.
The idea is to update the original data that you passed to treeModel, and let the treeModel recreate these classes.
You can do it by either replacing the `nodes` input (using immutable data) or by calling `update()`.

As @parasjain95 mentioned, if you are holding a `TreeNode` instance you can access `data` to get the original node.

All the best

**Comment by joyanta** [comment]
hi all resolved. May be i should have posted it earlier.

**Comment by abelkbil** [comment]
@joyanta Can you post the ts file here. I am also looking how to add new node. Thanks

**Comment by antoantonyk** [comment]
@adamkleingit Hi adam, after i upgrade to "angular-tree-component": "^6.0.0" and angular@5.0.5, suddenly the dynamic tree node add/remove functionalities stopped working. Once i collapse and expand, the node will get appear. pls suggest an option.

**Comment by adamkleingit** [comment]
Can you reproduce here?
https://plnkr.co/edit/u5fMmaM14rJ0aqG3k240?p=preview


*Adam Klein*
*Chief Technology Officer*



*Tel.*   +972-52-7475633 <+972527475633>
*Web*  500tech.com <http://www.500tech.com/> | github.com/500tech |
@adamklein500 <http://twitter.com/adamklein500>
