### ISSUE TITLE
getting TypeError: (void 0) is not a function 

### ISSUE THREAD

**Issue by rakeji** [500tech/angular-tree-component#303]
Hi,

I am using angular 2.x and angular-tree-component@3.6.0 with jspm for bundling. I get the error:

core.umd.min.js:31 EXCEPTION: Uncaught (in promise): TypeError: (void 0) is not a function
TypeError: (void 0) is not a function

is there fix for it?.

**Comment by ezzkht** [comment]
Same problem here.

https://github.com/500tech/angular-tree-component/issues/298

**Comment by rafraph** [comment]
Same problem here.

**Comment by chendachao** [comment]
Same problem here.

**Comment by adamkleingit** [comment]
@rakeji Are you using SystemJS?

**Comment by rafraph** [comment]
Yes. Downgrade fix this

**Comment by rakeji** [comment]
@adamkleingit I am using jspm for bundling.

**Comment by elcondedebahia** [comment]
I solved this by downgrading. This is my package.json:

 "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@angular/router": "4.1.1",
    "@angular/upgrade": "4.0.0",
    "angular-in-memory-web-api": "~0.1.15",
    "angular-tree-component": "3.2.3",
