### ISSUE TITLE
Can't dynamically add a node inside another node

### ISSUE THREAD

**Issue by okdevwww** [500tech/angular-tree-component#304]
I don't know how to add node inside another node.
would you like to let me know about it?
thanks

**Comment by okdevwww** [comment]
I have tried as following.
addNode(node, index) {
    node.data.children.push({
      hasChildren:false,
      name: "node3.3",
      subTitle: "new and improved"
      });
  }

**Comment by armsofter** [comment]
Same problem on my side.
