### ISSUE TITLE
how to remove node dynamically?

### ISSUE THREAD

**Issue by okdevwww** [500tech/angular-tree-component#305]
I don't know how to remove node dynamically.
if you let me know about it, I will be appreciated.
thanks,

**Comment by parasjain95** [comment]
Search for splice method on google. Use it with node.data.children array.

**Comment by adamkleingit** [comment]
Either replace the `nodes` input (immutable data) or call `treeModel.update()`

**Comment by sulhome** [comment]
The splice method doesn't work on version 5.0.0 as soon as you call update() the item well be back

```typescript
const itemIndex = nodeToDelete.index;
nodeToDelete.parent.children.splice(itemIndex, 1); // item disappear
this.tree.treeModel.update(); // item comes back again
```
