### ISSUE TITLE
If click on Parent Node and Respective Child Node Should Expanded automatically?

### ISSUE THREAD

**Issue by vishnuchandra** [500tech/angular-tree-component#307]
Hi 
Please tell me How to do it using tree component

**Comment by parasjain95** [comment]
call the expand() method for each node you want to expand on click action in ActionMapping

**Comment by vishnuchandra** [comment]
Im new to angular2 cud u please send me the plunker file

**Comment by adamkleingit** [comment]
You can also call `expandAll()` on the TreeNode.
Please refer to the docs on how to use the tree API:
https://angular2-tree.readme.io/docs/api
