### ISSUE TITLE
Child node not expanding in AOT built version.

### ISSUE THREAD

**Issue by mgkoko** [500tech/angular-tree-component#308]
Hi,

I tried the latest version (3.6.0) also 3.5.0 but it is giving me void 0 is not a function error, I downgraded to version 3.2.3 which fixes the void 0 issue but in the AOT built version of the application the nodes are not expanding. I tried Actionmapping click to EXPAND but that doesn't work either (so neither the expand icon nor the node itself is not expanding the children) The JIT compilation of the application doesn't have the same issue.

Any help?

**Comment by adamkleingit** [comment]
@mgkoko Are you using SystemJS?

**Comment by parasjain95** [comment]
I think SystemJs should not be used. Webpack is gaining popularity for angular and its performance is also good. Also with cli tool being used (whish uses webpack) everyone should move to webpack.

**Comment by mgkoko** [comment]
@adamkleingit sorry for my late reply. I am using SystemJs  in the development version (JIT) but for the live version I am using AOT built https://angular.io/docs/ts/latest/cookbook/aot-compiler.html which is not using SystemJs and the problem is only in AOT built version. 

I am not using angular CLI or webpack, I will try those.

**Comment by gRoussac** [comment]
Hi all, @adamkleingit,

version 3.7.2

When try to compile for production in AOT, starting webpack bundling, I get this error :

```
ERROR in ./aot_temp/~/angular-tree-component/dist/components/tree.component.ngfactory.ts
Module build failed: Error: Can't resolve 'loadChildren' in '...\aot_temp\node_modules\angular-tree-component\dist\components'````

Has anyone any idea what can cause that ? Any help appreciated thanks.

Regards

**Comment by adamkleingit** [comment]
@gRoussac nice catch, I hope they solve it ASAP

**Comment by candidosales** [comment]
I'm having the same error: 

```
ERROR in ./compiled/node_modules/angular-tree-component/dist/components/tree.component.ngfactory.ts
Module build failed: Error: Can't resolve 'loadChildren' in '/home/brasilct/Documents/backoffice-admin/compiled/node_modules/angular-tree-component/dist/components'
```
How does it solve?

**Comment by KeitaElric** [comment]
+1 same error in version 3.8.0
