### ISSUE TITLE
MoveUP/MoveDown button

### ISSUE THREAD

**Issue by agims7** [500tech/angular-tree-component#309]
Hi, I would like to ask if there is any functionality by clicking to move element by 1 index to the top or bottom ???

**Comment by parasjain95** [comment]
Refer this link. Everything is given here.
https://angular2-tree.readme.io/

**Comment by adamkleingit** [comment]
You will need to change the data supplied to the tree and call `treeModel.update()`:
https://angular2-tree.readme.io/docs/changing-the-tree

**Comment by agims7** [comment]
That's not the answer. Let me explain once again. I would like to create button with function to move down selected element or top. So first I need to select element and than clicking on the button this element will go up or down, and if there is any parrent element next to it it will drill down .

**Comment by parasjain95** [comment]
Can you try to show the same with images. Its difficult to understand what you want to achieve. From what i understand, there is no big deal in implementing this

**Comment by agims7** [comment]
![tree](https://cloud.githubusercontent.com/assets/18736434/26294209/60602670-3ec2-11e7-927f-c78928849a55.png)

Let me explain on this image. I just selected row 2, than If I click button move down, row 2 will became row 3 and row 3 will became 2 (that's quite easy to do, manipulating nodes), but if I select for example row 6.3 and click "move down" I would like to move this row to the position of row 7.

**Comment by parasjain95** [comment]
In this case you need to create your own logic. It can be done. You just need to learn how to do it using this library. It is just a play od deleting and inserting nodes from one place to another

**Comment by agims7** [comment]
Is there any way that you will create something like this in the future?

Is there any way, that you will create something like this in the future? Is it possible to point what will be the best way to do it using own logic? The most problematic thing is to enter the parent element and change the position in their children's.

**Comment by parasjain95** [comment]
let targetnode = this.threeModel.getFocusedNode(); OR getActiveNode() // whatever you need.
parent = targetnode.parent
fromindex = targetnode.index;

targetnode contains the index of the selected node that you want to move. You now need to remove your node from that index and insert it to the new index of choice (fromindex+1 , if you want to move it down and  fromindex-1, if you want to move it down). Use splice method as parent.data.children.splice(...);

Read about splice method on internet and do read the documentation
https://angular2-tree.readme.io/

It seems that you are not even trying my friend. You should read this and you will be able to use this library very well

**Comment by agims7** [comment]
Ok thank you. I followed your advice and create my own logic, I will suggest for you if you can create it directly in your code so it will be easier for another users. My `code:

`<button (click)="down(tree)">W dół</button>`
 `<button (click)="up(tree)">Do góry</button>`

  ```
up(tree) {
    let targetnode = tree.treeModel.getFocusedNode();
    let parent = targetnode.parent
    let fromindex = targetnode.index;
    let clone = parent.data.children[fromindex]
    let newIndex = fromindex - 1;
    let nextRow = parent.data.children[newIndex];
    if (newIndex < 0) {
      tree.treeModel.focusPreviousNode();
      let next = tree.treeModel.getFocusedNode();
      if (targetnode.id === next.id) {
        return false;
      }
      tree.treeModel.focusNextNode();
      let newParentIndex = next.index;
      next.parent.data.children.splice(newParentIndex, 0, clone);
      parent.data.children.splice(fromindex, 1);
      tree.treeModel.update();
      return false;
    }
    if (nextRow.children.length > 0) {
      let nextRowSum = nextRow.children.length;
      tree.treeModel.focusPreviousNode();
      let nextElement = tree.treeModel.getFocusedNode();
      if (nextElement.hasChildren) {
        tree.treeModel.focusDrillDown();
        for (let i = 0; i < nextRowSum + 1; i++) {
          tree.treeModel.focusNextNode();
        }
      } else {
        tree.treeModel.focusNextNode();
      }
      let nextRowElement = nextRow.children;
      nextRowElement.push(clone);
      parent.data.children.splice(fromindex, 1);
    } else {
      parent.data.children.splice(fromindex, 1);
      parent.data.children.splice(newIndex, 0, clone);
    }
    tree.treeModel.update();
  }
```
----------------------------------------------------------------------------------------------
 ```
 down(tree) {
    let targetnode = tree.treeModel.getFocusedNode();
    let parent = targetnode.parent
    let fromindex = targetnode.index;
    let clone = parent.data.children[fromindex]
    let newIndex = fromindex + 1;
    let nextRow = parent.data.children[newIndex];
    let collapsed;
    if (newIndex > parent.data.children.length - 1) {
      if (tree.treeModel.getFocusedNode().isCollapsed === false) {
        collapsed = false;
        tree.treeModel.focusDrillUp();
      }
      tree.treeModel.focusNextNode();
      let next = tree.treeModel.getFocusedNode();
      if (targetnode.id === next.id) {
        if (next.parent.parent === null) {
          return false;
        } else {
          let newParentIndex = next.parent.index + 1;
          next.parent.parent.data.children.splice(newParentIndex, 0, clone);
          next.parent.data.children.splice(fromindex, 1);
          tree.treeModel.update();
          return false;
        }
      }
      tree.treeModel.focusPreviousNode();
      let newParentIndex = next.index;
      next.parent.data.children.splice(newParentIndex, 0, clone);
      parent.data.children.splice(fromindex, 1);
      if (collapsed === false) {
        tree.treeModel.focusDrillDown();
      }
      tree.treeModel.update();
      return false;
    }
    if (nextRow.children.length > 0) {
      tree.treeModel.focusNextNode();
      if (tree.treeModel.getFocusedNode().isCollapsed) {
        tree.treeModel.focusDrillDown();
      } else {
      }
      tree.treeModel.focusPreviousNode();
      let nextRowSum = nextRow.children.length;
      let nextRowElement = nextRow.children;
      nextRowElement.unshift(clone);
      parent.data.children.splice(fromindex, 1);
    } else {
      parent.data.children.splice(fromindex, 1);
      parent.data.children.splice(newIndex, 0, clone);
    }
    tree.treeModel.update();
  }
```
