### ISSUE TITLE
Cant Move expander inside the content-wrapper

### ISSUE THREAD

**Issue by shruthi-meda** [500tech/angular-tree-component#310]
Hi
Am trying to move the expander inside the content-wrapper. So at render time, i see my own expander icon and title of the node inside the same rectangle.

<ng-template #treeNodeWrapperTemplate let-node let-index="index">
    <div class="node-wrapper" [style.padding-left]="node.getNodePadding()">
      
      **<div class="node-content-wrapper"**
        [class.node-content-wrapper-active]="node.isActive"
        [class.node-content-wrapper-focused]="node.isFocused"
        (click)="node.mouseAction('click', $event)"
        (dblclick)="node.mouseAction('dblClick', $event)"
        (contextmenu)="node.mouseAction('contextMenu', $event)"
        (treeDrop)="node.onDrop($event)"
        [treeAllowDrop]="node.allowDrop"
        [treeDrag]="node"
        [treeDragEnabled]="node.allowDrag()">
        **<tree-node-expander class=" glyphicon glyphicon-chevron-down" style="display:inline-block" [node]="node"></tree-node-expander>**
        <tree-node-content [node]="node" [index]="index"></tree-node-content>
      </div>
    </div>
  </ng-template>

But i dont see it being honored at the render time, its reset to the default markup, back to being at sibling level to node-content-wrapper.
<div class=..>
      <tree-node-expander... />
       <div class="node-content-wrapper" ..../>
</div>

Is this possible at all ? Am i missing something?

**Comment by adamkleingit** [comment]
Hi this is strange, can you share the entire file?

Please take a look at the example's code and see if you missed anything:
https://github.com/500tech/angular-tree-component/blob/master/example/cli/src/app/templates/templates.component.ts

**Comment by shruthi-meda** [comment]
Hi 
Thanks, think it was my browser acting up. A restart helped.

**Comment by nileshpatva** [comment]
I want to replace the existing expander with the font awesome icon **fa-plus-square-o**, how can I do that. Thanks

**Comment by darshansimha** [comment]
@nileshpatva did you find a solution to that, I am also trying to add a custom icon to the tree.
