### ISSUE TITLE
Prevent Drag For a Single Node in the Tree

### ISSUE THREAD

**Issue by avneeshroks** [500tech/angular-tree-component#311]
Hi,

I am using "angular-tree-component": "^3.4.0".

Is there any way of preventing drag for a single node in the tree ?

Thank you

**Comment by parasjain95** [comment]
make your own function for allowDrag. Inside it return false if node.data.children.length==0 otherwise return false

**Comment by adamkleingit** [comment]
What @parasjain95 said....
