### ISSUE TITLE
Drag and drop from lower index to higher index under same parent gives wrong index.

### ISSUE THREAD

**Issue by parasjain95** [500tech/angular-tree-component#312]
Hi,
When i am implementing my own drop and i drag a node from lower index to higher index under same parent the to.index is one more than it should be. It considers the node that is about to be moved. Thus giving index one higher than what it would actually be

**Comment by adamkleingit** [comment]
Hi,
The index fixing logic should be handled by you.
The library cannot guess what behaviour you want to implement (imagine you want to copy the node, not move it).

Take a look at `moveNode` method in `lib/models/tree.model.ts` for reference
