### ISSUE TITLE
When is the context menu getting added to this library?

### ISSUE THREAD

**Issue by parasjain95** [500tech/angular-tree-component#313]
I am using this library for industrial purpose. Soon there will be a need for context menu. When are you planning to do it. 
Kindly add it as soon as possible and try to keep it as independent as possible from current code because no one would prefer make drastic changes to their codes to add context menu. 

Thank you

**Comment by adamkleingit** [comment]
Hi,
1) Context menu can be implemented using a custom template. I prefer to keep it outside of the tree library.
2) All the changes that we introduce to the tree are backwards compatible whenever possible
3) I remind you that this is an open source library, if you need any urgent feature you are more than welcome to suggest it and if it's accepted then make a pull request with it to contribute back.
