### ISSUE TITLE
Drag and drop sometimes causes root node to appear as hovered

### ISSUE THREAD

**Issue by parasjain95** [500tech/angular-tree-component#314]
After Drag and drop is done on root node it appear as hovered. This makes two nodes appear as hovered.

**Comment by adamkleingit** [comment]
Hi, which version of the library are you using? If it's 3.7.0 then this bug was fixed in 3.7.1

**Comment by parasjain95** [comment]
Ok thank you. I was using an older version. I will try with newer one.
Thanks

**Comment by adamkleingit** [comment]
Awesome
