### ISSUE TITLE
Limit the depth of the tree

### ISSUE THREAD

**Issue by sm-ie** [500tech/angular-tree-component#315]
Hi,
Is it possible to limit the depth of the tree? Say it can only allow drag and drop upto 3 levels etc? I cant seem to find it documented.
Thanks

**Comment by adamkleingit** [comment]
Yup using allowDrop function:
https://angular2-tree.readme.io/docs/drag-drop#options

**Comment by sm-ie** [comment]
Thanks, is there a simpler way to know the current level depth than parsing the tree structure?
