### ISSUE TITLE
I want to drag with right mouse button.How can I do it?

### ISSUE THREAD

**Issue by WeiChienHsing** [500tech/angular-tree-component#320]
I want to drag with right mouse button.How can I do it?
If it can't be done in current version, which file do I need to modify in order to do this?

**Comment by parasjain95** [comment]
You can do it using action mapping.
see documentation :-
https://angular2-tree.readme.io/

**Comment by WeiChienHsing** [comment]
@parasjain95 
I tried.I can select tree nodes by clicking right button.But I still can't figure out how to drag a tree node by using right click.Can you give me a more specific code snippet?

**Comment by parasjain95** [comment]
Ok. That may not be possible using this library as of now. This is not a very regular requirement. You can try to find some workaround on the internet
