### ISSUE TITLE
options.animateSpeed is ignored

### ISSUE THREAD

**Issue by dae721** [500tech/angular-tree-component#321]
Version 3.7.2. Setting options.animateSpeed has no effect. Looks like there's a typo in tree-node-children.component.ts:

```
*treeAnimateOpen="
            node.isExpanded;
            speed:node.options.animateExpand;  <== should be animateSpeed
            acceleration:node.options.animateAcceleration;
            enabled:node.options.animateExpand">
```

Setting a breakpoint in tree-animate-open.directive.js, I can see that after setting `var delta = this.animateSpeed;`, delta is `true`, which gets treated as 1 in the maxHeight calculation.

**Comment by adamkleingit** [comment]
Thanks,
will be fixed in coming version
