### ISSUE TITLE
Node Elements from more then one source/property

### ISSUE THREAD

**Issue by TsengSR** [500tech/angular-tree-component#324]
I couldn't find a way on how to render tree elements from different properties, i.e. attributes and elements from an XML like structure 

```
let nodes = [{
   name: 'root',
   elements: [{
      name: 'child',
   }],
   attributes: [{
      name: 'attribute',
   }]
}]
```

Now I want to render both, elements and attributes as elements of root node, just display them differently (i.e. adding @ in front of attributes or using special styling). 

Can it be done somehow with the `#treeNodeFullTemplate`?

**Comment by adamkleingit** [comment]
Hi,
This is not supported in the tree, you'll have to transform your data structure into a single children array.

All the best
