### ISSUE TITLE
Export the node data to an xml

### ISSUE THREAD

**Issue by akumar999** [500tech/angular-tree-component#325]
Hi I am trying to use angular-tree-component for editing an xml, so that it can allow users to update it on UI. My Question is will we be able to export the node data to an xml, is that possible using angular-tree-component api? Once I am done adding a new node and have a export button where I can export as a file/xml . Kindly suggest.

**Comment by adamkleingit** [comment]
Hi,

you can use the models API to iterate over the nodes and get all the data you need.
Check out ITreeModel and ITreeNode here:
https://angular2-tree.readme.io/docs/api
