### ISSUE TITLE
AOT build error

### ISSUE THREAD

**Issue by ghaiat** [500tech/angular-tree-component#329]
Hi,

After reinstalling angualr-tree-component today, (i think mobx was updated), i get the following error when trying to build in AOT:

ERROR in vendor.944793091c384ffbdf0c.bundle.js from UglifyJs
Unexpected token: name (BaseAtom) [vendor.944793091c384ffbdf0c.bundle.js:124991,6]

BaseAtom is coming from mobx.... What can we do ?

Thank you

**Comment by btroncone** [comment]
@ghaiat Same issue I am having

https://github.com/500tech/angular-tree-component/issues/328

**Comment by btroncone** [comment]
Looks like MobX in general is broken.

https://github.com/mobxjs/mobx/issues/1039

**Comment by btroncone** [comment]
@ghaiat In the short term you can install `"mobx": "3.1.11",`  in your project to get past the error.

**Comment by ghaiat** [comment]
@btroncone thanks i ll try that

**Comment by ghaiat** [comment]
i can confirm it works by downgrading to 3.1.11

**Comment by sh977218** [comment]
It's caused by upgrade mobx from 3.1.11 to 3.1.12.
the solution is that let npm use 3.1.11 instead of 3.1.12 of angular-tree-component 3.6.0
In
` npm-shrinkwrap.json`
add:
`{
    "name": "angular-tree-component",
    "version": "3.6.0",
    "dependencies": {
      "mobx": {
        "version": "3.1.11"
      }
    }
  }`

**Comment by btroncone** [comment]
Looks like this is resolved now in 3.1.13

**Comment by ludetc** [comment]
3.1.13 does not work for us with AOT.
sh977218 solution above is the way to go at the moment, with this 

`    "angular-tree-component": {
      "version": "3.6.0",
      "dependencies": {
        "mobx": {
          "version": "3.1.11"
        },
        "mobx-angular": {
          "version": "1.5.0",
          "dependencies": {
            "mobx": {
              "version": "3.1.11"
            }
          }
        }
      }
    }
  }`

**Comment by adamkleingit** [comment]
I fixed the MobX version to exactly 3.1.11 in angular-tree-component@3.7.3 until MobX fixes this issue.

**Comment by elvirdolic** [comment]
Why using mobx at all?

**Comment by jderus** [comment]
All of this information really needs to go into your readme instead of buried in issues. 
It is a barrier to new users.

The readme need to hit the target of "How do I use this in an Angular CLI app in less than 5 minutes".
It currently, does not.

**Comment by adamkleingit** [comment]
Thanks for the suggestion.
Do you want to make a pull request to fix the Readme?

Thanks!

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633
