### ISSUE TITLE
drag external item drop into tree does not work on firefox.

### ISSUE THREAD

**Issue by sh977218** [500tech/angular-tree-component#332]
I'm using:
angular tree component: 3.7.3. 
Firefox: 53.0.3
The drag and drop feature within the tree works good on Firefox. But this does not work when drag an external item and drop into an existing tree. I'm not even able to drag the external item at all. Is this feature supported in Firefox?  Or it's a bug?

**Comment by adamkleingit** [comment]
Hey @sh977218 ,
Are you using the tree-drag directive?

**Comment by shawinder** [comment]
I am facing different issue. External element drop giving `from` as null but `to` object works fine.
I am using following code.

```
options = {
        actionMapping: {
            mouse: {
                drop: (tree:any, node:any, $event:any, {from, to}:any) => {
                    console.log('drag', from, to); // from === {name: 'first'}
                    // Add a node to `to.parent` at `to.index` based on the data in `from`
                    // Then call tree.update()
                }
            }
        }
    };

<p [treeDrag]="{name: 'first'}" [treeDragEnabled]="true">Drag me!</p>
```

**Comment by shawinder** [comment]
I found the issue. I was using multiple Tree modules for drag and actual tree. It's working fine after using same module for both drag element and the tree component.

**Comment by adamkleingit** [comment]
@shawinder glad you solved it.
@sh977218 if you have any new information please supply.
Thanks
