### ISSUE TITLE
Enhancement: Changing a node to text field on double click

### ISSUE THREAD

**Issue by sayumani** [500tech/angular-tree-component#335]
Hi,

I am looking for a soultion to change the double clicked node to text field.Do we have any option for that in lates build if so please let me know.

Thanks,
Sayooj V R

**Comment by adamkleingit** [comment]
Yes, `options.actionMapping.mouse.dblClick`.
Please refer to the docs about action mapping:
https://angular2-tree.readme.io/docs/action-mapping
