### ISSUE TITLE
hide a node in my treeview. Its not working.

### ISSUE THREAD

**Issue by jonathanohayon** [500tech/angular-tree-component#343]
Hi,

I am trying to hide a node in my treeview. Its not working.
options = { isHiddenField: 'hidden' }
  nodes = [
    { id: 1, hidden: true, name: 'node1'},
    { id: 2, name: 'node2'},

Thanks

**Comment by andrpelz** [comment]
Hello,

I have the same problem. The 'isHiddenField' option is not working.

I have write a simple demo with the last tree version 3.7.3 to test it. Here is the code:
```
<tree-root [nodes]="nodes" [options]="options"></tree-root>
```
```
  options = { isHiddenField: 'hidden' }
  
  nodes = [
    {
      id: 1,
      name: 'root1',
      children: [
        { id: 2, hidden: true, name: 'child1' },
        { id: 3, name: 'child2' }
      ]
    },
    {
      id: 4,
      name: 'root2',
      children: [
        { id: 5, name: 'child2.1' },
        {
          id: 6,
          name: 'child2.2',
          hidden: true,
          children: [
            { id: 7, name: 'subsub' }
          ]
        }
      ]
    }
  ];
```

**Comment by akalitenya** [comment]
i have same problem

**Comment by finalxcode** [comment]
+1

**Comment by adamkleingit** [comment]
Hi,
isHiddenField is not in use anymore. I will update the docs and remove it from treeOptions.
You can call hide() / show() on a tree node,
or use the new binding to tree state (which will be introduced in 3.9.0).
