### ISSUE TITLE
Add support for formControl & ngModel

### ISSUE THREAD

**Issue by thekalinga** [500tech/angular-tree-component#344]
Since this component can be used as an input in forms, the component should ideally be supporting `ngForm` apis such as `formControl` & `ngModel` so that this seemlessly works with other inputs

**Comment by adamkleingit** [comment]
Hi,
can you explain? How can a tree be an input?
Thanks

**Comment by thekalinga** [comment]
If we are creating a user & the user belongs to multiple teams. In the user creation form, we need to select the most granular team he belongs to so that his accesses might be restricted.

Or In my case, user can specify his preferred vehicle type while creating a shipment & vehicle types are usually hierarchies.

In general case, tree can be used as an input where the user needs to select from a hierarchy as input

**Comment by adamkleingit** [comment]
I think in this case you should wrap the tree with your own ngModel implementation. Having the selected nodes as the "model" is very implementation specific.

**Comment by abelkbil** [comment]
@thekalinga How did you solve it. @adamkleingit ngModel warpper is good. I didn't have that thought. Any code sample links ? Much Thanks
