### ISSUE TITLE
Call custom local function in actionMapping

### ISSUE THREAD

**Issue by rootspain** [500tech/angular-tree-component#346]
When i call my own function myFunc() in actionMapping block - throw error "_this.myFunc()" is not a function.

const actionMapping:IActionMapping = {
  mouse: {
    contextMenu: (tree, node, $event) => {
      $event.preventDefault();
      console.log(node);
      this.myFunc();
    },
    click: (tree, node, $event) => {
      if (node.hasChildren) TREE_ACTIONS.TOGGLE_EXPANDED(tree, node, $event);
  },
  keys: {
    [KEYS.ENTER]: (tree, node, $event) => alert(`This is ${node.data.name}`)
  }
};

**Comment by adamkleingit** [comment]
Hi, this is not an issue with the tree but a bug in your code.
You need to define myFunc on the context where you define the actionMapping.
Good luck

**Comment by DebPP** [comment]
It happened to me and I decided like this

  actionMapping: IActionMapping = {
    mouse: {
      dblClick: (tree, node, $event) => {
        this.myFunction()
      },
    }
  }

options = { actionMapping: this.actionMapping }

-----------------------------------------------------------------------------------------------

 <tree-root #tree [options]="options" [nodes]="nodes"></tree-root>
