### ISSUE TITLE
Unable to set drag image for tree node

### ISSUE THREAD

**Issue by 24hours** [500tech/angular-tree-component#348]
Hi, 
I am trying to implement multiple node drag / drop functionality similar to google drive. 

While the function can be implemented quite easily with action mapping ( thanks dev ! ), there is no way to change the behavior of dragging ghost image. 

We are usually able to change the image with [setDragImage](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/setDragImage).  I tested the api with https://jsfiddle.net/f47zzg7v/2/ . 

The api seems to not working in dragStart event. It seems to me that setTimeout is causing the problem here. I remove the line and setDragImage is working like a charm.

https://github.com/500tech/angular-tree-component/blob/7314f893f1182fed36b29f27bd1a40d0b0fec04a/lib/directives/tree-drag.directive.ts#L25

It also seems to me that drag event are not implemented. Is there a particular reason why ? It would be very helpful for user who wish to implement a more complex drag image using absolute position dom.

**Comment by adamkleingit** [comment]
Hey,
Drag is something that needs to be rewritten to support mobile using regular mouse / touch events.
But for now I guess it's possible to fix the timeout issue and the drag event.
Maybe if you are already into the code - could you make a pull request?
Thanks

**Comment by 24hours** [comment]
Hi,

I can write a patch to fix both issue i mention here. I just want to
confirm the reason behind timeout and absent of drag event.

**Comment by adamkleingit** [comment]
I think for now better leave it as it is and make a fork to fit your needs.
Because I plan to refactor the drag & drop completely soon
