### ISSUE TITLE
getNodeByPath is not working propertly 3.7.3 [clarification/issue]

### ISSUE THREAD

**Issue by djleonskennedy** [500tech/angular-tree-component#349]
Hello 
How to set selected Node ? `getNodeByPath` use id's, however we have to set active `Node` by `path`.

Could you suggest how set node as active property ?

NOTE: in general, we just need get Node by business key, due to our BE api :(

**Comment by adamkleingit** [comment]
You can use `getNodeBy` and pass it any function you like.
Or `getNodeByPath` which uses path, or `getNodeById` which uses id.
You can also change which field is the ID in options.idField.

All the best

**Comment by djleonskennedy** [comment]
@adamkleingit thank you for solution

I've used recursion to find by path

```
this.un = this.products$.subscribe(() => {
      const path = this.path
        ? this.path.trim().split('/') : '';
      const nodes = this.treeRef.tree.treeModel.nodes;
      const [node] = findDeep(nodes, (x: any) => this.path === x.path);
      if (node != null) {
        const _node = this.treeRef.tree.treeModel.getNodeById(node.id);
        _node.ensureVisible();
        _node.toggleActivated();
      }
    });
```

Thank you
