### ISSUE TITLE
Custom toggleExpanded action not working in 2.7.3

### ISSUE THREAD

**Issue by elvirdolic** [500tech/angular-tree-component#350]
Hi,

I have a custom toggleExpanded Action which overrides the default one. The logic will collapse other nodes based on the current node

`export function toggleExpandedAction(tree: TreeModel, node: TreeNode, _$event: any) {
    if (node.hasChildren || node.isRoot) {
        tree.expandedNodes.forEach((expNode) => {
            if (!node.isDescendantOf(expNode)) {
                expNode.collapseAll();
            }
        });
        node.toggleExpanded();
    }
}`

this is working in version 2.7.2 when upgrading to 2.7.3 the logic doesn't work. 

This check gives in 2.7.2 a true:  if (!node.isDescendantOf(expNode)) { and in 2.7.3 false

**Comment by adamkleingit** [comment]
Strange, I'll look into it.
Feel free to dive into the code and debug it - it will help to solve this issue quicker.

**Comment by adamkleingit** [comment]
Have you tried migrating to the latest version? (5.0.0 and up)?

**Comment by elvirdolic** [comment]
We can close this issue. The reason were the old output events which were removed.

**Comment by adamkleingit** [comment]
Awesome. I suggest looking in the changelog when switching versions, I always write the changes and breaking changes.
