### ISSUE TITLE
disable parent node selection 

### ISSUE THREAD

**Issue by AngularTx** [500tech/angular-tree-component#353]
In the tree view , i would like to disabled the selection of the parent node . 
->Parent
   -> child1
   -> child2 

We should be able to only click/select the child nodes. I added ngclass to disable if its a parent node . 
disabling works fine in UI, but i can still click it on parent node and it gets selected .

**Comment by adamkleingit** [comment]
Hi, you can use actionMapping.mouse.click and override the default behaviour

**Comment by AjayShivanagol** [comment]
@adamkleingit is it possible to share any live examples?
in my case, I want to disable only a limited selection of parents not all.
