### ISSUE TITLE
Override or set icon sets to use for nodes

### ISSUE THREAD

**Issue by ronnyek** [500tech/angular-tree-component#357]
Greetings... great library. I've got this library integrated and everything works well. 

I can derive the type of node at run time (isLeaf/isFolder whatever), however I dont see any place to specify which icon to use instead of the little left arrow/down arrow. I tried overriding the default wrapper template, but that looks like that utilizes the "expander" component, which I cant find theme/setting info on. 

Is there an easy way to just say if its folder and open, use this icon, if its folder and closed use this icon, otherwise use icon specified on the node?

I looked through documentation and it seemed like the best I could do is apply a style to the node dyamically based on that data.

btw, if I can figure out how to do this I can potentially contribute a few themes based on other html trees

**Comment by sderrico** [comment]
Ho Ho Ronnyek!

From my comprehension, the icon is set by a css class and managed as follow:

.toggle-children contains a style background-image

Depending of the state collapsed or expanded:

toggle-children-wrapper-expanded style transform: rotate(0);
toggle-children-wrapper-collapsed style transform: rotate(90);

Is it helpful?

Thanks!
Seb

**Comment by ronnyek** [comment]
I'll look into this... still doesnt seem like an ideal way to provide icon themes, but... may work.  So long as what you are saying is I could conceivably just override toggle-children-wrapper-collapsed and expanded

**Comment by adamkleingit** [comment]
@ronnyek 
To override the expander icon - like @sderrico said you can use the classes and supply your own icons / style
To add an icon - if it's to the right of the expander you can use the `treeNodeTemplate`, otherwise use the `treeNodeWrapperTemplate`
