### ISSUE TITLE
Custom component in tree node

### ISSUE THREAD

**Issue by iamsarav** [500tech/angular-tree-component#359]
Hi All,

Im new to Angular2 and GitHub as well. Bear with me, if this is not a place to ask for help.

Can anyone let me know how to call components in the tree nodes? 

Thank you.

**Comment by sderrico** [comment]
Ho Ho Iamsarav,

We set a custom template like the demo at https://angular2-tree.readme.io/docs/templates , inside of the custom template, we set our custom component where we pass the node as an input. Inside of your component, it is possible to retrieve your data with node.data.

`<tree-root [nodes]="nodes">
  <ng-template #treeNodeTemplate let-node>
    <custom-component [node]=node></custom-component>
  </ng-template>
</tree-root>`

The input will be of type TreeNode described at https://angular2-tree.readme.io/docs/api

Good luck!
Seb

**Comment by adamkleingit** [comment]
Thanks for the help @sderrico
