### ISSUE TITLE
Request - option to expand only one node at a time

### ISSUE THREAD

**Issue by johaven** [500tech/angular-tree-component#364]
It would be nice to have an option to activate the expanding of one node at a time (except for the root node). Other nodes would automatically collapsed.

I know that is possible with the tree viewChild (and i use it to do this) but it's a cool feature to add for this project :)

**Comment by finalxcode** [comment]
+1

**Comment by adamkleingit** [comment]
Hi,
I'll consider adding it as an option.
In the meanwhile you can use the new tree state binding with action mapping to achieve it quite easily
