### ISSUE TITLE
Wrong Documentation for event activeChanged

### ISSUE THREAD

**Issue by patrickracicot** [500tech/angular-tree-component#367]
In the events section of the documentation, we can still find the event [`activeChanged`](https://angular2-tree.readme.io/docs/events#activechanged).

This events has been removed since the version [`2.8.2`](https://github.com/500tech/angular-tree-component/blob/master/CHANGELOG.md#282-2017-02-21)

**Comment by adamkleingit** [comment]
Fixed, thanks
