### ISSUE TITLE
Somehow enable local encapulation of styles

### ISSUE THREAD

**Issue by ronnyek** [500tech/angular-tree-component#368]
So things are working very well with styles... but rather than having a just some style classes we're responsible for overriding, and to make things more styleable... would it be possible to have some place to set a class, and simply have the class rendered in say the toplevel component... and then use that for styling?

The specific scenario I am dealing with... I've got a component that encapsulates tree component. I'd like to encapsulate the styling so as to not stomp on any other usage. If I use the local styles (somecomponent.scss) and set up the styles per the styling wiki article, the styles simply don't get applied without setting view encapsulation to none.  Flipping it to none, would effectively render that style at the toplevel without re-writing which effectively overwrites the style of all trees.

Scenario 2, I'd like to display the tree component, and like to have a single css file with simple themes (working on theme support per the help request). I could have theme be a class like .plain, .bootstrap etc, and ultimately render two tree components with totally diff themes just by switching a top level class.

These suggestions aren't necessarily suggestions on how to deliver the end functionality, but questions about how to achieve this so as to end up with a more modular, encapsulated component.

**Comment by adamkleingit** [comment]
Hi,
I think I need to update the example.
Can you try to override styles in styles.scss and scoping to a class that surrounds the tree?

I really don't know how else I can achieve an overridable style

**Comment by ronnyek** [comment]
I've not paid a huge amount of attention to how other libraries achieve this... Even if it was just a top level tree class, and then like you said themes could include style name in the selector... does the tree already support this?

**Comment by pumano** [comment]
got same behaviour twice. I can't rewrite styles tree styles from my component.

Need fresh actual examples. And updated documentation

**Comment by pumano** [comment]
I found solution for passing styles from parent component to childrens:

CSS styles should be used with prefix :host and ::ng-deep :

```
:host::ng-deep .toggle-children {
    z-index: 1;
    background-image: none;
    background-color: #333;
}
```

note: **>>>** and **/deep/** is deprecated

Will be good if @adamkleingit add it info to documentation (styling page)

**Comment by adamkleingit** [comment]
Thanks @pumano , I'll investigate it. I wasn't aware of ng-deep.
@ronnyek, since styles in Angular are static, it cannot be passed by as props, unless I make all styles in a separate css file, which I tried to avoid.

**Comment by adamkleingit** [comment]
Moved CSS to an external .css file so it's completely overridable.

**Comment by lifan0127** [comment]
@adamkleingit Could you please elaborate the implication of your recent change (use external css file)? How to take advantage of that for tree styling? I could not find any reference in the documentation.
