### ISSUE TITLE
viewportNodes not updated in TreeNodeCollectionComponent

### ISSUE THREAD

**Issue by pfeigl** [500tech/angular-tree-component#371]
Hi,

we are having a tree with async nodes and also enabled support for adding new nodes. We are using version 3.8.

We also auto-expand nodes when new nodes have been added as child to a node which had no childs sofar.

We are calling treeModel.update() after we apply changes.

Our problem is, that in TreeNodeCollectionComponent the setNodes is called (so it looks like the information that the actual data changed is coming through), but the reaction() which is registered on this.nodes is not actually dispatched. 
Therefor viewportNodes never is updated and thus we won't see the newly added TreeNode.

I checked the example (and also updated it to version 3.8) and everything is working nice in there, so I assume that we are doing something wrong, but for the sake of god I can't find it :(

I also checked, that the mobx versions between example and our application match. 

Thanks for any help,
Philipp

**Comment by adamkleingit** [comment]
Can you try to reproduce in webpackbin?
Here is a starter bin with the tree component in latest version:
https://www.webpackbin.com/bins/-KqGwvVQLknZ-fTXHjCO

-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by pfeigl** [comment]
Wow, after almost two full days of debugging, I finally found the problem.
We were referencing mobx^3.1.8 in our packages.json, which led to 3.1.16 beeing installed.
angular-tree-component references a concrete version of mobx (3.1.11) which led to this version beeing installed in node_modules/angular-tree-component/node_modules/mobx/

This probably resulted in two mobx versions beeing installed into our project which in turn led to the described problem.

Is there any way how things like this can be avoided?

**Comment by adamkleingit** [comment]
Can you try referencing 3.1.11 in your app to solve your problem?

Ideally the tree would be more lenient with MobX versions, and MobX will
not introduce breaking changes in patches.
The problem is sometimes things break when advancing MobX patch versions
I'll see if putting ^3.1.11 in tree works or not.


-- 
- Adam Klein <http://il.linkedin.com/in/adamklein500>
- CTO @ 500Tech.com <http://500tech.com/>
- AngularJS, ReactJS, NodeJS
- Development, consulting, training and public speaking
- (+972) 52 747 5633

**Comment by pfeigl** [comment]
That's what I did and everything is working as expected now. Thanks for your help and the change you are going to apply. Possible saves someone else' time :)
