### ISSUE TITLE
example\cli project didn't run at IE11

### ISSUE THREAD

**Issue by Owenzh** [500tech/angular-tree-component#373]
Hi,

To allow for a faster response, please read carefully:

Please look for an answer in the docs before submitting an issue:
angular2-tree.readme.io.

In case you are reporting a bug, please reproduce it on webpack bin. You can start from here:
https://www.webpackbin.com/bins/-KqGwvVQLknZ-fTXHjCO
Open the left side menu and click copy
Make your changes
Click Save to view results
Share the URL once reproduced

If you are unable to reproduce on webpackbin, please:
- paste your package.json
- say which browser you are using
- paste your nodes and options and whatever code your feel will help reproduce the error

Thank you and happy programming

**Comment by adamkleingit** [comment]
Hi,
Demo works on IE11 on the docs site
