### ISSUE TITLE
clone node on drag-n-drop across trees

### ISSUE THREAD

**Issue by ronenzas** [500tech/angular-tree-component#377]
Hi there, is this an existing out of the box option?
If not can it be added?

Thanks!

**Comment by ronenzas** [comment]
Just in case the scenario is not clear:
When dragging a node from tree1 and dropping it in tree2, i want the node to be cloned, and not moved.

**Comment by adamkleingit** [comment]
Hi,
I will add copyNode soon so you can use it. Stay tuned
If you're in a hurry you can override actionMapping and supply a copy function of your own - refer to the docs.

**Comment by adamkleingit** [comment]
Hey,
will add a copyNode function, and a `getNodeClone` callback option in 4.1.0.
Please review the updates docs
