### ISSUE TITLE
Example1 Compile error/repair

### ISSUE THREAD

**Issue by TayBill** [500tech/angular-tree-component#378]
I found it necessary to add the focusedNodeId line (below) to get the example1 to compile.
'
export class DragComponent {
  state: ITreeState = {
    expandedNodeIds: {
      1: true,
      2: true
    },
    hiddenNodeIds: {},
    activeNodeIds: {},
   ** focusedNodeId: ''**
  };
'

**Comment by adamkleingit** [comment]
Hi, fixed in version 4.0.0
