### ISSUE TITLE
Change please misspelling in events.ts from "changeFilterr" to "changeFilter"

### ISSUE THREAD

**Issue by AlexanderIgorovych** [500tech/angular-tree-component#382]
Change please misspelling in events.ts from "changeFilterr" to "changeFilter" and release next npm version with this bug fix, my app depends on it. I have seen commit with this bug fix, but it was too late, I have done my commit (so please discard my changes ).

**Comment by AlexanderIgorovych** [comment]
#375 - quick fix for this issue

**Comment by adamkleingit** [comment]
Thanks, will be fixed in 4.1.0
