### ISSUE TITLE
https://angular2-tree.readme.io/docs   ui problems

### ISSUE THREAD

**Issue by AlexanderIgorovych** [500tech/angular-tree-component#383]
Fix this out put on the main page 
{"id":"5707c6875309d117006948d4","name":"angular-tree","subdomain":"angular2-tree","versions":[{"_id":"5707c6875309d117006948d7","releaseDate":"2016-04-08T14:56:07.571Z","is_deprecated":false,"is_hidden":false,"is_beta":false,"is_stable":false,"codename":"","version_clean":"1.0.0","version":"1.0"},{"_id":"578baf1ab935480e00956342","releaseDate":"2016-07-17T16:15:22.733Z","is_deprecated":false,"is_hidden":false,"is_beta":false,"is_stable":false,"codename":"","version_clean":"1.1.10","version":"1.1.10"},{"_id":"57a627f8e228650e008507c7","releaseDate":"2016-08-06T18:10:00.103Z","is_deprecated":false,"is_hidden":false,"is_beta":false,"is_stable":false,"codename":"","version_clean":"1.1.12","version":"1.1.12"},{"_id":"57aa4fc2971f1f0e00e5f20c","releaseDate":"2016-08-09T21:48:50.490Z","is_deprecated":false,"is_hidden":false,"is_beta":false,"is_stable":false,"codename":"","version_clean":"1.1.13","version":"1.1.13"},{"_id":"57b0d98e4430cf0e00277909","releaseDate":"2016-08-14T20:50:22.280Z","is_deprecated":false,"is_hidden":true,"is_beta":false,"is_stable":false,"codename":"","version_clean":"1.1.15","version":"1.1.15"},{"_id":"57c9c50a3a28560e00040898","releaseDate":"2016-09-02T18:29:30.985Z","is_deprecated":false,"is_hidden":false,"is_beta":false,"is_stable":false,"codename":"","version_clean":"1.1.16","version":"1.1.16"},{"_id":"57d54d43e2e70e20009cda14","releaseDate":"2016-09-11T12:25:39.237Z","is_deprecated":false,"is_hidden":false,"is_beta":false,"is_stable":false,"codename":"","version_clean":"1.1.18","version":"1.1.18"},{"_id":"57d92db93916800e003dde9a","releaseDate":"2016-09-14T11:00:09.656Z","is_deprecated":false,"is_hidden":false,"is_beta":false,"is_stable":false,"codename":"","version_clean":"1.2.0","version":"1.2.0"},{"_id":"57e6a11b6f38c50e002e85fe","releaseDate":"2016-09-24T15:51:55.072Z","is_deprecated":false,"is_hidden":false,"is_beta":false,"is_stable":false,"codename":"","version_clean":"1.2.2","version":"1.2.2"},{"_id":"57f3845f60ad2729006bd770","releaseDate":"2016-10-04T10:28:47.952Z","is_deprecated":false,"is_hidden":false,"is_beta":false,"is_stable":false,"codename":"","version_clean":"1.3.1","version":"1.3.1"},{"_id":"58022897a1b2621900de3528","releaseDate":"2016-10-15T13:01:11.826Z","is_deprecated":false,"is_hidden":false,"is_beta":false,"is_stable":false,"codename":"","version_clean":"1.3.3","version":"1.3.3"},{"_id":"583ae1d10ef9c019006797e4","releaseDate":"2016-11-27T13:38:25.471Z","is_deprecated":false,"is_hidden":false,"is_beta":false,"is_stable":false,"codename":"","version_clean":"2.0.0","version":"2.0.0"},{"_id":"583ae26d7cc610230075539c","releaseDate":"2016-11-27T13:41:01.185Z","is_deprecated":false,"is_hidden":false,"is_beta":false,"is_stable":false,"codename":"","version_clean"

**Comment by adamkleingit** [comment]
I'll write to readme.io it seems to be a bug on their website

**Comment by adamkleingit** [comment]
They fixed it
