### ISSUE TITLE
Can't resolve 'mobx'

### ISSUE THREAD

**Issue by adrian-mitangi** [500tech/angular-tree-component#385]
Hi,

I've just update the tree component to 4.1.0 from 3.5.0 and now I'm getting the following compilation error:

`ERROR in ./~/angular-tree-component/dist/models/tree-node.model.js
Module not found: Error: Can't resolve 'mobx'`

**Comment by adamkleingit** [comment]
are u using webpack or systemjs? can you paste your package.json / other config files? can u try removing node_modules and re-installing?

**Comment by Ekaanth** [comment]
Hello,
I tried to re-install and clear cache nothing worked, I'm still getting this ERROR 

` ERROR in ./~/angular-tree-component/dist/angular-tree-component.umd.js
Module not found: Error: Can't resolve 'mobx-angular' in 'D:\Workspace\KOCReports\node_modules\angular-tree-component\dist' `

**Comment by adamkleingit** [comment]
If it's umd.js I'm guessing you are using SystemJS which is not supported

**Comment by naresh2482** [comment]
Hi Friends,
I am new in MEAN stack, I am also getting same error
I am getting error on >ng serve  
ERROR: ERROR in Metadata version mismatch for module ./~/node_modules/mobx-angular/dist/mobx-angular.d.ts, 
found version 4, expected 3, resolving symbol TreeModule in ./~/node_modules/angular-tree-component/dist/angular-tree-component.d.ts, 
resolving symbol TreeModule in ./~/node_modules/angular-tree-component/dist/angular-tree-component.d.ts

Is there any workarround steps for this issue.

I really appreciate any help you can provide.
