### ISSUE TITLE
Drag and drop implementation prevents custom data on dataTransfer object

### ISSUE THREAD

**Issue by Gragx** [500tech/angular-tree-component#386]
Hello there

I am trying to make drag and drop work entirely with the HTML5 drag and drop API. Meaning that I don't store the dragged node in a variable on the current webpage (this libraries default implementation), but in the drag events DataTransfer object. The goal is to use drag and drop across tabs/windows or even browsers (btw. it would be lovely to have that as the default implementation).

To do this, I created custom dragStart and drop handlers. 
The issue is, that I need to store my data as 'text' for things to work in Internet Explorer:
```javascript
event.dataTransfer.setData('text', JSON.stringify(someData));
```

If I use this libraries dragStart option to create my custom handler, I am not able to store any data in the event i'm getting. 
Am not entirely sure why. I checked the compiled javascript of the tree-drag-directive and there is a timeout before any custom handlers are being called, without that it would work
```javascript
setTimeout(function () { //remove this timeout and the event can actually be used to store data
    _this.treeDraggedElement.set(_this.draggedElement);
    if (_this.draggedElement.mouseAction) {
        _this.draggedElement.mouseAction('dragStart', ev);
    }
}, 30);
```

So I went ahead and created my dragStart handler outside of angular-tree on my tree-node template.
This does not work either, because the tree-drag-directive's dragStart function is still being called, after my handler, meaning your fix for Firefox with an empty string in the dataTransfer object overwrites my own data.

I see two possible solutions:
- Make it so the event passed on to the actionMapping, dragStart  handler can be worked with
- Only apply your "Firefox fix", if there is no data present already

**Comment by Gragx** [comment]
I just realized, that there was an update to the tree-drag-directive some weeks ago and I am still using an older version. Will make an update ASAP. and see if the issue still exists

**Comment by adamkleingit** [comment]
@Gragx did it solve it?

**Comment by Gragx** [comment]
It did, I am now able to manipulate the dataTransfer object in my custom dragStart function.
