### ISSUE TITLE
How to hide the scrollbar

### ISSUE THREAD

**Issue by l2radamanthys** [500tech/angular-tree-component#388]
I need to hide the scroll bar to display the full tree but I can not find out how to override styles for tree-viewport.

**Comment by sa1509** [comment]
Facing exactly the same issue. I also want to override the tree-viewport styles. Hope it is resolved soon.

**Comment by ScottSpittle** [comment]
The code below (SASS), uses full height and applies a horizontal scrollbar removing th eword breaks
```
tree-viewport {
  display: grid !important;
  overflow-y: hidden !important;

  & div:first-child {
    & div:first-child {
      height: 100% !important;
      word-wrap: break-word !important;
      white-space: nowrap !important;
    }
  }
}
```
