### ISSUE TITLE
Dynamically replace node causes all children to collapse even with isExpanded=true

### ISSUE THREAD

**Issue by ScottSpittle** [500tech/angular-tree-component#391]
Hi,

I have a button of which when clicked it will replace the clicked node with a new tree of nodes.

I then call `this.tree.treeModel.update();` which displays the new node, but it's children are all collapsed even though their isExpanded properties are true.

The keyboard shortcuts also appear to stop working as it prevents me from using the arrow keys to navigate the nodes after a dynamic replacement of a node

**Comment by nofear87** [comment]
+1

**Comment by MintL** [comment]
+1
I came up with this webpackbin to show the issue:
https://www.webpackbin.com/bins/-KsO9OPGvTO5rcQIghlS

**Comment by adamkleingit** [comment]
Hi,
`isExpanded` will some day be deprecated. Please bind to `state` or call `setState` instead, and set the expandedNodeIds.
