### ISSUE TITLE
How to hide loading for async children in exception?

### ISSUE THREAD

**Issue by eastjie** [500tech/angular-tree-component#392]
Hi,

I'm using version 4.0.0 and have a question about the loading progress for async "getChildren" calling.  I have called Web API and return an Observable and convert the Observable to Promise. It works well til exception happens. 

I have handled data in exception but the loading progress will never disappear. How can this problem be solved?

Thanks very much.

**Comment by adamkleingit** [comment]
Hi,
If you want the node to collapse you collapse it with 2 options:
- bind to tree state https://angular2-tree.readme.io/v6.1.0/docs/save-restore
- call `getNodeById(...).collapse()`

If you just want the node to have no children you can set the original node's children to an empty array (or add a special node that will output an error)

Hope this helps
