### ISSUE TITLE
setActiveAndVisible not in help, or in typings

### ISSUE THREAD

**Issue by TayBill** [500tech/angular-tree-component#394]
Hmm, I'm a newbie for this control, and am walking through the example code.
I noted that the example code used the node.setActiveAndVisible method, yet this method is not defined in help, or in the typings (intellisense doesn't work).  
Is is just left out of the help/typings, or am I missing something more fundamental.

**Comment by moniuch** [comment]
This is true, I noticed this method only when reading throught the example on the TreeModel page: https://angular2-tree.readme.io/docs/treemodel - but it is not listed in API.

**Comment by adamkleingit** [comment]
Fixed, will update soon in the docs
