### ISSUE TITLE
Node text is cut when exceed its container width

### ISSUE THREAD

**Issue by XtheWiz** [500tech/angular-tree-component#396]
Hi, I found a problem that if I have tree with deep level place in specific width container.
For example, div container has 150px width, and 5 level tree inside there. When I expand to deeper level, the text of that node is cut.

I already tried with overflow: auto, virtual scroll and perfect scrollbar but all of them are not work.

**Comment by XtheWiz** [comment]
I solve this issue by using div to wrap tree-root element and give them css white-space value to nowrap.

**Comment by DanielCaspers** [comment]
Should this issue be closed then? CSS either on the individual nodes or across the whole tree itself seems like a reasonable way to handle that problem.

**Comment by XtheWiz** [comment]
Yes, please close this issue.

**Comment by arvriv** [comment]
I have those a problem too
did you found an ansower for this qoistion?
it can help me to know how it possible to do it
thanks

**Comment by arvriv** [comment]
please i wait for your answer 
it's very important for me 
i can't continue without your answer
thanks
