### ISSUE TITLE
Styling help

### ISSUE THREAD

**Issue by Ponnda** [500tech/angular-tree-component#398]
Hi,

I cannot seem to figure out how to change the styling correctly on the tree component. Using one of the style examples seems to do nothing for me. More so than the styling could I please ask you to give me a detailed example how to change the icon for expanding the nodes.

Thank you!

**Comment by sa1509** [comment]
I faced similar issue. Don't know if this is a good solution but I ended up adding the following in my custom css:

.toggle-children-wrapper-collapsed .toggle-children {
    background-image: url(assets/images/expand.png) !important;
}

.toggle-children-wrapper-expanded .toggle-children {
    transform:rotate(0deg)!important;
    background-image: url(assets/images/collpase.png) !important;
}

The  background-image url is set to the icons I want for expanded and collapsed nodes. Hope it helps.

**Comment by kripton69** [comment]
Hi, I have a problem with puts explorer like branch lines that connect the parents with their children...
[https://ibb.co/jV2wGb](url)
