### ISSUE TITLE
TypeError: JSON.stringify cannot serialize cyclic structures.

### ISSUE THREAD

**Issue by ramuda** [500tech/angular-tree-component#399]
I have implemented the tree component .
Version implemented is 4.1.0 
Template `<tree-root
    #leftListRef
    tabindex="0"
    [nodes]="leftList"
    [focused]="focusedLeftTree"
    [options]="options"
    (moveNode)="onNodeMoved($event)"
    (activate)="onActivateLeft($event)"
    (deactivate)="onDeactivateLeft($event)"
    (focus)="onFocusLeft()"
    (blur)="onBlurLeft()">
  </tree-root>`
When I want to test some operations like activate I get an error 
PhantomJS 2.1.1 (Windows 7 0.0.0)  check the activate and deactivate emits FAILED
	TypeError: JSON.stringify cannot serialize cyclic structures.
I am using jasmine2.0 on karma. It runs fine on chrome but fails in phantomJS

Test code snippet `fixture = TestBed.createComponent(PickListTestControllerComponent);
    fixture.detectChanges();
fixture.debugElement.nativeElement.querySelectorAll('.node-content-wrapper')[0].click();
    expect(component.moveUpDisabled).toBe(true);
    expect(component.moveDownDisabled).toBe(true);
    expect(component.moveLeftDisabled).toBe(true);
    expect(component.moveRightDisabled).toBe(false);`

**Comment by adamkleingit** [comment]
Hi,
I'm not using stringify anywhere in the library.
Can you print out where the exception happens? (which file / method / line)
