### ISSUE TITLE
Example on disabling certain items functionally and visually

### ISSUE THREAD

**Issue by moniuch** [500tech/angular-tree-component#400]
I would gladly welcome an example of the best way to disable selecting of certain folder nodes - both functionally and visually.

Also, maybe there is an api way, or plans to have one, to disable certain items with just a single call. I need to provide an interface state for a case when user wants to move a folder into another folder. When I present the folder tree to select the target folder, I need to disable certain nodes from being selected - namely: the folder to be moved (itself), its parent and all of its descendants - so maybe there should be a call available like `treeModel.disableParentSelfAndChildren(startingFolderId)`.

I tried to use state object for that (specifically: activeNodeIds- flagging an item with `false`) but it would not prevent me from selecting an inactive node.

**Comment by arundhaj** [comment]
Why was this feature request closed?

A property `isDisabled` in `TreeNode` class would be helpful, so that it can be used as follows:

```
<input
        class="tree-node-checkbox"
        type="checkbox"
        (click)="node.mouseAction('checkboxClick', $event)"
        [disabled]="node.isDisabled"
        [checked]="node.isSelected"
        [indeterminate]="node.isPartiallySelected"/>
```

**Comment by itsmekhanh** [comment]
I am also interested in this feature too. Will it be in a future release?

**Comment by LukeHartcher** [comment]
+1

**Comment by jamiehankins** [comment]
+1 piling on. I need this functionality now. I guess I'll have to figure a way to hack it.

**Comment by emceearjun** [comment]
+1

**Comment by d4rkc0de** [comment]
+1

**Comment by TheoLechemia** [comment]
+1

**Comment by akshaygolash** [comment]
+1

**Comment by DefKorns** [comment]
+1
