### ISSUE TITLE
expanding nodes when new data arrive from ngrx store.

### ISSUE THREAD

**Issue by TMaster** [500tech/angular-tree-component#402]
Hi.

I'm using the tree component inside my application which built with redux.
My tree structure is exists in the store's state, and the tree nodes' property is bound to the state.

In my flow every time a node is expanded for the first time an action is sent to load the node's children.
After results are sent from the server. I change the tree state in a command and therefore changes the **nodes** property.
In addition I change the expanded field of the parent.

When I'm expanding the parent (for the first time) something strange happens: 
- The parent node is expanded.
- The children nodes are added to the tree (therefore the tree gets updated).
- The parent node is collapsed.

When the parent is collapsed, if I tried to re expand it, it works fine.
I checked the tree state that comes from the store and it seems fine.

What bothers me is that as I understand it, the **isExpanded** field should tell the tree if the node should be expand in the beginning, this is also what I saw [in the example  ](https://github.com/500tech/angular-tree-component/blob/9c62a8a6d9f1e43dc452080dc846893b841349cc/example/cli2/src/app/fulltree/fulltree.component.ts#L218), but unfortunately it doesn't seems to work.

Another strange thing, the root node is expanded with no problem, the problems start when I'm trying to expand nodes from second level.

Do I need to do something special when I work with the tree in redux?
Why the parent node is collapsing ? :sob: 

Thanks a lot,
TMaster

**Comment by adamkleingit** [comment]
Hi, instead of using `isExpanded` field, you have 2 options:
- bind to the tree state: https://angular2-tree.readme.io/v6.1.0/docs/save-restore
- call `getNodeById(...).expand()`

Hope this helps
