### ISSUE TITLE
Lost data changes in nodes  after tree update

### ISSUE THREAD

**Issue by koryan** [500tech/angular-tree-component#403]
Hi, new to this component
I use this.treeComponent.treeModel.getActiveNode().data = myDataObject to change nodes in tree.
myDataObject has prop "name" and i see that name in tree is correctly changing

Then in another node i push childs using this.treeComponent.treeModel.getActiveNode().data.children.push(childsArr)

But when i use this.treeComponent.treeModel.update() after pushing i see new childs, but loose all previous node changes
What i'm doing wrong?

**Comment by adamkleingit** [comment]
Hi,
You shouldn't change the data reference of the TreeNode.
Better do Object.assign, or change the original [nodes] input that was given to the tree
