### ISSUE TITLE
Filtering don't work properly with async loaded nodes

### ISSUE THREAD

**Issue by Bulczi** [500tech/angular-tree-component#404]
Hello :),

When filtering the tree with async nodes loading, I believe the filtering is not working properly. The filtering logic is not being applied on the recently loaded nodes - the tree needs to be refiltered manually.

The issue can be reproduced on the demo tree from the https://angular2-tree.readme.io/docs website. Steps to reproduce:
1. Type in the filter input textbox _root_ - the nodes with no root word are filtered out properly
2. Expand _asyncroot_ node - **the loaded subnodes will not be filtered according to the filter**
3. Remove last letter in the filter input textbox - the filter will be reapplied and the asyncly loaded subnodes will be filtered out as they don't mach the _root_ filter.

Kind regards,
Bulczi.

**Comment by adamkleingit** [comment]
Hi,
When using async data, usually it makes more sense to do the filtering server-side (because not all nodes are loaded).
I think this use-case is not necessarily the desired behaviour in all cases. You can always call filter after you get an event for loaded children so I prefer to leave it as is
