### ISSUE TITLE
node.isExpanded state might not be correct just after firing treeModel.collapseAll()

### ISSUE THREAD

**Issue by johnking** [500tech/angular-tree-component#414]
Hi @adamkleingit ,

I found this issue with following steps:

Step 1. Make sure all the tree nodes expanded
Step 2. In a component method
  1.  call treeModel.collapseAll() to collapse all the nodes
   2. for a certain node path, which is more than 2 level deeper, check the node state, I found the node state in the first two levels are correct, but those in deeper levels will still be in `expanded` state.

code snippet:
 
```javascript
      tree.treeModel.collapseAll();

      focusedNode.path.forEach( (id) => {
        let node = tree.treeModel.getNodeById(id);
        if (node) {
          console.log(node.isExpanded);
          node.expand();
        } else {
          console.log("no node found!");
        }
```

My dev environment: 
```
@angular/cli: 1.3.2
node: 6.10.2
os: darwin x64
@angular/animations: 4.3.6
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.6
@angular/compiler: 4.3.6
@angular/core: 4.3.6
@angular/forms: 4.3.6

@angular/http: 4.3.6
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.6
@angular/platform-browser-dynamic: 4.3.6
@angular/router: 4.3.6
@angular/cli: 1.3.2
@angular/compiler-cli: 4.3.6
@angular/language-service: 4.3.6
```
and I am using Chrome.

**Comment by johnking** [comment]
My temporary solution is: 
```javascript
      setTimeout(()=> node.expand(), 100);
```

**Comment by adamkleingit** [comment]
Hi,
I couldn't reproduce. Can you reproduce here and reopen:
https://plnkr.co/edit/u5fMmaM14rJ0aqG3k240?p=preview
