### ISSUE TITLE
Styles do not have to be imported

### ISSUE THREAD

**Issue by IncognitoCore** [500tech/angular-tree-component#416]
The readme on https://angular2-tree.readme.io/docs/getting-started states that styles have to be imported, but this is not the case (they are automatically applied and the .css file doesn't even exist).

_Using the node package. Installed as described in the guide mentioned above._

**Comment by chriso86** [comment]
+1

**Comment by adamkleingit** [comment]
Sorry, there was a mixup with versions.
In version 5.0 (just released) - you have to include the external CSS (there were a lot of complaints about not being able to override styles so we made it a separate CSS)
