### ISSUE TITLE
Which version to install (npm vs github releases)?

### ISSUE THREAD

**Issue by sulhome** [500tech/angular-tree-component#418]
On npm the current published version is 3.1.0
On the releases tab in github the current version is 5.0.0

Which one to use? also how do we know what is a beta/alpha or final release?

**Update: 11/09/2017**
So version 3.1.0 is on this link: [https://www.npmjs.com/angular2-tree-component](https://www.npmjs.com/angular2-tree-component)
Version 5.0.0 is published on npm but under this location [https://www.npmjs.com/package/angular-tree-component](https://www.npmjs.com/package/angular-tree-component)

so obviously https://www.npmjs.com/package/angular2-tree-component is outdated and should have its README file updated to point to the new one.

Thank you

**Comment by mgroetan** [comment]
Some info about the breaking changes in 5.0.0 wrt external CSS handling would also be appreciated.

**Comment by adamkleingit** [comment]
Hi,
please use version 5.0.0
changes and breaking changes are listed in CHANGELOG.md
I also updated the docs website to be default on 5.0.0 (was 4.1.0 by mistake)
All the best
