### ISSUE TITLE
TreeModel.isEmpty returns undefined for undefined nodes

### ISSUE THREAD

**Issue by jakub-stejskal** [500tech/angular-tree-component#421]
When `[nodes]` are `undefined`, `TreeModel.isEmpty` returns `undefined` (a falsy value) instead of expected `true`.

See https://www.webpackbin.com/bins/-KtQivR_4pm2PVCyLVmJ

Current implementation:
```
  isEmptyTree(): boolean {
    return this.roots && this.roots.length === 0;
  }
```
This should fix it:
```
  isEmptyTree(): boolean {
    return _.isEmpty(this.roots);
  }
```

**Comment by adamkleingit** [comment]
Hi,
Current implementation of `isEmptyTree` needs to return true only if there is an empty node array, not for undefined (this is used for dragging into an empty tree).
