### ISSUE TITLE
special characters are not displaying. kindly help.

### ISSUE THREAD

**Issue by senthilpap** [500tech/angular-tree-component#422]
When we input data to tree, special characters like &^%$#@*()!~ are not displayed.

**Comment by radben13** [comment]
Could you include a code example or more details? What specifically are you trying to do when you say "we input data to tree"?

**Comment by adamkleingit** [comment]
Please reproduce here and reopen the issue:
https://plnkr.co/edit/u5fMmaM14rJ0aqG3k240?p=preview
