### ISSUE TITLE
How to override styling?

### ISSUE THREAD

**Issue by mgroetan** [500tech/angular-tree-component#423]
I need to override some CSS, to get a BsDropdownModule to show correctly.

I've found that I need to override the ".tree-children" class, and I've read this page: https://angular2-tree.readme.io/docs/styling#overriding-style

I'm not a CSS wiz, so I don't understand this:
> Surround your tree with a class, and add your custom style to your style.scss file.
Scope all the custom rules under your custom class - and that's it!

I'm using Angular 4(.3.6) and building with Angular CLI (1.4.0).
Wherever I place my CSS, it ends up being rendered BEFORE the CSS from the tree component, effectively being overridden.

**Comment by mgroetan** [comment]
If I just dump a simple "override" style block inside the "body" tag, it works in non-IE/Edge browsers. Ugly, but OK.
Not a perfect solution, though, as IE doesn't respect the order of styles, it seems. Dev tools lists my override last, but still gets overridden itself. Could this be due to the execution model in IE, when other CSS from the dropdown component is injected into the "head" element at runtime? Maybe the last one added "wins"?
So eagerly awaiting a more proper fix.

**Comment by mgroetan** [comment]
Found the answer myself. Sorry about the lack of basic CSS understanding.

Just added a new class for the surrounding div and then scoped the overridden class beneath that, like this (in my component's "styles.css" file):
```
/* Custom class that surrounds the tree view */
.treeview {
    height: 800px;
}

    /* Scope the overridden class inside the custom class, to avoid it being overridden by injected component styles */
    .treeview .tree-children {
        overflow: inherit; /* Was "hidden", but made the dropdown hide behind the bottom of the node's tree branch */
    }
```
That way, the CSS ends up in the "head" tag. Although above the injected CSS from the tree component, the scoping makes sure it works as intended.

**Comment by aldrindizonh** [comment]
how to overide the syle of node-content-wrapper? i want it to width 100%.

.node-content-wrapper    {
  width: 100% !important ;
}

try ^ in my code is not working. help :(

**Comment by NiceStepUp** [comment]
mgroetan, could you help me to override my tree?  I have a plunker : http://plnkr.co/edit/azLsD1?p=preview

So the guide says:

> Surround your tree with a class, and add your custom style to your style.scss file.
> Scope all the custom rules under your custom class - and that's it!

So I've created .ace style (_Surround your tree with a class_ like guide says):

    `.ace { }`

Then I put all elements of style **ACE Admin theme** inside of ".ace" class (_Scope all the custom rules under your custom_ class like guide says):

```
.ace div.tree {
     padding-left: 0;
     margin-left: -5px
}
```
...
and my tree:

 ```
<tree-root 
  [ngClass]="'ace'"
  [nodes]="nodes"
  [options]="options"
></tree-root>
```

I think it should be really simple, however I cannot apply the Ace Admin Style. Sorry about that I cannot figure out how to override style.

**Comment by ulisesmorenomassachusetts** [comment]
Is the FullTemplate option the required step to accomplish this?

**Comment by reenezden** [comment]
@NiceStepUp , were you able to get the styling working? If yes, can you please share?

**Comment by NiceStepUp** [comment]
> @NiceStepUp , were you able to get the styling working? If yes, can you please share?

@reenezden  yeah, I've posted an answer. Please, see here

https://stackoverflow.com/questions/49161721/how-to-properly-override-style-of-angular-tree
