### ISSUE TITLE
Feature Request: save current expanded tree as a json object. 

### ISSUE THREAD

**Issue by johnking** [500tech/angular-tree-component#424]
Hi, @adamkleingit 

   Sometimes, we need to select and process a subset of large tree nodes. We may select the nodes either visually or done by APIs calls. But it will be nice to save the snapshot as a json object so that it could be further processed in other Angular components or methods.

thanks

-John

**Comment by johnking** [comment]
One more use case: 

  After users create the tree visually, they can get the JSON data by saving current tree into a file.

**Comment by adamkleingit** [comment]
Hi,
noted.

In the meanwhile you can bind to (stateChange) event and calculate the JSON however you like.
