### ISSUE TITLE
angular-tree-component

### ISSUE THREAD

**Issue by huangyangyang-yangyang** [500tech/angular-tree-component#425]
angular-tree-component not support fireFox?

**Comment by huangyangyang-yangyang** [comment]
angular-tree-component not support fireFox?

**Comment by mgroetan** [comment]
Works fine for me ;-)

**Comment by huangyangyang-yangyang** [comment]
angular-tree-component support fireFox,is style reason!new successfully,thanks.

**Comment by Sharad777** [comment]
In Firefox styles are not coming proper.

**Comment by adamkleingit** [comment]
Looks good to me.
Can you paste screenshot and reopen?
