### ISSUE TITLE
sizeChanged() method removed?

### ISSUE THREAD

**Issue by stogle** [500tech/angular-tree-component#428]
The `TreeComponent.sizeChanged()` method was recently removed by https://github.com/500tech/angular-tree-component/commit/f86c58366bc8f12af956fa2d7bf346a07e873557.

The [docs](https://angular2-tree.readme.io/docs/large-trees) say I need to call this method when a hidden tree with virtual scroll becomes visible. Is this no longer the case?

**Comment by velimirp** [comment]
I have the same problem. The tree is hidden and looks weird when made visible but i can't call the sizeChanged() method since it's no longer present.

**Comment by HATyCEHKA** [comment]
I have the same problem, but I found solution:
`this.tree.treeModel.virtualScroll.setViewport(this.tree.treeModel.virtualScroll.viewport);`

**Comment by stogle** [comment]
@adamkleingit could you explain why TreeComponent.sizeChanged() was removed? It's still mentioned in the docs [here](https://angular2-tree.readme.io/docs/large-trees) and [here](https://angular2-tree.readme.io/docs/common-issues).

**Comment by RonnyRen** [comment]
this.tree.treeModel.virtualScroll.setViewport(this.tree.treeModel.virtualScroll.viewport); 
It cannot work. Is there any workaround?

**Comment by adamkleingit** [comment]
I must have deleted it by mistake when doing some cleanup.
Will be returned in 6.0.0

**Comment by adamkleingit** [comment]
Published in 6.0.0

**Comment by anhvupham** [comment]
Looks like it's still an issue in 7.0.1
