### ISSUE TITLE
calling expandAll() in the initialized event leads to an error

### ISSUE THREAD

**Issue by Gerros** [500tech/angular-tree-component#430]
Hi, 
when calling the following command in the initialized event I get an error:

this.treeComponent.treeModel.expandAll();

ERROR TypeError: Cannot read property 'forEach' of undefined
    at TreeModel.webpackJsonp.../../../../angular-tree-component/dist/models/tree.model.js.TreeModel.expandAll (tree.model.js:248)
    at executeAction (mobx.js:854)
    at TreeModel.res (mobx.js:845)
   

The error is because the treeModel.root property is undefined at that moment... anybody else encountered that problem? 
In the documentation of the initialized event it says that this is the event which can be used for expanding the nodes... so at the moment as far as I see this, this is a bug.

**Comment by AbhiThakare** [comment]
@Gerros 

Can you try like below

```javascript
  onInitialized(tree) {
     tree.treeModel.expandAll();
  }
```

```html
<tree-root   #tree
      [nodes]="nodes"
      [options]="customTemplateStringOptions"
      (onInitialized)="onInitialized(tree)">
      <ng-template #treeNodeTemplate let-node>
        <span title="{{node.data.subTitle}}">{{ node.data.name }}</span>
        <span class="pull-right">{{ childrenCount(node) }}</span>
      </ng-template>
      <ng-template #loadingTemplate>Loading, please hold....</ng-template>
 </tree-root>
```

hope this will help,
Please share the output 

Cheers 
Abhi.

**Comment by Gerros** [comment]
I tried it out with a version where I still had this error and unfortunately this did not help. Still the treeModel.root is undefined. But in the meantime I do not get this error anymore.
The difference to the version where I get the error is that I got rid of some setTimeout calls. These setTimeout calls I have as workaround due to some "detected change after change detection exception". Maybe those setTimeouts were the reason which lead to this error... can not say for sure.

Thanks @AbhiThakare !!

**Comment by shigi** [comment]
I faced the same error.
It works fine on version < 3.7.0.
I guess the the cause may be that timing of firing initialized event changed.

**Comment by adamkleingit** [comment]
It works with latest version:
https://plnkr.co/edit/9TrH4W42S0sWFUCyGwYF?p=preview

**Comment by thienedits** [comment]
@AbhiThakare Hi I have tried this and the nodes do not expand. There is no errors.

**Comment by erickyi2006** [comment]
@thienedits , I also found this using the latest version.  Is your nodes data static or dynamic? If dynamic, then I know the solution.

btw. the ngOnInit() is incorrect, should do the initialization in ngAfterViewInit().

**Comment by oscarlagatta** [comment]
Hi, has this issue been solved ? 
Thanks

**Comment by NiranjanAbb** [comment]
I have same issue. My data is combination of static and dynamic. Can someone help me to fix this?

**Comment by thienedits** [comment]
I am on version 7.0.1 and doing in ngAfterViewInit seems to work for me

```
ngAfterViewInit() {
        if(this.tree && this.tree.treeModel) {
            this.tree.treeModel.expandAll();
        }
    }
```
