### ISSUE TITLE
Latest release doesn't draw node expander

### ISSUE THREAD

**Issue by mmallit** [500tech/angular-tree-component#437]
Hello,

Using the latest release(5.0.0) fixed issues I was hitting in 4.1.0 where I could not dynamically add nodes to the tree following the documentation for it. After the update call, the tree would no longer expand and nodes wouldn't be added. HOWEVER, now in 5.0.0, the first render doesn't show the node expander. I was able to repro with webpackbin here: https://www.webpackbin.com/bins/-KuUsyJeerxKIYtC6VwE

Any help appreciated.

Thanks,
Mike

**Comment by AbhiThakare** [comment]
@mmallit 

Agree!

You can add css manually to your style.css file.

```css
@import '~angular-tree-component/dist/angular-tree-component.css'; 
```

Let me know output

Cheers
Abhi.

**Comment by kevinpirola** [comment]
same result to me, and the import of the CSS is not working.

**Comment by suspended** [comment]
The CSS styles and event handlers for these are missing. A workaround is to either downgrade to 4.1.0 or write the event handlers yourself.

**Comment by AbhiThakare** [comment]
@kevinpirola 

Works fine for me without removing tilde ~ and it compiled too.

```javascript
@import '~angular-tree-component/dist/angular-tree-component.css'; 
```

**Comment by adamkleingit** [comment]
Updated docs with the import statement.
@kevinpirola - are you doing the import in `styles.scss`? Are you using angular-cli?
