### ISSUE TITLE
AOT build issue with version 5.0.0

### ISSUE THREAD

**Issue by ghodum** [500tech/angular-tree-component#439]
I am trying to do an AOT build with version 5.0.0 and I am hitting the following error:

Error in bail mode: [at-loader] src\compiled\node_modules\angular-tree-component\dist\components\tree-viewport.component.ngfactory.ts:50:35
    TS2554: Expected 0 arguments, but got 1.

It appears that the onScroll() event handler method in TreeViewportComponent is missing a parameter (the event) and this may be causing the issue.

I do not get this error when using the previous version 4.1.0.

Thanks,
Greg

**Comment by adamkleingit** [comment]
Waiting for 5.0.0 to be released

**Comment by jcjolley** [comment]
I too am experiencing this issue.

**Comment by adamkleingit** [comment]
Hi - fixed in 5.2.0
