### ISSUE TITLE
Guys you should really say that the css files need to be included in the project. Because it is not mentioned in the docs and as a newbie i lost one hour on this issue

### ISSUE THREAD

**Issue by panospost** [500tech/angular-tree-component#440]
Hi,

To allow for a faster response, please read carefully:

Please look for an answer in the docs before submitting an issue:
angular2-tree.readme.io.

In case you are reporting a bug, please reproduce it on webpack bin. You can start from here:
https://www.webpackbin.com/bins/-KqGwvVQLknZ-fTXHjCO
Open the left side menu and click copy
Make your changes
Click Save to view results
Share the URL once reproduced

If you are unable to reproduce on webpackbin, please:
- paste your package.json
- say which browser you are using
- paste your nodes and options and whatever code your feel will help reproduce the error

Thank you and happy programming

**Comment by atlantageek** [comment]
So what did you include.  My tree is only showing the roots. This may be my issue.

**Comment by adamkleingit** [comment]
Sorry guys, the readme website showed the docs for version 4.1 by default, whereas npm default version is 5.0.0.
Fixed
