### ISSUE TITLE
A way to control copy node

### ISSUE THREAD

**Issue by tobiasbrenner** [500tech/angular-tree-component#441]
When pressing ctrl while dragging the node, the node is copied into the tree and not moved. There is no way to prevent this  if you want to disable node copy in general.

It would be nice to have a TreeOptions boolean flag to disable a node copy completely or have a allowCopy function like for allowDrag.

Best regards,
Tobias

**Comment by adamkleingit** [comment]
Hi,
you can do this with:
```
options.actionMapping.mouse.drop =
(tree: TreeModel, node: TreeNode, $event: any, {from , to}: {from: any, to: any}) => tree.moveNode(from, to)
