### ISSUE TITLE
ngModel Update tree nodes

### ISSUE THREAD

**Issue by abelkbil** [500tech/angular-tree-component#442]
Hi,

How you are handling model update using ngModel or Form. What is the right approach?, I have an input text and and a multi select box value on each node. 

I thought of ng model It didnt work.
```
<tree-root
          #tree [nodes]="nodes" [options]="options" >
          <ng-template #treeNodeTemplate let-node let-index="index">
            <app-context [(ngModel)]="node.data.name" name="name{{node.data.id}}" [node]="node.data" ></app-context>
          </ng-template>
        </tree-root>
```
And on submit button I tried to access the node json object variable, But new nodes created and edits happened are not reflecting.

```
  addNew() {
    this.nodes.push({
      id: 0,
      name: 'new node',
      type: 'usecase',
      children: []
    });
    this.tree.treeModel.update();
  }

  saveTree(){
    console.log(this.tree.treeModel);
  }
```
Any previous links or any doc reference will be helpful

Thank you

**Comment by jlouiss** [comment]
You could try binding an update on the input change event, like this
```html
<app-context ... (change)="tree.treeModel.update()" ...>
```

**Comment by adamkleingit** [comment]
It should work with ngModel. Maybe the problem is with app-context component.
Can you try with a regular input?
