### ISSUE TITLE
Using TreeModel and TreeNode in angular2 component, not able to test the tree using unit testing in angular2

### ISSUE THREAD

**Issue by sudhakar-sekar** [500tech/angular-tree-component#447]
Hi,

 I am using angular2-tree-component v2.6.1 npm package for the tree structure in angular2 project.
 In development environment, I am able to access all the functions inside the package. But, when I am trying to test the tree, I am not able to access any functions inside the package. 
I am using karma and jasmine for angular2 unit testing.
For example,
**this.tree.getVisibleRoots()** - it's working in development environment, but not in testing environment.
If i'm trying to test the method, got an issue like below,
**TypeError: tree.getVisibleRoots is not a function() is not a function**.

Is it possible to test the tree structure using karma and jasmine in angular2 unit testing.

After upgrading npm  angular2-tree-component package from v2.6.1 to v3.1.0, the tree is not displaying in UI.
In v2.6.1, the tree working correctly, not in v3.1.0.
Anyone help me to test the tree structure in angular2.

Thanks in advance....

**Comment by adamkleingit** [comment]
there shouldn't be any difference.
Maybe you didn't include the tree module in the testbed?
