### ISSUE TITLE
Upgrading angular2-tree-component from v2.6.1 to v2.3.0, after upgrading the version the tree is not displayed

### ISSUE THREAD

**Issue by sudhakar-sekar** [500tech/angular-tree-component#448]
Hi,

 I am using angular2-tree-component, to display the tree. I am displayed two trees one is LHS and another one is RHS.
 Before upgrading to v3.1.0, both trees are displayed and able to extract and collapse.
 But, after upgrading to v3.1.0 from v2.6.1, RHS tree will be displayed and the LHS tree is not displayed.
 I am using #treeNodeTemplate to display the tree.

Here is the HTML code,

                    <tree-root #tree [nodes]="LHSNodes" [focused]="true" [options]="optionsForLHS" (onInitialized)="getTree(tree.treeModel)">
                        <template #treeNodeTemplate let-node>
                            <span>{{ node.data.name}}</span>
                        </template>
                    </tree-root>
can anyone help me to resolve these issue...

Thanks is advance.......

**Comment by adamkleingit** [comment]
Hi,
please see breaking changes list in CHANGELOG.md
