### ISSUE TITLE
Trigger click event on treenode

### ISSUE THREAD

**Issue by crivadavi** [500tech/angular-tree-component#450]
Hi, 
after initialize the tree in my component I want to select a determinate treenode with an Id and trigger the click event. This is what I have:

```
ngOnInit() {
    setTimeout(() => {
      let nodeToShowFirst = this.tree.treeModel.getNodeById('evAt');
      let event = new MouseEvent('click');
      if(nodeToShowFirst !== undefined){
        nodeToShowFirst.elementRef.nativeElement.dispatchEvent(event);
      }
    }, 0);
  }
```

but I receve the Error: "Element Ref is no longer supported since introducing virtual scroll
      You may use a template to obtain a reference to the element"

It happen because of the call to elementRef() on the ITreeNode,
but if the list of treenodes is generated dinamically I can't use ViewChild. So, how can I obtain the elementRef to the node and dispatch click event?

**Comment by adamkleingit** [comment]
Hi,
you can use the API to find the node and select it:
`treeModel.getNodeById(id).setIsActive(true)`
