### ISSUE TITLE
passing a custom template through wrapper component

### ISSUE THREAD

**Issue by itzik25b** [500tech/angular-tree-component#453]
Hi,
I have a wrapper component which contains the angular-tree-component, I want to pass a template to my wrapper component then it should pass it to the angular-tree-component.

**external HTML** 
```
<tree-wrapper [nodes]="tree.nodes">
  <div>I wanna be a template for each node</div>
</tree-wrapper>
```

**tree wrapper**
```
<tree-root [nodes]="nodes" [options]="treeOptions">
    <ng-template #treeNodeTemplate let-node="node" let-index="index">
      <ng-content></ng-content>
    </ng-template>
</tree-root>
```

the code above results in showing the passed content only once instead of showing it for each node (i verified i have more than one nodes)

is it possible to do it in another way?

**Comment by jlouiss** [comment]
Try with this :)
```html
<!-- external component template -->
<tree-wrapper [nodes]="tree.nodes">

  <ng-template #treeNodeTemplate let-node let-index="index">
    <!-- template goes here -->
    <span>{{ node.data }}</span>
  </ng-template>

</tree-wrapper>

------

<!-- tree wrapper template -->
<tree-root [nodes]="nodes">
  <ng-content></ng-content>
</tree-root>
```

**Comment by itzik25b** [comment]
Unfortunately it doesn't work for me, while checking the DOM I see the model but no template is being renderd

![image 16](https://user-images.githubusercontent.com/16287085/31770581-4ea1c098-b4e1-11e7-9377-64ec37b5ef5b.png)

**Comment by jlouiss** [comment]
What versions of angular and angular-tree-component are you using?

**Comment by itzik25b** [comment]
Thanks for the quick response.
I'm using Angular version 4.4.4 and angular-tree-component ^5.0.0
I changed the template to be with static text and still no template is rendered.

I'm having a hybrid angular/angularJS application so that's might be the difference. I tried to do that with only angular components in the chain and i'm still having the same result - no template is rendered

**Comment by jlouiss** [comment]
I checked a couple things and I found out my solution wasn't actually working since the default behavior matched the example I wrote.
I'll try to find a solution in the next days and I'll tell you if I can find something

**Comment by adamkleingit** [comment]
Hi,
since this isn't something specific to angular-tree-component I'm closing the issue. It's more of an Angular question
