### ISSUE TITLE
Normalized data

### ISSUE THREAD

**Issue by marcinsirocki** [500tech/angular-tree-component#455]
I want to use tree with redux. I wonder about state shape in redux. Following the guide, state shape should be normalized, for example: 

nodes = {
0: { name: 'A', childIds: [1,2]},
1: {name: 'B', childIds: [3]},
2: {name: 'C'},
3: {name: 'D'}
};

How to use component tree with above model?

**Comment by adamkleingit** [comment]
I suggest you make a selector (using reselect) that transforms the above structure to the structure that conforms to angular-tree-component.
