### ISSUE TITLE
ERROR TypeError: Cannot read property 'emit' of undefined (NEW)

### ISSUE THREAD

**Issue by Luis16287** [500tech/angular-tree-component#457]
Same issue, same angular-tree-component version (4.0.0) of  [#449](https://github.com/500tech/angular-tree-component/issues/449), try the proposed solutions but I could not solve the problem

In my html
` <input #filter (keyup)="filterNodes(filter.value)" placeholder="Filtrar tareas..."/>`
`<tree-root class="scrollbar-style-1"
      #tree
      [nodes]="nodes"
      [options]="customTemplateStringOptions"
      [focused]="true"
      (event)="onEvent($event)"
      (initialized)="onInitialized(tree)"
    >`

In my ts
`@ViewChild` ('tree') tree: `TreeComponent;`

I use `@ViewChild `because in a modal I add a new task and update `nodes `and after doing this I need to use `this.tree.treeModel.update();` 
`this.tree.sizeChanged();` 

When i am trying to search in input it throws `"ERROR TypeError: Cannot read property 'emit' of undefined".`

**Comment by adamkleingit** [comment]
Hi,
can you send the entire code of the component so we can help you debug?

**Comment by adamkleingit** [comment]
Can you try with later version (5.X.X) and reopen the issue if it works?
Or reproduce with the plunkr:
https://plnkr.co/edit/u5fMmaM14rJ0aqG3k240?p=preview
