### ISSUE TITLE
expand collapse not works properly

### ISSUE THREAD

**Issue by istiti** [500tech/angular-tree-component#461]
If you are unable to reproduce on webpackbin, please:
- [package.json](https://gist.github.com/istiti/c612cda1bc23cf4f81e666ad7b9c715f)
- chrome Version 61.0.3163.100 (Build officiel) (64 bits)

![hihi](https://user-images.githubusercontent.com/2789203/32045731-4c4a0c46-ba41-11e7-81ec-e0a9787c4c04.gif)

**Comment by alunDillon** [comment]
I still can't solve,  can you share the demo?

**Comment by adamkleingit** [comment]
Hi, please reproduce here and re-open the issue:
https://plnkr.co/edit/u5fMmaM14rJ0aqG3k240?p=preview
