### ISSUE TITLE
Provide ability to show a special template when parent has zero children

### ISSUE THREAD

**Issue by AbdulRahmanAlHamali** [500tech/angular-tree-component#464]
Hello,

I would like to request the ability to optionally display a text indicating that we could not find any children for a certain node.

**Use case:**
We are fetching a list of elements from the backend to insert them as children of a certain node in the tree, but find out that this list is an empty list.

**Current behavior:**
The node will be expanded, but no children will be shown

**Suggested behavior:**
The node will be expanded, but will have a single child that says something like "No children available".
Of course, it would be better if the user of the library can write a template to choose what to show when there are no children.

What do you think?

Regards,

**Comment by adamkleingit** [comment]
Hi,
this can be done using the full template. Please refer to the docs

**Comment by AbdulRahmanAlHamali** [comment]
Thank you, for those interested. I ended up adding the following div to the full template:

<div *ngIf="node.isExpanded && node.children && node.children.length === 0" class="no-tree-children">No Entries Available...</div>

I think it would be nice, however, to be able to do that without the full template
