### ISSUE TITLE
treeNodeWrapperTemplate does not include templates in its ngOutletContext

### ISSUE THREAD

**Issue by DavidTheWin** [500tech/angular-tree-component#465]
The ngOutletContext in tree-node-wrapper.component.ts doesn't include the provided templates meaning that attempting to provide an ng-template for the tree node wrapper discards the tree node template.

**Comment by adamkleingit** [comment]
Merged - will be published soon

**Comment by adamkleingit** [comment]
Published in 5.2.0

**Comment by RFMV34** [comment]
I have same issue, when I apply custom #treeNodeWrapperTemplate my custom #treeNodeTemplate is gone.
