### ISSUE TITLE
ngOutletContext breaks with Angular 5.0.0

### ISSUE THREAD

**Issue by joachim-bl** [500tech/angular-tree-component#467]
I get a run time error after updating to Angular 5.0.0:
Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-container'.
1. If 'ngOutletContext' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.

In the specs I read that ngOutletContext should be renamed to ngTemplateOutletContext.
https://github.com/valor-software/ngx-bootstrap/issues/2658

regards
Joachim

**Comment by Flo12345** [comment]
I get the same error. Is there an update plan yet?

**Comment by Anoop-Goudar** [comment]
By replacing ngOutletContext to ngTemplateOutletContext in all files, it worked for me.

**Comment by digibum** [comment]
When will this be on npm? Tnx (5.1.2)

**Comment by devfcr** [comment]
Any news on this issue?

**Comment by jlouiss** [comment]
@devfcr this will be fixed as soon as possible according to [this comment](https://github.com/500tech/angular-tree-component/pull/468#issuecomment-342597634)

**Comment by adamkleingit** [comment]
Published in 5.2.0
