### ISSUE TITLE
Only root nodes are appearing.

### ISSUE THREAD

**Issue by salilbajaj** [500tech/angular-tree-component#471]
My component's code

`constructor(
    @Optional() private nodes:EvaluationMapperNodes[]  
    ) { }
 ngOnInit() {
    this.makeNodes()
    this.writeAuthorized = this.authenticationService.isUserAuthorized('admin');
  }
 makeNodes(){
    this.nodes=[
    {
      id: 1,
      name: 'root1',
      children: [
        { id: 2, name: 'child1' },
        { id: 3, name: 'child2' }
      ]
    },
    {
      id: 4,
      name: 'root2',
      children: [
        { id: 5, name: 'child2.1' },
        {
          id: 6,
          name: 'child2.2',
          children:[
            {id:7, name:'child2.2.1'}
          ]
        }
      ]
    },
  ];
  }
`
And data type declaration
`export class EvaluationMapperNodes {
    id: number;
    name: string;
    children: EvaluationMapperNodes[];
}`

Using 'EvaluationMapperNodes' class inside EvaluationMapperNodes is giving error that it is not assignable. and If  I us any[], only root appears
![tree-component](https://user-images.githubusercontent.com/14991148/32543469-bb529496-c49b-11e7-8c71-465401084697.JPG)

**Comment by picossi** [comment]
for me too happens this
I think it is related to this issue #468

**Comment by adamkleingit** [comment]
Hi,
did you import the css file?

**Comment by adamkleingit** [comment]
If it's related to #468 then it is fixed in 5.2.0

**Comment by webwizrd** [comment]
I still have this error with 5.2.1
Only root nodes appear. I have copied the example nodes array and used the same template as the demo. Nothing fancy.

**Comment by salilbajaj** [comment]
@webwizrd My issue was appearing because I dint include its css in angular-cli.json.
Included it and it started working just fine.
Its not mentioned in Documentation thats why missed it.

**Comment by webwizrd** [comment]
For me, the issue was that components were not correctly tagged. So I ended up modifying the .css file by putting ":host /deep/ " in front of all the defined styles - works fine now.

**Comment by adamkleingit** [comment]
Glad it worked out

**Comment by tommy-hansen** [comment]
@adamkleingit, I had the same issue and it took me a while to discover this thread. The suggestion in @webwizrd's [comment above](https://github.com/500tech/angular-tree-component/issues/471#issuecomment-348796236) works, but that seems heavy-handed, if I understand correctly. In `angular-tree-component.css` I now have literally:

```
:host /deep/ .tree-children.tree-children-no-padding { padding-left: 0 }
``` 
etc.

This is hosting the tree in another component with this in the component's `.less` file:
```
@import '~angular-tree-component/dist/angular-tree-component.css';
```

Is the approach supposed to work (`@import` in the component)? Is Less a problem? Any other comments?

Again, the work-around works, such as it is. 

Thanks!
