### ISSUE TITLE
How can we add a node to a specific node?

### ISSUE THREAD

**Issue by jball98** [500tech/angular-tree-component#473]
Does this plugin have this function? Or will the new added node just be automatically at the first level?

Not adding by dragging and dropping just programmatically triggered by a button click or something.

Im looking at the readme and it only adds to a specific node and not the highlighted ones.

Thanks

**Comment by matte00** [comment]
I need to. I need to add in drop event new node with custom data.

**Comment by adamkleingit** [comment]
Hi,
How does the user select under which node to add a new node - by right-click?

Basically you can just add a child to the original node children, and call `treeModel.update()`

**Comment by jball98** [comment]
so say a user click a node. can we get the index number from the click event and just call the addnode?


this.nodes[0].children.push.

if so, how do we get the index?

**Comment by matte00** [comment]
@adamkleingit The user select an item from external component (table's row) an drop this on a tree node. I need to add a now node with same custom data (get from table's row). I cannot add [treeDrag] because i haven't access to table's row template. 

```
options = {
  actionMapping: {
    mouse: {
      drop: (tree, node, $event, {from, to}) => {
        console.log('drag', from, to); // from === {name: 'first'}
        // Add a node to `to.parent` at `to.index` based on the data in `from`
        // Then call tree.update()
      }
    }
  }
}
```
I don't understand "Add a node to `to.parent` at `to.index` based on the data in `from`. Then call tree.update()" How you can do this?

**Comment by adamkleingit** [comment]
@jball98 there are a few options. If you have access to the TreeNode object you can access the original node's children with:
```
node.data.children.push(...)
```
If you have just the ID or the Path of the node you can find it first with `getNodeById(id)` or `getNodeByPath(path)` - and then run the above code.

@matte00 If you can't add [treeDrag] then the action mapping is irrelevant - you'll need to override the node's wrapper template and add a drop event of your own.

**Comment by matte00** [comment]
@adamkleingit Thank you for your response. 

```
        actionMapping: {
            mouse: {
                dblClick: (tree, node, $event) => {
                    if (node.hasChildren) TREE_ACTIONS.TOGGLE_EXPANDED(tree, node, $event);
                },
                drop: (tree, node, $event, data) => {
                    this.dropToTree(tree, node, $event, { from: null, to: data.to });
                }
            }
        },
```

Drop event call a method "dropToTree"
```
    dropToTree(tree, node, $event, { from, to }) {
        let t = new TreeNode(this.dragElement, to.parent, tree, to.index);
    }
```
I can create a node with my custom data (dragElement) but how i can do to add this node?

**Comment by jball98** [comment]
@adamkleingit 
if we use findbynodeid then we need to expand all nodes. is there anyway to not expand all the nodes and still achieve findbynodeid? the reason I ask is because the tree is very big

**Comment by adamkleingit** [comment]
@matte00 you shouldn't create a TreeNode, just update the original data. So
basically add the node to `to.parent.data.children` in position `to.index`.
And then you need to either call update(), or pass a new instance of
`nodes` if you're using immutable data.

@jball98
Why do you need to expand all? Are you loading the nodes asynchronously?
What are you trying to achieve?


*Adam Klein*
*Chief Technology Officer*



*Tel.*   +972-52-7475633 <+972527475633>
*Web*  500tech.com <http://www.500tech.com/> | github.com/500tech |
@adamklein500 <http://twitter.com/adamklein500>

**Comment by matte00** [comment]
@adamkleingit Thank you Adam, it's works! I have another question if you can help me. If i call tree,update after node added to empty parent node the expand method don't works. Where is my error?

**Comment by adamkleingit** [comment]
Can you reproduce in https://plnkr.co/edit/u5fMmaM14rJ0aqG3k240?p=preview?


*Adam Klein*
*Chief Technology Officer*



*Tel.*   +972-52-7475633 <+972527475633>
*Web*  500tech.com <http://www.500tech.com/> | github.com/500tech |
@adamklein500 <http://twitter.com/adamklein500>

**Comment by matte00** [comment]
@adamkleingit Hi Adam, thank you for your help. I resolved! 

After adding node to empty parent (no children) i need to do:
```
let n: TreeNode = this.tree.treeModel.getNodeById(p.id);
if (n != null) {
      n.expand();
      n.setActiveAndVisible(false);
}
```

**Comment by adamkleingit** [comment]
Coolio
