### ISSUE TITLE
Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-container'

### ISSUE THREAD

**Issue by serdarturkmen** [500tech/angular-tree-component#475]
Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-container'

**Comment by jball98** [comment]
duplicate #467

**Comment by maheshwarambhe** [comment]
By replacing ngOutletContext to ngTemplateOutletContext in all files, it worked for me.
I think it need to update in latest version

**Comment by adamkleingit** [comment]
Published in 5.2.0
