### ISSUE TITLE
How to select the checkbox and the node name separately?

### ISSUE THREAD

**Issue by dannyzhan** [500tech/angular-tree-component#476]
Thanks for implementing such a good component, it's so good.

    I recently find how to add a tri-state checkbox according to the official document, 
but I want to select the checkbox and the node name separately. 
     currently when I click the node name, the checkbox state is changed, that's not I want.  what I want is: when I click the checkbox, the checkbox state changed, when I click the node name, the checkbox state keeps unchanged.
    I tried to use the wrapper template and the full node template, but failed, not sure how to customized my requirement.

Thanks a lot!

**Comment by adamkleingit** [comment]
Hi,
you should probably save your own set of `checkedNodeIds` instead of using the `activeNodeIds` - and set the `checked` value accordingly.
Hope it helps

**Comment by dannyzhan** [comment]
Thanks, I resolved the issue by myself.
This is because the demo from the official document overrides the mouse click event in the IActionMapping.
I removed that override and then my requirement is met.
Thanks again for your great component!

**Comment by adamkleingit** [comment]
@dannyzhan awesome
