### ISSUE TITLE
Async children not handled when restoring state (restoring expandedNodeIds without pre-fetching data)

### ISSUE THREAD

**Issue by rart** [500tech/angular-tree-component#477]
I want to store the state of the component and restore it when it comes into view again and I'm using async load.

When I restore the tree state, async child opens up and shows "loading" but in reality, the request doesn't even fire and the loading message just sits there. Haven't dug into the code yet but seems that the component simply doesn't handle the async children and just tries to open whatever ids it finds within the current data.

http://embed.plnkr.co/QvStlM/

PS. Sorry, I did a plunk before I opened the issue and saw the webpackbin message; I had finished the plunk by then. Hope plunker is ok. :)

**Comment by CK110** [comment]
hava same problem，
it seems like (statechange) is trigger before （loadNodeChildren），
is there  any event ( param: $event is state )   trigger after（loadNodeChildren）

**Comment by adamkleingit** [comment]
I'll try to solve.
Actually webpack bin stopped working so the plunkr helps a lot

**Comment by adamkleingit** [comment]
OK I fixed - will be published in 5.3.0

**Comment by rart** [comment]
That was awesomely fast, thank you!

**Comment by adamkleingit** [comment]
Published in 6.0.0 (I had to make a breaking change - not returning anything when calling setIsExpanded)
