### ISSUE TITLE
How to create context menu on node right click

### ISSUE THREAD

**Issue by afsalcodehack** [500tech/angular-tree-component#478]
Hi,

To allow for a faster response, please read carefully:

Please look for an answer in the docs before submitting an issue:
angular2-tree.readme.io.

In case you are reporting a bug, please reproduce it on webpack bin. You can start from here:
https://www.webpackbin.com/bins/-KqGwvVQLknZ-fTXHjCO
Open the left side menu and click copy
Make your changes
Click Save to view results
Share the URL once reproduced

If you are unable to reproduce on webpackbin, please:
- paste your package.json
- say which browser you are using
- paste your nodes and options and whatever code your feel will help reproduce the error

Thank you and happy programming

**Comment by adamkleingit** [comment]
Using actionMapping, or a custom node wrapper template
