### ISSUE TITLE
About ngtemplateoutlet  with angualr 5.0.0

### ISSUE THREAD

**Issue by yunClouds** [500tech/angular-tree-component#479]
Hi
I had update the angular-tree-component @ version 5.2.0 , but It still has the error about ngtemplateoutlet  :

ERROR in Error at W:/webStormWorkspace/coast-guard/node_modules/ng-tree-antd/components/nz-tree.component.d.ts.NzTreeComponent.html(59,13):  ("
          <ng-container
            [ngTemplateOutlet]="nzTitle"
            [ERROR ->][ngOutletContext]="{ $implicit: node, node: node, index: index }">
          </ng-container>
        ")

How to  resolve it。
thanks a  lot

**Comment by yunClouds** [comment]
ohh, I know that ....

**Comment by adamkleingit** [comment]
What is nz-tree?
