### ISSUE TITLE
Documentation about Drag&Drop - onMoveNode - moveNode

### ISSUE THREAD

**Issue by Fortidude** [500tech/angular-tree-component#480]
"angular-tree-component": "^5.2.1"
"@angular/core": "^4.2.4"

Drag & Drop:
https://angular2-tree.readme.io/docs/drag-drop

```
options = {
  allowDrag: true
}

onMoveNode($event) {
  console.log(
    "Moved",
    $event.node.name,
    "to",
    $event.to.parent.name,
    "at index",
    $event.to.index);
}

<tree-root
    (onMoveNode)="onMoveNode($event)"
    [nodes]="nodes"
    [options]="options"></tree-root>

```
(onMoveNode) not working. I check code inside dist/components/tree.component.js and there is (moveNode)  - and ofc that one works fine.

**Comment by adamkleingit** [comment]
I will update the docs. Thanks!

**Comment by etonyali** [comment]
This is still not working and the documentation is the same.
