### ISSUE TITLE
Using deprecated ngOutletContext causes Angular 5 build to fail

### ISSUE THREAD

**Issue by dlabrecq** [500tech/angular-tree-component#483]
The ngOutletContext was deprecated in Angular 4 and has been removed in Angular 5. Please use
ngTemplateOutletContext instead.

ERROR in Error at .../node_modules/angular-tree-component/dist/components/tree-node.component.d.ts.TreeNodeComponent.html(23,9): Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-container'.
1. If 'ngOutletContext' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
      <ng-container
        [ngTemplateOutlet]="templates.treeNodeFullTemplate"
        [ERROR ->][ngOutletContext]="{ $implicit: node, node: node, index: index, templates: templates }">
      </ng-c")

**Comment by adamkleingit** [comment]
Hi,
this was fixed in version 5.2.0

**Comment by dlabrecq** [comment]
Thought I was using 5.2.1, but 6.0.0 builds fine. Thanks!
