### ISSUE TITLE
How to get reference to tree in order to call the expandAll() method

### ISSUE THREAD

**Issue by hanijazzar** [500tech/angular-tree-component#487]
I want to expand the children of a node after fetching the data asynchronously. I saw the issues concerning isExpanded and that it only works for static data loaded initially. I tried many of the suggestions but none worked. My question is how can I use the expandAll() method on the tree after loading the data? Should I use TreeModel or TreeComponent or TreeNode? I only have my tree in the template and I'm not sure how to use it in the component. Documentation is very confusing. Some said to use tree.treeModel.expandAll(); but what is 'tree' in this case? how do u link it to the 'nodes'?

Template:
                      
```
                <tree-root
                        #tree
                        [nodes]="nodes"
                        [options]="options">
                    <ng-template #treeNodeTemplate let-node="node" let-index="index" >
                        <input
                                (change)="check(node, !node.data.checked)"
                                type="checkbox"
                                (click)="check(node, !node.data.checked)"
                                [indeterminate]="node.data.indeterminate"
                                [checked]="node.data.checked" style="width: 18px;height: 18px; cursor: pointer">
                        {{ node.data.name }}
                    </ng-template>
                </tree-root>
```

Component:
nodes = [........// the data loaded later]

**Comment by ScottSpittle** [comment]
```
@ViewChild(TreeComponent) private tree: TreeComponent;

let treeModel = this.tree.treeModel;
let i: TreeNode = treeModel.getNodeById(id);

i.expandAll();
```

**Comment by hanijazzar** [comment]
Hello, Thanks for the answer. But when I tried it, it keeps giving me 'TypeError: i is undefined' in the console. I'm sure that the tree is filled and that the id passed is correct

**Comment by hanijazzar** [comment]
Nevermind it now works. I had to add 'this.tree.treeModel.update();' Thanks a lot
