### ISSUE TITLE
Drag'n'Drop in the same Tree is not working

### ISSUE THREAD

**Issue by AhoiBrause** [500tech/angular-tree-component#488]
Hey,

Drag n Drop is not working on my Project, please look to my Source... I also tested the Example "CLI"... its not working too :(
The Item is Draggable and Dropable, but onDrop is the Node referenced on the Dropplace or the Item doesnt drop

component
`import { Component } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { JSystemService } from '../../../japi/services/system.service';
import { JBetriebAngebotService } from '../../../japi/services/betrieb/angebot.service';

import { BtrAngebotPos } from '../../../japi/objects/betrieb/btrAngebotPos';
import { TreeModule, ITreeState, ITreeOptions } from 'angular-tree-component';

@Component({
    selector: 'view-verwaltung-angebot-positionen',
    template: `
<div class="col-md-12">
  <div class="box box-default">
    <div class="box-header with-border">
      <h5 style="display: inline-block;" class="box-title">Liste</h5>
    </div>
    <div class="box-body">
      <tree-root (moveNode)="onMoveNode($event)" [nodes]="nodes" [options]="options"></tree-root>
    </div>
  </div>
</div>
    `
})
export class ViewVerwaltungAngebotPositionenComponent {
  public options: ITreeOptions = {
    allowDrag: true,
    allowDrop: true
  };

  public nodes = [
    {
      id: 1,
      name: 'root1',
      children: [
        { id: 2, name: 'child1' },
        { id: 3, name: 'child2' }
      ]
    },
    {
      id: 4,
      name: 'root2',
      children: [
        { id: 5, name: 'child2.1' },
        {
          id: 6,
          name: 'child2.2',
          children: [
            { id: 7, name: 'subsub' }
          ]
        }
      ]
    }
  ];

  constructor(private system: JSystemService,
              public angebot: JBetriebAngebotService,
              private route: ActivatedRoute) {

  }

  onMoveNode($event) {
    console.log(
      'Moved',
      $event.node.name,
      'to',
      $event.to.parent.name,
      'at index',
      $event.to.index);
  }

}
`

package.json
`{
  "name": "intern-v5",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "angular-tree-component": "^6.0.0",
    "core-js": "^2.4.1",
    "ng2-file-upload": "^1.3.0",
    "rxjs": "5.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.5.5",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
}
`

**Comment by AhoiBrause** [comment]
Same fix like issue #488

**Comment by sulhome** [comment]
what is the fix for this?

**Comment by AhoiBrause** [comment]
npm install mobx-angular@1.9.0 --save

**Comment by sulhome** [comment]
is this a temp fix?

**Comment by sulhome** [comment]
@AhoiBrause 
Just to confirm
you have to install this specific version **1.9.0** of `mobx-angular`
If you install latest version **2.0.1** of `mobx-angular` then drag and drop will not work.
I think this issue should be **reopened** as this looks like a workaround rather than a permanent solution

**Comment by adamkleingit** [comment]
Will be fixed in coming version

**Comment by adamkleingit** [comment]
Fixed in 6.1.0

**Comment by sulhome** [comment]
@adamkleingit thank you
so the fix now is just to upgrade? do I need to still reference `mobx-angular`?

**Comment by sulhome** [comment]
@adamkleingit 
if `mobx-angular` is dependency for tree component then why not tree component include it instead of end user trying to figure out what version of `mobx-angular` to include
