### ISSUE TITLE
Drop slot height cannot be set to 0

### ISSUE THREAD

**Issue by WinMac32** [500tech/angular-tree-component#489]
It appears the logic of [tree-options.model.ts](https://github.com/500tech/angular-tree-component/blob/master/lib/models/tree-options.model.ts) does not permit a drop slot height of 0, as it gets coerced to 'false' in the null check of the dropSlotHeight getter.

The line in question is: 
`return this.options.dropSlotHeight || 2`

**Comment by adamkleingit** [comment]
True, will be fixed in 6.0.1


*Adam Klein*
*Chief Technology Officer*



*Tel.*   +972-52-7475633 <+972527475633>
*Web*  500tech.com <http://www.500tech.com/> | github.com/500tech |
@adamklein500 <http://twitter.com/adamklein500>

**Comment by adamkleingit** [comment]
Fixed in 6.1.0
