### ISSUE TITLE
How to add horizontal scroll?

### ISSUE THREAD

**Issue by Agonzit** [500tech/angular-tree-component#493]
I'm giving a border-box to every node, at first the left and right edges got cut off, but fixed it with a 1px padding on tree-leaf and tree-node.

The problem is with large text it just gets cut off and the node remains the same width. How can i make it so a scrollbar is activated?

Using `overflow:auto` on 'tree-children' and overflow:visible on node-wrapper does render a scrollbar, but the text is outside the node.

How could I make it so the node grows along with it's content?

Thank you

**Comment by adamkleingit** [comment]
Please reproduce to plnkr and reopen:
https://plnkr.co/edit/u5fMmaM14rJ0aqG3k240?p=preview
