### ISSUE TITLE
Tree node status cannot update automatically when data is updated.

### ISSUE THREAD

**Issue by RonnyRen** [500tech/angular-tree-component#495]
Hi,

I got the latest version 6.0 and work with Angular 5.0.2, and found that a new issue:
When tree data is updated (one node data is updated, not add or move node), the tree could not update automatically. When I collapse and then expand parent node, the status is updated. I tried call method this.tree.treeModel.update(), it still not work. Is there any easy workaround?

**Comment by RonnyRen** [comment]
I got a workaround that add specific dependency  below to package.json file
"mobx-angular": "1.9.0" 
The version later than 1.9 cannot work

**Comment by adamkleingit** [comment]
Fixed in 6.1.0

**Comment by weiwang94** [comment]
what fixed in 6.1.0?

**Comment by salilbajaj** [comment]
Even drag and drop is getting reflected when parent node is collapsed and expanded
