### ISSUE TITLE
mobxAngular log message

### ISSUE THREAD

**Issue by matthewdfleming** [500tech/angular-tree-component#496]
There is a log message that shows up in the console: `Type mobxAngularDebug(true) or mobxAngularDebug(false) to trigger MobX debugging`.

I couldn't see of a way to disable the message from coming up. Do you know of any way to disable the message?

**Comment by adamkleingit** [comment]
It's a message from mobxAngular which is being used in the tree component.
What's the problem with it?


*Adam Klein*
*Chief Technology Officer*



*Tel.*   +972-52-7475633 <+972527475633>
*Web*  500tech.com <http://www.500tech.com/> | github.com/500tech |
@adamklein500 <http://twitter.com/adamklein500>

**Comment by matthewdfleming** [comment]
It's obviously not some huge deal or anything but I'm not a fan of debug logging within production apps is all.

**Comment by adamkleingit** [comment]
I'll the issue in mobx-angular
