### ISSUE TITLE
bug: focusNextNode leads to mistakes after filtering

### ISSUE THREAD

**Issue by philipphutterer** [500tech/angular-tree-component#499]
When you fill the tree with some nodes and filter them, the tree indexing is not updated or adapted. All nodes still have their old index what leads to the following scenario:
 - _findAdjacentSibling will return a wrong sibling
 - up and down arrow keys show that traversing the tree is not correct anymore

I think replacing 'this.index' through 'getIndexInParent(skipHidden)' in _findAdjacentSibling would work. That might lead to a loss of performace in bigger trees; there might be a better solution.

To explain completely how to see the mistake:
 - Go to the demo: https://angular2-tree.readme.io/docs/getting-started
 - Add some nodes
 - filter by 'new child'
 - select one node and click next node / previous node to see the wrong focusing

**Comment by adamkleingit** [comment]
Will be fixed in next version

**Comment by adamkleingit** [comment]
Solved in 7.0.0
