### ISSUE TITLE
Module not found: Error: Can't resolve 'angular-tree-component'

### ISSUE THREAD

**Issue by gsv91** [500tech/angular-tree-component#503]
It can be stuped but I'm novice with angular and npm, but really want to use your lib.

I installed your package via npm, as mentioned at https://angular2-tree.readme.io/docs/getting-started. Npm says that I need to install a couple of peer dependencies like angular/common and angular/core. I installed them too with rxjs and zone.js.
But after all of this manipulation I still have error:

> Module not found: Error: Can't resolve 'angular-tree-component'

Of course I have 
```
import { TreeModule } from 'angular-tree-component';
@NgModule({
  imports: [..., TreeModule],
  ...
})

```
in my module. What is the reason of this error? Why angular cant find your module? And how to fix that? May be that problem related with angulat/cli that I use to serve and generate?

**Comment by adamkleingit** [comment]
If you use angular cli then you already have angular/core and angular/common installed.
Do you have angular-tree-component in your package.json?
Can you send a link to your code on github? 
Doesn't sound like an issue with the library - I'm closing the issue and if I can reproduce it I'll reopen it.

**Comment by gsv91** [comment]
Yes, the problem was in lack of dependency in package.json. Thanks.
