### ISSUE TITLE
ERROR TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by asif-khan17** [500tech/angular-tree-component#506]
Hi,

To allow for a faster response, please read carefully:

Please look for an answer in the docs before submitting an issue:
angular2-tree.readme.io.

In case you are reporting a bug, or requesting help, please reproduce it in a GIT repo or fork this online template:
https://plnkr.co/edit/u5fMmaM14rJ0aqG3k240?p=preview

getNodeById() gives undefined , I have written it in setTimeOut and also tried using updateData callback but still I am getting this error 

Plz help 
Thank you and happy programming

**Comment by asif-khan17** [comment]
(initialized) is also giving me error but in documentation initialized is there

**Comment by adamkleingit** [comment]
Please reproduce in the above plunkr and reopen the issue
