### ISSUE TITLE
Incorrect arguments order for Array.reduce

### ISSUE THREAD

**Issue by ferreirocm** [500tech/angular-tree-component#507]
https://github.com/500tech/angular-tree-component/blob/0fdf0ebad482aeafd262b8e5366b36a4c4e13a19/lib/models/tree.model.ts#L290

As per:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

the correct order is **(accumulator, currentValue)**, and the code snippet should be:

```this.hiddenNodeIds = nodeIds.reduce(```**(hiddenNodeIds, id)**``` => Object.assign(hiddenNodeIds, {```

**Comment by adamkleingit** [comment]
Merged - will be published in the coming release
