### ISSUE TITLE
node children not loading for async http request

### ISSUE THREAD

**Issue by MjRockss** [500tech/angular-tree-component#514]
I am trying to load node children by sending a httprequest to server. However,till the response is generated,it exits the getchildren function and keeps on showing the loading text on the clicked node.

```
nodes = [{
  id: 1,
  name: 'root1',
  children: [{
    id: 2,
    name: 'child1'
  }, {
    id: 3,
    name: 'child2'
  }]
}, {
  id: 4,
  name: 'root2',
  children: [{
    id: 5,
    name: 'child2.1'
  }, {
    id: 6,
    name: 'child2.2',
    hasChildren: true,
    children: [{
      id: 7,
      name: 'subsub'
    }]
  }]
}, {
  id: 8,
  name: 'rootn',
  hasChildren: true
}];

options = {
  getChildren: (node: TreeNode) => {
    return this.getChild(node.id).subscribe(
      result => {
        return result;
      }
    )
  }
}

getChild(nodeId) {
  return this.http.post('http://localhost:8080/App/fetchNodesForTree', {
      seqID: nodeId
    })
    .map(
      res => {
        let data = res.text() ? res.json() : [{}];
        return data.childNodes;
      },
      err => {
        let data = err.text() ? err.json() : [{}];
        return data;
      }
    );
}

```
![tree image](https://user-images.githubusercontent.com/34569686/34194564-49b57736-e57f-11e7-8cdf-5ba0a5e26f61.JPG)

I dont know what am i doing wrong. Any help would be appreciated.

**Comment by adamkleingit** [comment]
Try calling toPromise (the tree doesn't support observable at the moment)

**Comment by MjRockss** [comment]
@adamkleingit  can you please share how to do that?? code sample etc.

**Comment by MjRockss** [comment]
@adamkleingit I tried with toPromise the solution worked children are getting loaded. Now I am having children which may contains sub child and so on in nested form. using the same logic as above the I am not loading the data in advance it is only loaded after the node is clicked. 
For the first time it is loading children but the sub children are not getting loaded. (Observation : for sub-children the getChildren
```
options = {
  getChildren: (node: TreeNode) => {
    return getService('http://localhost:8080/App/fetchNodesForTree', {
      seqID: nodeId
    })
    .then(result => {console.log(result.childNodes); return result.childNodes;})
    .catch(error => {console.log(error); return [];});
  }
}

 getService(url: string, data:any): Promise<any> {
    return this.http
        .post(url,data, this.options)
        .toPromise()
        .then(this.extractData)
        .catch(this.handleError);
}

private extractData(res: Response) {
    let body = res.json();
    return body || {};
}

private handleError(error: any): Promise<any> {
    console.error('An error occurred', error);
    return Promise.reject(error.message || error);
}
```
Image of the same
![treeview with child](https://user-images.githubusercontent.com/34569686/34207557-0273337c-e5b1-11e7-9e8a-15499ee4c78b.JPG)

I want something like this If i click on the child it should still call the getChildren and load child as shown in the red circle 
![treeview with child_red circle](https://user-images.githubusercontent.com/34569686/34207609-3e51cad4-e5b1-11e7-94ae-352bb1fc9617.JPG)

Response received from the Promise looks something like this

```
[{children: Array(0), hasChildren: true, id: 139, name: "child 1.1"},
{children: Array(0), hasChildren: true, id: 114, name: "child 1.2"},
{children: Array(0), hasChildren: true, id: 90, name: "child 1.3"},
{children: Array(0), hasChildren: true, id: 92, name: "child 1.4"},
{children: Array(0), hasChildren: true, id: 178, name: "child 1.5"}]
```
Any help would be appreciated.
