### ISSUE TITLE
Change state of checkbox (check)

### ISSUE THREAD

**Issue by LuisReinoso** [500tech/angular-tree-component#529]
Hi, everyone!

I want to change the state of every node (checkbox value) when tree-root component is initialized. I don't found how to change state of checkbox in documentation.

I can access to the treeModel when is initialized according with documentation using (initialized).

HTML:
```HTML
<tree-root #tree [nodes]="nodes" [options]="options" (initialized)="onInitTree($event)>"
<!-- some code -->
</tree-root>
```

Typescript
```javascript
onInitTree(event) {
//... some code
// Here access to node
event.treeModel.getNodeById(idNode).XXXX // 
//... some code
}
```

I don't know wich method or attribute use to change the checkbox value.

I try to set isSelected attribute of TreeNode but this give an error "It is not possible to assign a new value to a computed value."

Could you give an example how to do this.

**Comment by arundhaj** [comment]
you should be using `node.setIsSelected(true|false)` or `node.toggleSelected()`

**Comment by klteograss** [comment]
@arundhaj thanks, is there any efficient way of initialize the state of the checkboxes?  `node.setIsSelected` is kinda of slow.

**Comment by LuisReinoso** [comment]
Thanks!

**Comment by LuisReinoso** [comment]
I solved this implementing a #treeNodeTemplate I based on this:
[https://github.com/500tech/angular-tree-component/blob/a44013417043c3544906d436b28bafe3a56a1d75/example/cli4/src/app/checkboxes/checkboxes.component.ts](https://github.com/500tech/angular-tree-component/blob/a44013417043c3544906d436b28bafe3a56a1d75/example/cli4/src/app/checkboxes/checkboxes.component.ts)

I didn't solve this using `node.setIsSelected(true|false)` or `node.toggleSelected()`

In this way I use the custom variable called `checked: true`

For example: If you have this nodes
```javascript
nodes = [
    {
      name: 'root1',
      checked: true,
    },
    {
      name: 'root2',
      checked: false,
      children: [
        { name: 'child1', checked: false },
        { name: 'child2', checked: false, children: [
          { name: 'grandchild1', checked: false },
          { name: 'grandchild2', checked: false }
        ] }
      ]
    }
];
```
You might to implement
```javascript
public check(node, checked) {
    this.updateChildNodeCheckbox(node, checked);
    this.updateParentNodeCheckbox(node.realParent);
}
```
In this way I save the nodes checked on start;
