### ISSUE TITLE
dispose/unsubscribe for tree events

### ISSUE THREAD

**Issue by alxkhr** [500tech/angular-tree-component#535]
Wouldn't it be nice to **return** the subscription or the autorun object on calling `TreeModel.subscibe()` or `TreeModel.subscribeToState()`, so it would be possible to listen to next `loadNodeChildren`event (for example in a Promise) and then dismiss the subscription?

Me and my team would be very grateful for that tiny API change! :)

**Comment by sroucheray** [comment]
Hi @500tech-user and thanks for the great work on this tree component.

I think @alxkhr is right and I would even go a bit further. It seems to me a major drawbacks for this component as all the subscriptions made on `TreeModel` are never unsubscribed.
See https://github.com/500tech/angular-tree-component/blob/master/lib/models/tree.model.ts#L44
There are two consequences for the user of the component: 
1) I am still notified by event on the component/model even after the component has been destroyed
2) As there is still a binding between the component and the model there might be a memory leak there, thus a performance concern when using the tree component.

**Comment by adamkleingit** [comment]
@alxkhr, @sroucheray - you are right, need to implement an onDestroy hook in treeModel.
Do you want to make a PR? Would be very helpful. Thanks!

**Comment by sroucheray** [comment]
@adamkleingit I just pushed a simple PR. I hope I have not missed any of your guidelines. Tell me if I need to change/add anything.

**Comment by sroucheray** [comment]
@adamkleingit I think this can be closed

**Comment by adamkleingit** [comment]
@sroucheray  Thanks. I added you to maintainers group. Are you on the slack channel as well?
Published the fix in 8.0.1
