### ISSUE TITLE
the style url seems  to be something wrong

### ISSUE THREAD

**Issue by guguji5** [500tech/angular-tree-component#542]
the introduce of the doc write as below:
`@import '~angular-tree-component/dist/angular-tree-component.css;`
but it seems incorrect. the angular-tree-component folder is in under the node_module and not in the root folder.

**Comment by JanLoebel** [comment]
The **~** is used in JavaScript files as an alias for 'node_modules'. But I guess you use SCSS/SASS and there seems to be a problem with the tilde, see also https://github.com/angular/angular-cli/issues/9185 or https://stackoverflow.com/questions/37106230/node-sass-does-not-understand-tilde

**Comment by guguji5** [comment]
Hi @JanLoebel.
Thanks for your reply.  I handle it using the relative path. 
could I raise another problem? it's that I used this plugin with checkbox option, but it doesn't apply the property or method to get the nodes selected. and the activeNodes property just refer to the active nodes, not the selected ones
