### ISSUE TITLE
how to get all selected nodes

### ISSUE THREAD

**Issue by guguji5** [500tech/angular-tree-component#544]
I used this plugin with checkbox option, but it doesn't apply the property or method to get the nodes selected. and the activeNodes property just refer to the active nodes, not the selected ones

any help will be appreciated ! thanks advanced.

**Comment by EclipseIsBwaaaa** [comment]
Yeah i have the same problem!
What i did was to iterate over all the tree and use TreeModel.isSelected(node: any) for every node on the tree., and populated an array with every selected node.

**Comment by isaklafleur** [comment]
@EclipseIsBwaaaa @guguji5 I get the selected nodes by make a simple filter over TreeModel.selectedLeafNodeIds and only storing the nodes that have true.

**Comment by Isaac2008** [comment]
selectedLeafNodeIds is a empty array

**Comment by guguji5** [comment]
Five months goes, I remember I realize this feature according to its own method. but I forget the details. So I close the issue if any deep detail needed, just comment below.

**Comment by elibushehri** [comment]
I want to get selected node using their parent, i mean when all children of a node is selected only parent node id should be in selected nodes not all of its children ids? how it can be implement?

**Comment by adamkleingit** [comment]
You can manage your own state outside the tree by subscribing to tree state updates using `treeModel. subscribeToState((state) => ...)` and then I guess drilling down the tree from top to bottom and if a node is a parent and has `isAllSelected` - then don't drill down to its children.

**Comment by daliri72** [comment]
> tree.treeModel.selectedLeafNodeIds
What is the `entries`
