### ISSUE TITLE
ERROR TypeError: Cannot read property '' of undefined while using viewchild

### ISSUE THREAD

**Issue by vmallik59** [500tech/angular-tree-component#562]
####Parent component

export class HeaderComponent implements AfterViewInit {

  @ViewChild(SidebarComponent) sidebarComponent;
  
  ngAfterViewInit() {
   console.log("==========>  "+this.sidebarComponent.headerMenuItems);
  }

#### Child component

export class SidebarComponent {
  headerMenuItems: MenuItem[] = [];

**Comment by adamkleingit** [comment]
How is this relevant to the tree ?
Please reproduce in the plunkr provided when opening an issue and reopen
