### ISSUE TITLE
Performance degradation (unresponsive) with 30 nodes and drag drop

### ISSUE THREAD

**Issue by KirilVandovTelerik** [500tech/angular-tree-component#565]
Currently you are not able to make simple operations like drag and drop if you have 30+ nodes. You need to wait for like 20seconds to get the tree responsive and make the operation.

Here is an example: https://angular-bbjud7.stackblitz.io

**Comment by Sqrrl** [comment]
Your demo shows a blank page for me. Have you tried to disable change detection while dragging? See [#361](https://github.com/500tech/angular-tree-component/issues/361#issuecomment-351448859)

**Comment by KirilVandovTelerik** [comment]
thx that solved the issue
