### ISSUE TITLE
IE11 doesn't work - polyfill error

### ISSUE THREAD

**Issue by gtzinos** [500tech/angular-tree-component#567]
Hello, your demo at https://angular2-tree.readme.io/docs doesn't work.

**Comment by KeithGillette** [comment]
Link works fine for me. Perhaps a transient outage?

**Comment by gtzinos** [comment]
Check this photo http://prntscr.com/in3osb

**Comment by KeithGillette** [comment]
Loads fine for me in both Chrome on MacOS and Safari on iOS. What browser, version, & platform are you using? What errors appear on the browser console?

**Comment by stogle** [comment]
It fails to load in IE11 with an exception:

> SCRIPT5022: Exception thrown and not caught
> polyfills.bundle.js (804,36)
>

**Comment by adamkleingit** [comment]
Looks like a problem with polyfills. No idea why it suddenly started happening. Maybe need to include core-js polyfills as mentioned here:
https://github.com/angular/angular-cli/issues/4128

**Comment by Hesesses** [comment]
All demos on docs page the seems to be broken on IE11, I'm getting error with "startsWith"

**Comment by adamkleingit** [comment]
Fixed in docs. Thanks
Using the following polyfills:
```javascript
import 'core-js/es6/string';
import 'core-js/es6/object';
import 'core-js/es6/array';
```

**Comment by raDiesle** [comment]
I do use, but [].includes does not work in IE11, others work
