### ISSUE TITLE
Tree Component Not Working With Latest Mobx Update

### ISSUE THREAD

**Issue by ajkuntz** [500tech/angular-tree-component#573]
Our angular project that includes this component quit building today.  Upon investigating, it seems that mobx was updated and it is no longer compatible with the tree.  Here is an example of a forked version of your plunkr:

https://plnkr.co/edit/y6KWNYXbJtwDfWUsWMI3?p=preview

All I did was update the mobx version from ^3 to ^4.

The workaround for now was to install a version 3 of mbox  so it doesn't implode.

**Comment by MalithHatananchchige** [comment]
Yes, I'm getting the same issue here. But update mobx did not make any difference. Still getting warnings

**Comment by FeLiX-7** [comment]
+1

**Comment by apeter10** [comment]
+1

**Comment by yunClouds** [comment]
+1
errors like this:
![image](https://user-images.githubusercontent.com/26613310/37326384-e1ba8966-26cc-11e8-976a-991ef6ce9ca8.png)

**Comment by xino1010** [comment]
Temporary solution:
npm install --save-dev mobx@3.6.2

**Comment by ashilay** [comment]
+1

**Comment by AnatoliiSirosh** [comment]
+1

**Comment by vladyslav-nadtoka** [comment]
+1

**Comment by saif-adnan** [comment]
+1

**Comment by adamkleingit** [comment]
True, angular-tree-component had >=3. I'm changing to ^3 and publishing in the coming hour

**Comment by adamkleingit** [comment]
Published - can you try with version 7.0.2-beta1?

**Comment by micahwood** [comment]
I just tested with 7.0.2-beta1 and am no longer getting the mobx error.

**Comment by adamkleingit** [comment]
Published in 7.0.2
