### ISSUE TITLE
Error because Mobx has been updated to 4.0.0

### ISSUE THREAD

**Issue by EduJGURJC** [500tech/angular-tree-component#575]
Hi,

It seems that Mobx was updated yesterday to version **4.0.0** and since then angular-tree-component does not work. I get the following error:

![image](https://user-images.githubusercontent.com/26252085/37340029-f5ec1626-26bc-11e8-84ef-55cb940a0782.png)

So far it has worked well with mobx version  **3.6.1**. It would be nice if you set a fixed version in the package.json.

**Comment by petercmuc** [comment]
we save the same issue here and as a workaround specified mobx 3.6.1 in our package.json.

**Comment by albohlabs** [comment]
@petercmuc how do you do that?

**Comment by basvandenheuvel** [comment]
Same issue for our team.

**Comment by 1wiseash** [comment]
I changed the angular-tree-component's package.json file to require mobx@3.6.1 _and_ ran '''npm install mobx@3.6.1''' at the command line. I had to do both to fix the problem.

**Comment by ashilay** [comment]
+1, plz provide fix, issue affects working environment

**Comment by AnatoliiSirosh** [comment]
+1

**Comment by rbbaron** [comment]
+1

**Comment by ali-himindz** [comment]
+1

**Comment by adamkleingit** [comment]
Should be fixed in 7.0.2-beta1 - can you check?

**Comment by albohlabs** [comment]
Works for me. Thanks.

**Comment by EduJGURJC** [comment]
It's working! Thank you!

**Comment by dungahk** [comment]
@adamkleingit I'm using version 5, is it possible to release a hotfix within this major version? That would be great!

Thanks for the fix, btw!

**Comment by omerson** [comment]
I cannot find 7.0.2-beta1

**Comment by adamkleingit** [comment]
Released in 7.0.2 (also released 7.1.0 since then)
