### ISSUE TITLE
ERROR in Metadata version mismatch

### ISSUE THREAD

**Issue by hipresario** [500tech/angular-tree-component#578]
`ERROR in Metadata version mismatch for module /home/node_modules/mobx-angular/dist/mobx-angular.d.ts, found version 4, expected 3, resolving symbol TreeModule in /home/node_modules/angular-tree-component/dist/angular-tree-component.d.ts, resolving symbol TreeModule in /home/node_modules/angular-tree-component/dist/angular-tree-component.d.ts`

Because mobx library updated to 4.0?

**Comment by adamkleingit** [comment]
Should be fixed in 7.0.2-beta1 - can you check?

**Comment by hipresario** [comment]
done, great thanks!

**Comment by jainmitesh09** [comment]
@adamkleingit Thank you for the update. This might be a stupid question, but how do we prevent this kind of failure in our app? Meaning how do we suppress the version of dependency modules like in this case with mobx?

**Comment by adamkleingit** [comment]
Well, the mistake was depending on version >=3, instead of ^3.
So now it shouldn't return in the future, as the deps as of 7.0.2 will be:
"lodash": "^4.17.4",
"mobx": "^3.6.2",
"mobx-angular": "^2.1.1"
