### ISSUE TITLE
Error when build with AOT

### ISSUE THREAD

**Issue by Xen3r0** [500tech/angular-tree-component#580]
Hi,

I have a application Angular 5, Angular CLI 1.7.3 with angular-tree-component 7.0.1 and i have a problem with build:

`node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng build --prod --aot=true --sourcemap --vendor-chunk --common-chunk`

> Date: 2018-03-14T10:46:32.074Z                                                       
> Hash: 1a8aec0f2c32a1239d21
> Time: 16952ms
> chunk {scripts} scripts.479b3fdfefacf288bfd3.bundle.js, scripts.479b3fdfefacf288bfd3.bundle.js.map (scripts) 1.58 MB [initial] [rendered]
> chunk {0} styles.91d5058a6fd2a8928b0d.bundle.css, styles.91d5058a6fd2a8928b0d.bundle.css.map (styles) 746 kB [initial] [rendered]
> chunk {1} polyfills.997d8cc03812de50ae67.bundle.js, polyfills.997d8cc03812de50ae67.bundle.js.map (polyfills) 150 bytes [initial] [rendered]
> chunk {2} main.ee32620ecd1edff94184.bundle.js, main.ee32620ecd1edff94184.bundle.js.map (main) 145 bytes [initial] [rendered]
> chunk {3} inline.318b50c57b4eba3d437b.bundle.js, inline.318b50c57b4eba3d437b.bundle.js.map (inline) 859 bytes [entry] [rendered]
> 
> **WARNING in Invalid property name 'rx' at 13452:2. Ignoring.**
> 
> **ERROR in : Illegal state: Could not load the summary for directive MobxAutorunDirective in /home/manuel/public_html/winlassie-ihm/node_modules/mobx-angular/dist/directives/mobx-autorun.directive.d.ts.**

Any idea ?

Thanks

**Comment by adamkleingit** [comment]
Can you try with 7.0.2?

**Comment by adamkleingit** [comment]
Hey, please retry with 7.1.0 and reopen if the problem persists

**Comment by Xen3r0** [comment]
#596 the new issue
