### ISSUE TITLE
The latest version of 7.0.1 and "mobx-angular": "3.0.1" is not compatible

### ISSUE THREAD

**Issue by leihg** [500tech/angular-tree-component#583]
The latest version of 7.0.1 and "mobx-angular": "3.0.1" compatibility is not good, wrong

as follows：
“in Error: Metadata version mismatch for module D:/project/LUNZ-UI/node_modules/mobx-angular/dist/mobx-angular.d.ts, found version 4, expected 3”

**Comment by dzik1331** [comment]
Yes, I have the same.

**Comment by jainmitesh09** [comment]
@leihg use the above mentioned issue, the beta version should help.

**Comment by johaven** [comment]
+1

**Comment by adamkleingit** [comment]
Please check 7.0.2 and reopen if this persists
