### ISSUE TITLE
Version 7.0.2 still complains node_modules/angular-tree-component/dist/angular-tree-component.d.ts, found version 4, expected 3,

### ISSUE THREAD

**Issue by ningkexin** [500tech/angular-tree-component#591]
`
ERROR in Error: Metadata version mismatch for module /Users/ning/www/x/node_modules/angular-tree-component/dist/angular-tree-component.d.ts, found version 4, expected 3, resolving symbol
`

**Comment by mpGitHub** [comment]
Getting the same error as above. 

I had 7.0.1 installed which worked fine, but tried to upgrade to 7.0.2. Now I'm unable to use my repo any longer. I now get the above error when trying to install the previous version that worked of 7.0.1. Did some type of dependency break it? mobx-angular or something else?

I'm using Angular 4+

**Comment by ningkexin** [comment]
@mpGitHub I also used in angular4, but I can't use it after upgrading from 6.1.0 to 7.0.2, downgrading back to 6.1.0 can't be used, other issues are mobx-angular, but I change the package. The mobx-angular 3.6.2 version was added to json, and the installation was still the same error. What is the problem?

**Comment by mpGitHub** [comment]
@ningkexin I was able to get it to work by using the 7.0.2-beta1 version.

Delete 3 folders under node_modules:
* mobx
* mobx-angular
* angular-tree-component

Then install the beta1 version until the official release version is fixed:
* npm install angular-tree-component@7.0.2-beta1

Now everything seems to be working....

**Comment by SoerenAksglaede** [comment]
@mpGitHub Thanks!

**Comment by adamkleingit** [comment]
It seems like a package-lock.json problem.
I hope it will be fixed in 7.1.0

**Comment by adamkleingit** [comment]
Published 7.1.0 - can you verify?

**Comment by adamkleingit** [comment]
If the problem persists in 7.1.0 - please reopen the issue

**Comment by ningkexin** [comment]
@adamkleingit Has been fixed in angular4.x no problem, there is no problem with aot compiler, thank you very much!

**Comment by TheoLechemia** [comment]
I have the same problem on version 8.0.0
