### ISSUE TITLE
7.0.2 MobX <-> Mobx-Angular Version incompatible?

### ISSUE THREAD

**Issue by JanLoebel** [500tech/angular-tree-component#593]
I get the following compile warning when starting an Angular project.

{code}
WARNING in ./node_modules/mobx-angular/dist/utils/mobx-angular-debug.js
223:15-27 "export 'getDebugName' was not found in 'mobx'

WARNING in ./node_modules/mobx-angular/dist/utils/mobx-angular-debug.js
29:28-45 "export 'getDependencyTree' was not found in 'mobx'
{code}

I use version 7.0.2 of the angular-tree-component, which then transitive retrieve:
{code}
"mobx": "3.6.2",
"mobx-angular": "2.2.0"
{code}

Looks like mobx-angular@2.2.0 and mobx@3.6.2 seem to be incompatible? Does anyone else have this problem?

**Comment by enniob** [comment]
@JanLoebel I just updated my code to use the latest version (7.0.2) and its working fine. I did not get any error and I'm using

**Comment by JanLoebel** [comment]
I've tried to remove the "package-lock.json" and node_modules, but nothing worked. I've also checked if I call anything regarding mobx or mobx-angular, but I don't import any of these two components. Any ideas?

{code}
# npm ll mobx mobx-angular
│ ## Modules
└─┬ angular-tree-component@7.0.2
  │ A simple yet powerful tree component for Angular2
  │ git+https://github.com/500tech/angular-tree-component.git
  │ https://github.com/500tech/angular-tree-component
  ├── mobx@3.6.2
  │   Simple, scalable state management.
  │   git+https://github.com/mobxjs/mobx.git
  │   https://mobx.js.org/
  └── mobx-angular@2.2.0
      Angular connector to MobX (2 and above)
      git+https://github.com/mobxjs/mobx-angular.git
      https://github.com/mobxjs/mobx-angular#readme
{code}

**Comment by enniob** [comment]
What version of Angular are you using?
Maybe try uninstalling and installing again angular-tree-component?

**Comment by JanLoebel** [comment]
I'm using Angular 5.2.9. I've already tried to remove and re-added it again. 

In the browser the error looks like this:

<img width="617" alt="asd" src="https://user-images.githubusercontent.com/1765067/37598017-53503f22-2b81-11e8-86e4-9e1258f948a0.png">

**Comment by SoerenAksglaede** [comment]
Same issue here..

**Comment by hilel** [comment]
Same issue with angular 5.2.0

**Comment by enniob** [comment]
@JanLoebel  Sorry about that I had the warnings disabled on my build and I missed that. I do see it now too.

**Comment by toregua** [comment]
Same for me with angular `^5.0.0`

**Comment by mpGitHub** [comment]
I was able to get it to work by using the 7.0.2-beta1 version.
see issue [578](https://github.com/500tech/angular-tree-component/issues/578)

Delete 3 folders under node_modules:
* mobx
* mobx-angular
* angular-tree-component

Then install the beta1 version until the official release version is fixed:
* npm install angular-tree-component@7.0.2-beta1

Now everything seems to be working....

It's odd that the beta1 version works but the official release version does not?!?!?

**Comment by umutcakirbm** [comment]
Same issue with angular 5.2.9

**Comment by chuihinwai** [comment]
For me, I tried adding `"mobx": "4.1.0"` to package.json and ran `npm install`. That fixed the compile and runtime error. You'll get a warning in console saying there are duplicate mobx instances and could cause problems. …And they're right. The tree will not redraw if you update the tree model.

Went with @mpGitHub's steps and it works for me. https://github.com/500tech/angular-tree-component/issues/593#issuecomment-374630509

**Comment by adamkleingit** [comment]
It seems like a package-lock.json problem.
I hope it will be fixed in 7.1.0

**Comment by adamkleingit** [comment]
If the problem persists in 7.1.0 - please reopen the issue

**Comment by WonderJulian** [comment]
After updating to 7.1.0 the warnings (provided by @JanLoebel) still exist.

**Comment by chuihinwai** [comment]
I haven't seen those warnings with 7.1.0. I did do a `rm -rf
./node_modules` before tho. Might be worth a try🤔
