### ISSUE TITLE
tree - component not showing all children and not showing additional nodes

### ISSUE THREAD

**Issue by AndersMygind** [500tech/angular-tree-component#598]
Hi
 "angular-tree-component": "^7.0.2",
FF 59.0.1 (64-bit)
Chrome Version 65.0.3325.181 (Officiel version) (64-bit)

I am trying to show nodes and add further nodes from a service.
So initially I assign values to this.nodes - these do show up except for the children - 'child1' never shows up.
Any ideas what I do wrong with this simple code is appreciated?
Furthermore I try to add a node in the tree ('another node a') and this node never shows up either.

Thanks in advance

`import { Component, OnInit, ViewChild } from '@angular/core';
import { TreeComponent, TreeModel, TreeNode } from 'angular-tree-component';

// Bygget med https://angular2-tree.readme.io/docs
// usage:
@Component({
  selector: 'treeapp',
  template: '<tree-root #tree [nodes]="nodes" [options]="options"></tree-root>'
})
export class TreeAppComponent {
  options = {};
  nodes: any[];
  @ViewChild(TreeComponent) private tree: TreeComponent;

  constructor() {
    this.nodes = [
      {
        id: 1,
        name: 'root1',
        children: [{ id: 2, name: 'child1' }, { id: 3, name: 'child2' }]
      },
      {
        id: 4,
        name: 'root2',
        children: [
          { id: 5, name: 'child2.1' },
          {
            id: 6,
            name: 'child2.2',
            children: [{ id: 7, name: 'subsub' }]
          }
        ]
      }
    ];
    this.nodes.push({ name: 'another node b', children: [{ name: 'child21' }] });

    setTimeout(() => {
      this.nodes.push({ name: 'another node a', children: [{ name: 'child21' }] });
      console.log('nodes', this.nodes);
      this.tree.treeModel.update();
      this.tree.sizeChanged();
    }, 3);
  }
}
`

**Comment by AndersMygind** [comment]
![image](https://user-images.githubusercontent.com/5576607/37957738-ff43154c-31ae-11e8-9890-b73961f409c8.png)

**Comment by adamkleingit** [comment]
Hi,
Please reproduce in the plunkr from the issue template and reopen the issue.
Thanks

**Comment by AndersMygind** [comment]
We used a 7.0.2 which was buggy so we changed to "^5.2.1" and it works,
thank
