### ISSUE TITLE
Enable manually controllable tri-state selection

### ISSUE THREAD

**Issue by jsight** [500tech/angular-tree-component#606]
I have a situation where I have a large checkbox tree with thousands of individual nodes. I want the child nodes to be lazy loaded, but I also want to display a half-check based upon my own state information.

Currently, it seems that this is impossible as this state information is only tracked when the builtin tri-state behavior is enabled.

**Comment by phhbr** [comment]
Did you find a custom solution to this?

**Comment by jsight** [comment]
No, I never found a suitable solution.

**Comment by adamkleingit** [comment]
Hi,
this could be accomplished with custom templates and your own management of the checkbox state.
All the best
