### ISSUE TITLE
icon for each individual node

### ISSUE THREAD

**Issue by hytsoft** [500tech/angular-tree-component#614]
Hello,

I discovered how to set an image for a node using the 'ng-template #treeNodeTemplate' directive
but this only supports 1 image for the entire tree.

I am not talking about the state of a node (open\close), but of a different icon per node.

Is it possible to set each node with  a different image ?

**Comment by ulisesmorenomassachusetts** [comment]
How do you modify the icon for the specific node, to have customized icon?

**Comment by AbhiThakare** [comment]
HI @hytsoft,

Do you wnat show nodes with some Icons or images like below ?

![image](https://user-images.githubusercontent.com/10028004/39477802-4d59aa9c-4d58-11e8-8314-b523257b7072.png)

Thanks
Abhi

**Comment by adamkleingit** [comment]
You can use `let-node` and access the node inside the template

BTW, the fastest way to get an answer is to join our slack channel and post it there:
https://angular-tree-component.herokuapp.com/
You will also get announcements on releases, discussions and new features
Feel free to join
