### ISSUE TITLE
is there a tree like attachment picture? down to up, not rtl

### ISSUE THREAD

**Issue by grubed** [500tech/angular-tree-component#617]
![image](https://user-images.githubusercontent.com/21269645/39235850-a0e15088-48a9-11e8-9b82-01bb2b6578b6.png)

**Comment by adamkleingit** [comment]
Not yet.
But you can join our slack channel and post it there:
https://angular-tree-component.herokuapp.com/
You will also get announcements on releases, discussions and new features
Feel free to join
