### ISSUE TITLE
Horizontal scroll

### ISSUE THREAD

**Issue by Vishnusangam** [500tech/angular-tree-component#620]
I was trying angular-tree-compnent where I get vertical scroll using usevirtualscroll but I am unable to get horizontal scroll as my requirement say to have horizontal scroll as it require more nested nodes as well as lengthy names

**Comment by xkLander** [comment]
Perhaps you can use css to have the horizontal scrolling, same as you can have the vertical one.
https://stackoverflow.com/questions/9925754/css-horizontal-scroll

**Comment by adamkleingit** [comment]
Hi,
The fastest way to get an answer is to join our slack channel and post it there:
https://angular-tree-component.herokuapp.com/
You will also get announcements on releases, discussions and new features
Feel free to join

**Comment by chetanjassal** [comment]
> I was trying angular-tree-compnent where I get vertical scroll using usevirtualscroll but I am unable to get horizontal scroll as my requirement say to have horizontal scroll as it require more nested nodes as well as lengthy names

try this 
tree-viewport{
  overflow-x: auto !important; 
  display: flex !important; 
}

**Comment by LautaroLorenz** [comment]
> > I was trying angular-tree-compnent where I get vertical scroll using usevirtualscroll but I am unable to get horizontal scroll as my requirement say to have horizontal scroll as it require more nested nodes as well as lengthy names
> 
> try this
> tree-viewport{
> overflow-x: auto !important;
> display: flex !important;
> }

works fine, even without !important
