### ISSUE TITLE
What is the best way to update data in nodes with the same id?

### ISSUE THREAD

**Issue by itsmekhanh** [500tech/angular-tree-component#621]
I created a tree where some of the children have the same id. Selecting and deselecting a child from one parent will also update its status under another parent, which is the behavior that I want. Not sure if this was intended by the developers, but it was definitely nice to see it working.

<img width="292" alt="screenshot" src="https://user-images.githubusercontent.com/648384/39380160-74908f0c-4a12-11e8-82b2-d83b81751cf0.png">

However, I also want the capacity values to set to 0 kW whenever a child is deselected. It doesn't seem to set the other children with the same id to 0 kW.

This is the data payload that I'm using to generate the nodes.

```
{
      'name': 'Utility Program Name',
      'id': 'program_01',
      'capacity': 500,
      'unit': 'kW',
      'children': [
        {
          'id': 'group_01',
          'name': 'Group 1',
          'capacity': 200,
          'unit': 'kW',
          'children': [
            {
              'id': 'account_01',
              'name': 'account 01',
              'capacity': 50,
              'unit': 'kW'
            },
            {
              'id': 'account_02',
              'name': 'account 02',
              'capacity': 50,
              'unit': 'kW'
            },
            {
              'id': account_03,
              'name': 'account 03',
              'capacity': 100,
              'unit': 'kW'
            }
          ]
        },
        {
          'id': group_02,
          'name': 'Group 2',
          'capacity': 300,
          'children': [
            {
              'id': 'account_04',
              'name': 'account 04',
              'capacity': 200,
              'unit': 'kW'
            },
            {
              'id': 'account_01',
              'name': 'account 01',
              'capacity': 50,
              'unit': 'kW'
            },
            {
              'id': 'account_02',
              'name': 'account 02',
              'capacity': 50,
              'unit': 'kW'
            }
          ]
        }
      ]
    }
```

Template code
```
 <tree-root #tree [nodes]="nodes" [options]="options" [(state)]="state">
        <ng-template #treeNodeTemplate let-node let-index="index">
          <label>
            <input type="checkbox"
                        (click)="node.mouseAction('checkboxClick', $event); updateCapacity(node)"                
                        [indeterminate]="node.isPartiallySelected"/>
            <span>
              {{node.data.name}} - {{ node.data.capacity }} {{ node.data.unit }}
            </span>      
          </label>
        </ng-template>
</tree-root>
```

Is it possible to extend the behavior on how nodes with same id are updated? I also want to update the parents' capacity values as well whenever their children are updated.

**Comment by adamkleingit** [comment]
Hi,
Using the same ID with the tree will lead to unexpected behaviour.
I suggest you create a unique ID for each node (you can specify another id field in the options).

BTW,
The fastest way to get an answer is to join our slack channel and post it there:
https://angular-tree-component.herokuapp.com/
You will also get announcements on releases, discussions and new features
Feel free to join
