### ISSUE TITLE
'tree-root' is not a known element 

### ISSUE THREAD

**Issue by Chaitanya009** [500tech/angular-tree-component#626]
compiler.js:707 Uncaught Error: Template parse errors:
'tree-root' is not a known element:
1. If 'tree-root' is an Angular component, then verify that it is part of this module.
2. If 'tree-root' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("

  [ERROR ->]<tree-root></tree-root>
"): ng:///PagesModule/ConversationsComponent.html@119:2

I am trying to import tree component in child component I am getting this error. Any idea how to fix?

**Comment by adamkleingit** [comment]
Please link to github / plnkr

**Comment by richardk123** [comment]
fixed by adding TreeModule to app.module.ts imports

**Comment by ansyg** [comment]
> TreeModule
I have the same issue on angular 12,
Imported,error still exists

**Comment by despotgit** [comment]
same for me, @ansyg  on angular 11

**Comment by Harshith-gowda-k** [comment]
> fixed by adding TreeModule to app.module.ts imports

but what if I'm using angular 15 which as standalone components and does not contain app.module.ts
