### ISSUE TITLE
Unable to expand all nodes on init

### ISSUE THREAD

**Issue by Chaitanya009** [500tech/angular-tree-component#628]
export class ConversationBuilderComponent implements OnInit {

  nodes = [];
  @ViewChild('tree') tree: TreeComponent;

  @Component {
  nodes = [...];
  @ViewChild('tree') tree;

  ngAfterViewInit() {
    this.tree.treeModel.expandAll();
  }
}

}

**Comment by AbhiThakare** [comment]
Hi @Chaitanya009,

You can use initialized option 

```html
<tree-root
      #tree
      [nodes]="nodes"
      [options]="customTemplateStringOptions"
      [focused]="true"
      (event)="onEvent($event)"
      (initialized)="onInitialized(tree)"> 

```

```JavaScript
onInitialized(tree) {
    setTimeout(() => {
           tree.treeModel.expandAll();
        });
  }
```
**Note** -  Expand All on init can be expensive for big tree,
Please specify your exact requirement to help you out.

Thanks 
Abhi

**Comment by Chaitanya009** [comment]
`<tree-root #tree [nodes]="nodes" [focused]="true" (initialized)="onInitialized(tree)">`
`  onInitialized(tree) {
    setTimeout(() => {
       tree.treeModel.expandAll();
    });
  }`
I have tried this it didin't work

**Comment by AbhiThakare** [comment]
For me it's working, can you try to expandAll event on button click? and see whether its working or not.

I assume you are loading child asynchronous

**Comment by Chaitanya009** [comment]
I want to expand tree on loading of component

**Comment by Chaitanya009** [comment]
thanks, it did work after setting delay
