### ISSUE TITLE
Document usage of setActiveNode

### ISSUE THREAD

**Issue by ferdis** [500tech/angular-tree-component#637]
The `setActiveNode` method of `TreeModel` is not documented. 

It's located here: https://github.com/500tech/angular-tree-component/blob/master/lib/models/tree.model.ts#L261

**Comment by adamkleingit** [comment]
Hi,
the intention was for users to use `treeNode.setIsActive` instead.

**Comment by adamkleingit** [comment]
BTW,
I recently opened a slack channel for the library's users community.
I think it will be a good place for the community to discuss different ways of implementation, to ask for feature requests, collaborate on PRs, and hear about bugfixes and releases.

I invite you to join:
https://angular-tree-component.herokuapp.com/
