### ISSUE TITLE
Hiding the expand icon if there are no children

### ISSUE THREAD

**Issue by yaniv1988** [500tech/angular-tree-component#641]
I am making a REST call on clicking expand icon. If there are no results meaning it has no children, then I would like to hide the expand icon. I am using angular tree component v 7.1.0.

Currently, I have handled to not show any child nodes. However the icon remains visible.

Any help is appreciated.

**Comment by adamkleingit** [comment]
You can change the `hasChildren` property to false

**Comment by panoschal** [comment]
The `hasChildren` property seems to be read-only. Currently, I can't reassign it.
`TypeError: Cannot set property hasChildren of [object Object] which has only a getter`

**Comment by ViplavRaja-GIT** [comment]
node.data.hasChildren = false;

**Comment by sagarvaishnav** [comment]
> node.data.hasChildren = false;
This seems not working, It's still showing the expand icon if children nodes are hidden :(

**Comment by Cloud9Clone** [comment]
I confirm the @sagarvaishnav statement. After I successfully fatch the children and attach `hasChildren` attribute to each child, the arrow icon still gets rendered, although `hasChildren: false`. 

One way of hiding the icon is by not passing the children array i.e. no children property. However, if you attempt to add new children to that node, then you need first to attach `children` attribute and then push the new items. It's not that it is difficult, it just can be done with the library.
