### ISSUE TITLE
Add note about id field in 2-way binding documentation

### ISSUE THREAD

**Issue by janhurst** [500tech/angular-tree-component#642]
Hi,

I would like to suggest adding a note in the 2-way binding to state documentation about the importance of the node having an id field in the page located at https://angular2-tree.readme.io/docs/save-restore

I beat my head on this for quite a while until I finally twigged to it from the note mentioned here at
https://angular2-tree.readme.io/docs/common-issues. Naturally "common issues" was the last place I actually looked :)

Regards,
Jan

**Comment by adamkleingit** [comment]
Accepted and fixed. Thanks!
