### ISSUE TITLE
right mouse function ?

### ISSUE THREAD

**Issue by leihg** [500tech/angular-tree-component#646]
right mouse button to add or edit  child node function?

**Comment by adamkleingit** [comment]
You can do it using `actionMapping.mouse.contextMenu`:
https://angular2-tree.readme.io/docs/action-mapping

**Comment by arcdream** [comment]
adamkleingit
could you please provide a small sample to create a context menu on tree node. thanks a lot

**Comment by adamkleingit** [comment]
Hi,
I never tried to do that.
Maybe ask in the slack channel
