### ISSUE TITLE
Unable to display data using async

### ISSUE THREAD

**Issue by NiranjanAbb** [500tech/angular-tree-component#648]
Hi I am trying to display tree structure using some data. Below is my code.

`public string transformer(data:any){
    let results =  JSON.parse('{"userid":"e75792f8-cfea-460e-aca2-07a778c92a7c","tenantid":"00000000-0000-0000-0000-000000000000","username":"karthik","emailaddress":"john@krsars.onmicrosoft.com","isallowed":false,"userroles":[{"userroleid":"b81e63d1-09da-4aa0-af69-0f086ddb20b4","userid":"e75792f8-cfea-460e-aca2-07a778c92a7c","roleid":"85d2f668-f523-4b64-b177-b1a78db74234","tenantappid":1,"validfrom":"2018-01-24T00:00:00","validto":"2018-01-24T00:00:00","isactive":true}]}');
    const nodes = [];
    for (const key in results) {
      if (results[key] instanceof Array) {
        const containerTyp2 = {name: '', hasChildren: false,};

        containerTyp2.name = key;
        containerTyp2.hasChildren = true;

        nodes.push(containerTyp2);
     } else {
        const object = {name: ''};
        const containerTyp1 = {name: '', children: []};
        object.name = key;
        containerTyp1.name = key;
        containerTyp1.children.push(object);
        
        nodes.push(containerTyp1);
    }
   
  }
  console.log(nodes);
}
}`

When i compared to the data given in example, it is  same as you have provided. But with above data tree structure is not displaying nor giving any errors.

**Comment by ismailsaleekh** [comment]
i faced the issue when i have to add some node dynamicly, so it just does nt rendering new values, the solution i found after looking the source codes, u have to inject treeComponent into your component by
```@ViewChild(TreeComponent) treeComponentRef: TreeComponent;```
then u should reset treeModel property in TreeComponent, by doing 
```    const events = pick(this.treeComponentRef, this.treeComponentRef.treeModel.eventNames);
    this.treeComponentRef.treeModel.setData({ nodes: (your nodes here), options: (your options here), events });```

 // pick is lodash function

hope it will help somebod)

**Comment by adamkleingit** [comment]
@NiranjanAbb Can you reproduce in Stackblitz? https://stackblitz.com/edit/angular-wxansn
@ismailsaleekh Did you follow this guide? https://angular2-tree.readme.io/docs/changing-the-tree
