### ISSUE TITLE
v7.1.0 browser compatability - Not working in IE 11

### ISSUE THREAD

**Issue by misd92** [500tech/angular-tree-component#654]
Hi,
I am using angular-tree-component v7.1.0 with angular 4. It's working fine in Chrome, Edge, Firefox, Opera and Safari. I want it to make it work in IE 11. Is there any possibility that it would run on IE 11.

Thanks for the support

**Comment by misd92** [comment]
Hi,
I am using angular-tree-component v7.1.0 with angular 4. It's working fine in Chrome, Edge, Firefox, Opera and Safari. I want it to make it work in IE 11. Is there any possibility that it would run on IE 11.

Thanks for the support

**Comment by phhbr** [comment]
Outdated. Works in IE11 nowadays
