### ISSUE TITLE
No provider for TreeDraggedElement!

### ISSUE THREAD

**Issue by zxjQAZ** [500tech/angular-tree-component#659]
everything goes as document say,however the error below happen!

Error: StaticInjectorError(AppModule)[TreeComponent -> TreeDraggedElement]: 
  StaticInjectorError(Platform: core)[TreeComponent -> TreeDraggedElement]: 
    NullInjectorError: No provider for TreeDraggedElement!

**Comment by waseemdev** [comment]
You should use forRoot() method to import the module:
```ts
@NgModule({
    imports: [ TreeModule.forRoot(), ...]
});

**Comment by zxjQAZ** [comment]
yes, it's ok thank you a lot
