### ISSUE TITLE
how programatically set select or deselect node .

### ISSUE THREAD

**Issue by Rjitendra** [500tech/angular-tree-component#665]
In my case i am using version "angular-tree-component": "^8.0.0". My scenario like 
when update some page my selection on treeview should be  goes out.

somewhere update page component, i call refreshTreeNodes();

here is my sample code

 <tree-root [nodes]="docAbbr"  [options]="options" (activate)="documentDetail($event)" #tree (initialized)="onInitialized(tree)"></tree-root>

export class DocumentationComponent implements OnInit, AfterViewInit, OnDestroy {
 options: ITreeOptions = {
    idField: 'Id',
    displayField: 'name',
    childrenField: 'childDocuments',
    nodeHeight: 23,
  };
 @ViewChild('tree') tree;

 ngOnInit() {
    this.subscription = this.emitService.getDocumentationEmitter()
      .subscribe(item => this.refreshTreeNodes()
      );
  }
 refreshTreeNodes() {
    this.refreshTree();
    this.getDocumentationAbbreviated();

  }
 getDocumentationAbbreviated() {
    this.spinnerService.show();
    this.service.getDocumentationAbbreviated().subscribe(
      (data: any) => {
        this.setMinHeightForSideBar();
        this.docAbbr = null;
        this.docAbbr = data;
       // this.tree.treeModel.setFocusedNode(null);

        this.spinnerService.hide();
      }, error => {
      
      });
  }

  refreshTree() {
   

  this.tree.treeModel.nodeActivate = null;
  this.tree.treeModel.select = false;
  this.tree.treeModel.focused = false;
  this.tree.treeModel.setIsSelected(false);
}
}

Thanks,
Jitendra

**Comment by swarnim89** [comment]
if you are referring select/deselect using check boxes then please use SetisSelected property of node.
Example:  tree.treeModel.getNodeBy((node) => node.data.name === value.name).setIsSelected(true);
will checked the node with given name

**Comment by phhbr** [comment]
Thanks @swarnim89 for providing the solution.

If the issue is still not resolved, open the issue again @Rjitendra
