### ISSUE TITLE
Prevent Duplicate Entry Node in already existing Tree nodes

### ISSUE THREAD

**Issue by Prashdev7** [500tech/angular-tree-component#673]
How to prevent the duplicate entries in Tree node?
I have followed the https://angular2-tree.readme.io article for implementing the Custom Template tree view in my project its working fine, but there is an requirement where i should prevent the duplicate node in the Tree Node when we drag and drop the already exist ones.
Can we prevent that ??
<img width="617" alt="duplicate" src="https://user-images.githubusercontent.com/40144234/45159574-bfa9f500-b204-11e8-8170-fd05e1d04697.PNG">

Please help me in solving this issue!!

**Comment by phhbr** [comment]
Is it a duplicate by name only? Then you cannot prevent it.
If the data has the same id aswell, it should be prevented.

**Comment by adamkleingit** [comment]
You can override the `allowDrop` option.
Or you can override `options.actionMapping.mouse.drop`, then check if it's OK to move/copy, and if so, call: `tree.moveNode(from, to)` or `tree.copyNode(from, to)`.

**Comment by mrc1995** [comment]
I have the same problem, you know other solutions ?
