### ISSUE TITLE
Custom expand/collapse icons

### ISSUE THREAD

**Issue by musienkoyuriy** [500tech/angular-tree-component#674]
I need an ability to customize expand/collapse icon, for example, to "plus/minus". Is there this functionality? If no, do you plan to implement it? Also, tricks to realize it will be useful

**Comment by Krishna47** [comment]
I also wanted the same thing.
I achieved this by CSS.
In my global css (styles.css), I overrode class like below:

tree-node-content::before {
  content: "\f07b"
}

html:
 <tree-root [nodes]="nodes" [focused]="true" (activate)="handleTreeEvents($event)" [options]="options" **class="fas"**></tree-root>

I am using font-awesome 5. 
The icon can be implemented by adding class="fas" to tree-root in your html.
Check the Unicode in font-awesome page and add it like above. 

Little tweaking is needed though.

**Comment by mark53** [comment]
You can use custom template for this
[https://angular2-tree.readme.io/docs/templates#treenodewrappertemplate](url)

Then change `tree-node-expander` to your custom element.
You can use `node.toggleExpanded()`to toggle state and `node?.isExpanded` to determine what icon should be displayed.

**Comment by phhbr** [comment]
Issue closed by provided solutions. if this issue still remain, you may open this again.

**Comment by drullo** [comment]
I wish the documentation were more clear and complete.  I had this same question and I went to the documentation first.  I did read the Templates page, but it's not clear (because it's not documented) that this (replacing the expander) can be done.  The information posted above by @mark53 helped me figure that out, but it should be documented appropriately.

**Comment by sagunpandey** [comment]
@drullo I still can't customize expander icon. I am trying to change tree-node-wrapper.

>         <tree-root #tree [nodes]="tagTree" [options]="treeOptions">
>           <ng-template #treeNodeFullTemplate let-node let-index="index" let-templates="templates">
>             <div
>               [class]="node.getClass()"
>               [class.tree-node]="true"
>               [class.tree-node-expanded]="node.isExpanded && node.hasChildren"
>               [class.tree-conode-collapsed]="node.isCollapsed && node.hasChildren"
>               [class.tree-node-leaf]="node.isLeaf"
>               [class.tree-node-active]="node.isActive"
>               [class.tree-node-focused]="node.isFocused">
>               <tree-node-wrapper [node]="node" [index]="index" [templates]="templates"></tree-node-wrapper>
>               <tree-node-children [node]="node" [templates]="templates"></tree-node-children>
>             </div>
>           </ng-template>
>           <ng-template #treeNodeWrapperTemplate let-node let-index="index" let-templates="templates">
>             <div class="node-wrapper" [style.padding-left]="node.getNodePadding()">
>               <tree-node-expander [node]="node">
>                 <div>
>                   <fa-icon *ngIf="node?.isCollapsed" [icon]="['fas', 'plus-square']"></fa-icon>
>                   <fa-icon *ngIf="node?.isExpanded" [icon]="['fas', 'minus-square']"></fa-icon>
>                 </div>
>               </tree-node-expander>
>               <div class="node-content-wrapper"
>                    [class.node-content-wrapper-active]="node.isActive"
>                    [class.node-content-wrapper-focused]="node.isFocused"
>                    (click)="node.mouseAction('click', $event)"
>                    (dblclick)="node.mouseAction('dblClick', $event)"
>                    (contextmenu)="node.mouseAction('contextMenu', $event)"
>                    (treeDrop)="node.onDrop($event)"
>                    [treeAllowDrop]="node.allowDrop"
>                    [treeDrag]="node"
>                    [treeDragEnabled]="node.allowDrag()">
> 
>                 <tree-node-content [node]="node" [index]="index" [template]="treeNodeTemplate"></tree-node-content>
>               </div>
>             </div>
>           </ng-template>
>           <ng-template #treeNodeTemplate let-node let-index="index">
>             <div>
>               <span> {{ node.data.tagName }}</span>
>             </div>
>           </ng-template>
>         </tree-root>

**Comment by sagunpandey** [comment]
I have figured it out. Here my updated treeNodeWrapperTemplate.

          <ng-template #treeNodeWrapperTemplate let-node let-index="index" let-templates="templates">
            <div style="display: flex; align-items: center;" class="node-wrapper" [style.padding-left]="node.getNodePadding()">
              <div style="color: #6C757D;" (click)="node.toggleExpanded()" *ngIf="node?.data?.children?.length > 0">
                <fa-icon *ngIf="node?.isCollapsed" [icon]="['fas', 'plus-square']"></fa-icon>
                <fa-icon *ngIf="node?.isExpanded" [icon]="['fas', 'minus-square']"></fa-icon>
              </div>
              <div class="node-content-wrapper"
                   [class.node-content-wrapper-active]="node.isActive"
                   [class.node-content-wrapper-focused]="node.isFocused"
                   (click)="node.mouseAction('click', $event)"
                   (dblclick)="node.mouseAction('dblClick', $event)"
                   (contextmenu)="node.mouseAction('contextMenu', $event)"
                   (treeDrop)="node.onDrop($event)"
                   [treeAllowDrop]="node.allowDrop"
                   [treeDrag]="node"
                   [treeDragEnabled]="node.allowDrag()">

                <tree-node-content [node]="node" [index]="index" [template]="treeNodeTemplate"></tree-node-content>
              </div>
            </div>
          </ng-template>

**Comment by westongillette** [comment]
Is there a way to do this while still using `#treeNodeFullTemplate`?

The issue I'm having is that I'm using the full template for the tree display, but this override doesn't include `<tree-node-expander>` like it does in `#treeNodeWrapperTemplate`
