### ISSUE TITLE
How to customize the checkbox styles

### ISSUE THREAD

**Issue by shaukath** [500tech/angular-tree-component#678]
I tried in many ways but except width and height nothing is added.
Please help me on this issue.

Thank you !

**Comment by phhbr** [comment]
tree-node-checkbox {
    display: inline-block;
    width: 22px;
    height: 21px;
    position: relative;
    margin: 2px 0 0 0;
    vertical-align: middle;
}

input[type=checkbox] {
    border: 1px solid black;
    outline: none;
    margin: 0;
    -webkit-appearance: initial;
    width: 16px;
    height: 16px;
    position: absolute;
    color: white;
    cursor: pointer;

    &:disabled {
        border-color: black;
        opacity: 1.0;
        cursor: default;
    }
    &:focus {
        border-color: black;
    }
}

input[type=checkbox]:checked:after {
    /* Heres your symbol replacement - this is a trick in our special code. */
    content: "\E9CD";
    font-size: 16px;
    font-family: iwp;
    /* The following positions my tick in the center,
     * but you could just overlay the entire box
     * with a full after element with a background if you want to */
    position: absolute;
    left: 50%;
    top: 50%;
    -webkit-transform: translate(-50%, -50%);
    -moz-transform: translate(-50%, -50%);
    -ms-transform: translate(-50%, -50%);
    transform: translate(-50%, -50%);
}

input[type=checkbox]:indeterminate:after {
    /* Heres your symbol replacement - this is a trick in our special code. */
    content: "\2022";
    color: transparent;
    background-color: black;
    width: 50%;
    height: 50%;
    font-family: iwp;
    /* The following positions my tick in the center,
     * but you could just overlay the entire box
     * with a full after element with a background if you want to */
    position: absolute;
    left: 50%;
    top: 50%;
    -webkit-transform: translate(-50%, -50%);
    -moz-transform: translate(-50%, -50%);
    -ms-transform: translate(-50%, -50%);
    transform: translate(-50%, -50%);
}

**Comment by adamkleingit** [comment]
Hope it helps
