### ISSUE TITLE
Function calls are not supported in decorators but 'TreeModule' was called.

### ISSUE THREAD

**Issue by renatovanquish** [500tech/angular-tree-component#680]
This error occurs when I use with ng-packagr in angular 6 library.

**Comment by phhbr** [comment]
Can you provide additional information? Which ng-packagr, angular-cli, angular-tree-component versions?

Works with ng-packagr@4.7.0, @angular/cli@6.1.5 and angular-tree-component@8.2.0 over here..

If this issue still remains, don't hesitate to open again.
