### ISSUE TITLE
Mutliple check for Angular Tree Filter

### ISSUE THREAD

**Issue by RevathiSam** [500tech/angular-tree-component#681]
Hi,

I am trying to filter nodes by name and dataTable at the same time. Below code is using only datatable.

 this.modeltree.treeModel.filterNodes((node) => {
         return node.data.dataTable.includes(val);
         }); 

I would like to do filter for node.data.name while doing filter. Kindly help on this.

**Comment by phhbr** [comment]
If you still have the issue, could you provide further information and open the issue again? I don't know what's going on and it sounds like a functional issue, not something related to ATC.
