### ISSUE TITLE
How to update input to the tree ??? like currently i am giving input [nodes]="node" , but now i want to change input data and update tree

### ISSUE THREAD

**Issue by hetalbaradiya** [500tech/angular-tree-component#682]
PLEASE READ CAREFULLY!

# Use the Slack Channel
The fastest way to get an answer is via the slack channel:
https://angular-tree-component.herokuapp.com/

You will also get updates on releases, bugfixes and other announcements.

# Github Issue
Please look for an answer in the docs before submitting an issue:
angular2-tree.readme.io.

In case you are reporting a bug, or requesting help, please reproduce it in a GIT repo or fork this online template:
https://plnkr.co/edit/IU8cKYHL7h2YeFMdcAzE?p=preview

If you are unable to reproduce, please:
- paste your package.json
- say which browser you are using
- paste your nodes and options and whatever code your feel will help reproduce the error

Thank you and happy programming

**Comment by pk** [comment]
Just change the nodes property in your component.

See documentation section on this: https://angular2-tree.readme.io/docs/changing-the-tree

**Comment by phhbr** [comment]
If you still need further assistance, don't hesitate to open the issue again.

Thanks @pk for providing the solution
