### ISSUE TITLE
Language support ( async loading)

### ISSUE THREAD

**Issue by venkydeshmukh** [500tech/angular-tree-component#684]
I am using angular tree component and it works perfectly for me. 
Thanks for great library!!
However, there is small issue.
I am using async data to load the tree nodes. But tree shows "loading.." label (always in English). Is there a possibility to use internationalisation for this message? my users will be from Netherlands, So I would like to show "Laden..." and not "Loading.."

**Comment by DianaSellarova** [comment]
Hello @500tech-user @adamkleingit i would like to work on this issue if possible and provide you a pull request when it will be finished as i would benefit from it as well :).

**Comment by adamkleingit** [comment]
Hi @venkydeshmukh 
You can use a custom template for the loading label:
https://angular2-tree.readme.io/docs/templates#loadingtemplate

@DianaSellarova - thanks! What did you have in mind? I'm tagging @500tech/angular-tree-maintainers to get their opinion as well

**Comment by venkydeshmukh** [comment]
> Hi @venkydeshmukh
> You can use a custom template for the loading label:
> https://angular2-tree.readme.io/docs/templates#loadingtemplate
> 
> @DianaSellarova - thanks! What did you have in mind? I'm tagging @500tech/angular-tree-maintainers to get their opinion as well

Hi Adam, My bad.. I did not see this part of the documentation. Thanks a lot.

**Comment by adamkleingit** [comment]
@DianaSellarova you can also try to solve the build problem, find out why it fails in CI/CD - that would be fantastic
