### ISSUE TITLE
Custom nested field?

### ISSUE THREAD

**Issue by pablochud** [500tech/angular-tree-component#685]
Is it possible to set custom field name for nested second level? eg for 'books'?
 ```
nodes = [
    {
      _id: '1',
      title: 'root1',
      nodes: [
                   { _id: '3', title: 'child1', books: []},
                   { _id: '3', title: 'child1', books: [
                                              { subtitle: ' Noe', nr: 2 }
                                             ]},
]
    },
    {
      _id: '2',
      title: 'root2'
    }
  ];

  options: ITreeOptions = {
    idField: '_id',
    displayField: 'title',
    childrenField: 'nodes'
  };

```

**Comment by phhbr** [comment]
depending on the use case, you can store additional information on the 'data'-field of the ITreeNode, or go deeper another level.

Deeper:

nodes = [
   {
     _id: '1',
     title: 'root1',
     nodes: [
                  { _id: '3', title: 'child1', nodes: []},
                  { _id: '3', title: 'child1', nodes: [ {
                      _id: '4', title: ' Noe', nr: 2
                      }
                  }
]

If you have any further questions, don't hesitate to open the issue again
