### ISSUE TITLE
filterNodes not work correctly

### ISSUE THREAD

**Issue by Mehranh** [500tech/angular-tree-component#687]
Hi 
Please check your filterNodes method.
It doesn't work correctly.
ex: Children is not disable but parent is disable!

Can you fix it?
thanks

**Comment by gkn06** [comment]
I am also facing this issue. Please help

**Comment by adamkleingit** [comment]
Hi,
Here it works as expected:
https://angular2-tree.readme.io/docs/filtering

can you please reproduce in the StackBlitz link from the issue template and re-open the issue?
Thanks
