### ISSUE TITLE
Angular 7 support

### ISSUE THREAD

**Issue by Maximaximum** [500tech/angular-tree-component#689]
The docs say that this library only support Angular version up to v6. Is there going to be a new version with angular 7 support?

**Comment by azulay7** [comment]
@adamkleingit not working after ng-update to angular 7.0.4

**Comment by Kasilingam1230** [comment]
I too facing the same issue, if anyone fix it then it will be very helpful for me. Need a quick attention please.

**Comment by azulay7** [comment]
@adamkliengit thank you for your answer. but Im just a user. I dont know the code enough to make PR.

**Comment by adamkleingit** [comment]
@azulay7 every user is a potential contributor in open source.
If anyone wants to take this one it will be great

**Comment by Melmoth-the-Wanderer** [comment]
Works fine for me with angular 7.1.0
Is there anything in particular that does not work or throws an error?
@azulay7 could you update ng to 7.1.0 and see if the problem persist?

**Comment by adamkleingit** [comment]
I'm closing this, if there is a more specific error please update

**Comment by ramuda** [comment]
currently using angular7 and angular tree component 8.2.0 If I push a treenode in existing tree and try calling update. It hangs on loading message.

**Comment by adamkleingit** [comment]
Can you reproduce in Stackblitz:
https://stackblitz.com/edit/angular-wxansn
