### ISSUE TITLE
Package version 8.0.2 is published on npm with a bug

### ISSUE THREAD

**Issue by michalvankodev** [500tech/angular-tree-component#698]
Hi guys,
There is published package with version 8.0.2 which is causing ExpressionChangedAfterItHasBeenCheckedError with 2-way binded state.

I had to specify concrete version 8.0.1 to avoid this issue. Unfortunetaly I haven't found version 8.0.2 mentioned in this repo.

**Comment by adamkleingit** [comment]
Fixed and published in 8.0.3. Can you try?

**Comment by hbaron12** [comment]
Hi,

Happens to me also in version 8.4.0.
