### ISSUE TITLE
Dragover delay

### ISSUE THREAD

**Issue by KristijanJovanovski** [500tech/angular-tree-component#700]
I am experiencing a performance hit during the drag and drop operation. After some profiling with dev tools, it turned out to be due to layout thrashing. More precisely the adding and removing of is-dragging-over class on dragEnter and dragLeave respectively (this is implemented in the TreeDropDirective). 

For the basic usage it is not noticeable. This seems to be an edge case. To reproduce it, the page where the tree is located should contain multiple components. While repeatedly dragging over the tree nodes a delay happens (noticeable by observing the style change from is-dragging-over class).

**Comment by KristijanJovanovski** [comment]
Created PR #701 fixing this issue.
@500tech/teams/angular-tree-maintainers Could someone please review this?

**Comment by adamkleingit** [comment]
Published in 8.2.0
