### ISSUE TITLE
Nodes of tree model are incorrectly updated (strange begavior) after a new node added

### ISSUE THREAD

**Issue by DenisSemionov** [500tech/angular-tree-component#702]
After I add a new node to the tree, and printing `console.dir(this.tree.treeModel)` there IS a new node, but if I print `this.treeComponent.treeModel.nodes` there IS NO new node and I'm frustrated about that, due to that bug I cannot use **getNodeById** on new node.

![image](https://user-images.githubusercontent.com/32300784/51305358-4a1c2400-1a43-11e9-81d4-338d608af255.png)

![image](https://user-images.githubusercontent.com/32300784/51305448-8e0f2900-1a43-11e9-9273-f30884d90ede.png)

If you are unable to reproduce, please:

using:
```
        @angular/animations": "^7.2.0",
        "@angular/cdk": "^7.2.1",
        "@angular/common": "^7.2.0",
        "@angular/compiler": "^7.2.0",
        "@angular/core": "^7.2.0",
        "@angular/flex-layout": "7.0.0-beta.23",
        "@angular/forms": "^7.2.0",
        "@angular/material": "^7.2.1",
        "@angular/platform-browser": "^7.2.0",
        "@angular/platform-browser-dynamic": "^7.2.0",
        "@angular/router": "^7.2.0",
        "@angularclass/hmr": "^2.1.3",
        "@ngrx/core": "^1.2.0",
        "@ngrx/effects": "^7.0.0",
        "@ngrx/entity": "^7.0.0",
        "@ngrx/router-store": "^7.0.0",
        "@ngrx/store": "^7.0.0",
        "@ngx-translate/core": "^11.0.1",
        "@ngx-translate/http-loader": "^4.0.0", 
        "angular-tree-component": "^8.2.0",
```
- Using google chrome  browser (should not matter in that case)

**Comment by adamkleingit** [comment]
Hi, please reproduce using stackblitz:
https://stackblitz.com/edit/angular-wxansn?file=src%2Fapp%2Fapp.component.ts

**Comment by DenisSemionov** [comment]
Actually, now I tried to reproduce it and it seems like in my app problem are caused due to redux usage, so I will have to deal with that myself. In stackblitz without redux it's working as expected.

My fault, non-existing issue.
