### ISSUE TITLE
how to limit to 1 children

### ISSUE THREAD

**Issue by sinthujanara** [500tech/angular-tree-component#706]
PLEASE READ CAREFULLY!

# Reproduce
Please reproduce here if reporting a bug, or requesting help:
https://stackblitz.com/edit/angular-wxansn

# Additional Info
- paste your package.json
- which browser
- paste your code

# Use the Slack Channel
The fastest way to get an answer is via the slack channel:
https://angular-tree-component.herokuapp.com/

You will also get updates on releases, bugfixes and other announcements.

# Search Docs First
Please look for an answer in the docs before submitting an issue:
angular2-tree.readme.io.

**Comment by sarajung** [comment]
options = {
    allowDrag: (node) => node.isLeaf,
    allowDrop: (element, to)=> {
      // return true / false based on element, to.parent, to.index. e.g.
      return !to.parent.hasChildren;
    },
    
  };

**Comment by adamkleingit** [comment]
Please provide more info if you want any help
