### ISSUE TITLE
how to set different id name instead of id in nodes

### ISSUE THREAD

**Issue by sinthujanara** [500tech/angular-tree-component#707]
PLEASE READ CAREFULLY!

# Reproduce
Please reproduce here if reporting a bug, or requesting help:
https://stackblitz.com/edit/angular-wxansn

# Additional Info
- paste your package.json
- which browser
- paste your code

# Use the Slack Channel
The fastest way to get an answer is via the slack channel:
https://angular-tree-component.herokuapp.com/

You will also get updates on releases, bugfixes and other announcements.

# Search Docs First
Please look for an answer in the docs before submitting an issue:
angular2-tree.readme.io.

**Comment by adamkleingit** [comment]
Hi,
please provide more info. You can use idField in options if that's what you are referring to
