### ISSUE TITLE
IE11 not working on demo site / polyfill broken

### ISSUE THREAD

**Issue by gorille** [500tech/angular-tree-component#710]
Hi all, 
it seems that we have a regression with IE11 on the demo page here:
https://angular2-tree.readme.io/

I do get an error that the object does not have property or method "fill", as provided in the array polyfill.

it is the same issue as #567 or #272: the polyfill needs to be uncommented:
https://github.com/500tech/angular-tree-component/issues/567#issuecomment-379474295

**Comment by phhbr** [comment]
as documented in here: https://angular2-tree.readme.io/docs/ie11

**Comment by adamkleingit** [comment]
I'll update the example and comment out the polyfills so that the doc site works on IE11
