### ISSUE TITLE
How to move nodes of a tree into another tree

### ISSUE THREAD

**Issue by MohitSaraswat** [500tech/angular-tree-component#712]
I have a scenario in which I have two panels, the left pane has already created tree and the right pane is empty. I want to achieve - if i click on a button then the selected nodes get deleted from left pane and creates the same kind of tree structure on right pane and vice versa if i remove some nodes from right pane then it forms an organized tree structure again on left panel.

Please help me with this. Thanks in advance!

PLEASE READ CAREFULLY!

# Reproduce
Please reproduce here if reporting a bug, or requesting help:
https://stackblitz.com/edit/angular-wxansn

# Additional Info
- paste your package.json
- which browser
- paste your code

# Use the Slack Channel
The fastest way to get an answer is via the slack channel:
https://angular-tree-component.herokuapp.com/

You will also get updates on releases, bugfixes and other announcements.

# Search Docs First
Please look for an answer in the docs before submitting an issue:
angular2-tree.readme.io.

**Comment by adamkleingit** [comment]
https://angular2-tree.readme.io/docs/drag-drop#drag-and-drop-between-trees
