### ISSUE TITLE
angular-tree-component is not working with new angular (ivy)

### ISSUE THREAD

**Issue by colas74** [500tech/angular-tree-component#733]
# Reproduce
On green project I simply add "npm i angular-tree-component" and import it in ngmodule of `app.module.ts` file  like `TreeModule.forRoot()`

See this repro project [hello-ivy.zip](https://github.com/500tech/angular-tree-component/files/3201846/hello-ivy.zip)

# Additional Info
1. unzip 
2. npm install 
3. ng s => ERROR

**Comment by matte00** [comment]
Check it #721

**Comment by adamkleingit** [comment]
Closing duplicate
