### ISSUE TITLE
Is it possible to make a node selected when clicking that checkbox if the node is partially selected?

### ISSUE THREAD

**Issue by niloy369** [500tech/angular-tree-component#737]
In my current project we need to make a node selected while clicking that node if the node is partially selected. 
Currently it is deselecting the clicked partially selected node. I need to make it selected. 
How can I do that?

**Comment by philipphutterer** [comment]
Have a look at [ActionMapping](https://angular2-tree.readme.io/docs/action-mapping).
<details>
<summary>See code</summary>

```
actionMapping: IActionMapping = {
  mouse: {
    checkboxClick: (tree, node, $event) => {
      if (node.isPartiallySelected) {
        TREE_ACTIONS.DESELECT(tree, node, $event);
        return TREE_ACTIONS.SELECT(tree, node, $event);
      } else {
        return TREE_ACTIONS.TOGGLE_SELECTED(tree, node, $event);
      }
    }
  }
};

options: ITreeOptions = {
  useCheckbox: true,
  actionMapping: this.actionMapping
};
```

___
</details>

For big trees you maybe should consider revising the DESELECT which is there only for UI purposes.

**Comment by niloy369** [comment]
Thanks @philipphutterer , that worked.
