### ISSUE TITLE
Error on delete a new node with virtual scroll

### ISSUE THREAD

**Issue by reichamir** [500tech/angular-tree-component#772]
Hi,

First of all the Angular tree component is great!

I created a project on stackBlitz that reproduce the bug 
https://stackblitz.com/edit/angular-yu3k8a

# Scenario
1. Click "Add node". The method adds the node to the end of the list.
2. Scroll to bottom.
3. Click "Delete node". The method delete the new node.
Repreduce site: https://stackblitz.com/edit/angular-yu3k8a

# Tree configuration
{ useVirtualScroll: true }

# Exception info
Exception: "[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@1339]' TypeError: Cannot read property 'position' of null"
File: tree-node-collection.component.js
Code line: var relativePosition = firstNode ? firstNode.position - firstNode.parent.position - firstNode.parent.getSelfHeight() : 0;

Many thanks for your help!
Amir.

**Comment by adamkleingit** [comment]
@reichamir 
Thanks for the detailed issue! That's a great example of how an issue can be filed :)

Fixed and published in 8.5.2
