### ISSUE TITLE
angular-tree-component not working in IE11

### ISSUE THREAD

**Issue by sumitpatel123** [500tech/angular-tree-component#775]
I have used angular-tree-component in my project.It does work in Chrome but not in IE11. 

It gives following error.

![image](https://user-images.githubusercontent.com/6596429/70226950-c0b73280-1777-11ea-9e4c-a2ea4f4cc919.png)

package-lock.json

![image](https://user-images.githubusercontent.com/6596429/70227080-f8be7580-1777-11ea-91c0-3ed479f19fa0.png)

**Comment by Divya-Kothavari** [comment]
Hi ,

I am also facing same issue. Any workaround / solution for it ?

**Comment by IhorShmidt** [comment]
Hi, also have the same issue, any ideas?

**Comment by hugoj-goncalves** [comment]
mobx 5 doesn't support I.E. 11, it got updated here https://github.com/500tech/angular-tree-component/commit/0c336fdaf299ed9471d7cdd75ffbd1e2a86b5550
I forked to downgrade and we're using this version -> https://github.com/500tech/angular-tree-component/pull/776

maybe you can workaround with [npm-shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap)

**Comment by IhorShmidt** [comment]
Switched to version 8.0.0 and everything is fine

**Comment by bartromgens** [comment]
This is fixed in https://github.com/500tech/angular-tree-component/pull/776, but not yet released.

Downgrading to 8.4.1 worked for me.

**Comment by foxjazz** [comment]
thank you! that worked for me also 8.4.1

**Comment by adamkleingit** [comment]
The MobX downgrade was merged and should fix this.
Please use angular-tree-component 8.5.4
