### ISSUE TITLE
Missed TREE_ACTIONS.TOGGLE_SELECTED_MULTI

### ISSUE THREAD

**Issue by chendachao** [500tech/angular-tree-component#778]
I can't find the `TREE_ACTIONS.TOGGLE_SELECTED_MULTI`, if it was removed by intention, then what's the alternative?

***Version***:
```
angular: 8.2.11
angular-tree-component: 8.5.2
```

**Comment by adamkleingit** [comment]
Yes, SELECTED means that the checkbox is checked, and ACTIVE means selecting using the mouse / keyboard.
So you have TOGGLE_ACTIVE_MULTI instead...
