### ISSUE TITLE
Performance issues with large trees when i search any node, DOM get stuck and Spinner also not working properly? #121

### ISSUE THREAD

**Issue by Anj21** [500tech/angular-tree-component#779]
Hello Everyone,

I have a tree with 10,000 nodes. when i search something, so when it fetching the search result and re-render the tree, it takes alot time on rendering the tree. To improve the user experience, i put spinner on search click, but it is not spinning, it also stuck when DOM re-render the data.

I just want that when DOM is re-rendering the tree, spinner works properly, but it get stuck.
so can anyone help me out to solve this issue. 

PLEASE READ CAREFULLY!

# Reproduce
Please reproduce here if reporting a bug, or requesting help:
https://stackblitz.com/edit/angular-wxansn

# Additional Info
- paste your package.json
- which browser
- paste your code

# Use the Slack Channel
The fastest way to get an answer is via the slack channel:
https://angular-tree-component.herokuapp.com/

You will also get updates on releases, bugfixes and other announcements.

# Search Docs First
Please look for an answer in the docs before submitting an issue:
angular2-tree.readme.io.

**Comment by adamkleingit** [comment]
If you do client side filtering, the only way to show a spinner and keep the UI free is to use a Web Worker.
