### ISSUE TITLE
IDTypeDictionary type indexer causes ts lint compiler to fail

### ISSUE THREAD

**Issue by hiwotamare** [500tech/angular-tree-component#782]
Typescript is complaining because of the following type in the library;
`export declare type IDTypeDictionary = {
        [id: string]: boolean;
         } | {
       [ id: number]: boolean;
};`

const fld: IDTypeDictionary = {};
fld[2] = false; //  **error TS7017: Element implicitly has an 'any' type because type 'IDTypeDictionar**y' has no index signature. 

Suggested fix:

1. Add number type indexer:
`export declare type IDTypeDictionary = {
      [id: string]: boolean;
      [id: number]: boolean
};`
2. Or alternatively use an interface: 
`export declare interface IDTypeDictionary {
       [id: string]: boolean;
}`

**Comment by adamkleingit** [comment]
This was fixed and published, please use latest version
