### ISSUE TITLE
Add node to root

### ISSUE THREAD

**Issue by rbalbis** [500tech/angular-tree-component#785]
Hello, I would like to add a node to my root array of node, I have something like this : 

```
nodes: myNode[] = [
    {
      name: 'parent1',
      id: "1",
      children: [
        { name: 'child1', id: "2", },
        { name: 'child2', id: "3", },
      ]
    }, {
      name: 'parent2', id: "5",
      children: [
        {
          name: 'child4',
          children: [
            { name: 'child5', id: "6", },
            { name: 'child6', id: "7", },
          ], id: "8",
        }, 
      ]
    },
  ]

```
and I would like to add a new node at the same level as parent1 and parent2. 
I add my child like this 

`parent.data.children.push(myNewNode)`

I can't figure out how to add the node as there's no parent. 
Thanks

**Comment by adamkleingit** [comment]
1. Every node has a parent, even the top ones have something called a 'virtualRoot'
2. Can you work with the component `nodes` instead? It might be easier

**Comment by findela** [comment]
can you give a little snippet how to get work on this? I have a similar problem, not able to add parent.

I tried something like straightforward + there is no document followup of this.

`addParentNode = () => {
    this.nodes.push({
      id: 1,
      name: 'root1',
      children: []
    });
  }`
