### ISSUE TITLE
Tree does not scroll horizontally to show new nested nodes

### ISSUE THREAD

**Issue by Davechpn** [500tech/angular-tree-component#786]
the tree width is 300px and thats the same witdh for each node. At node expansion I am supposed to scroll a bit to the right and view my nested nodes in  full but unfortunately the tree cant cant scroll to the right

**Comment by adamkleingit** [comment]
Hi,
please add a link to stackblitz / codesandbox / git repo to reproduce.
Thanks

**Comment by junxie6** [comment]
I encountered the same issue. This is how I solved it:

$ vim app.component.html

```
<div class="tree-wrapper">
  <tree-root [focused]="true" [nodes]="nodes"></tree-root>
</div>
```

$ vim styles.scss

```
@import '~angular-tree-component/dist/angular-tree-component.css';

.tree-wrapper {
  width: 160px;
  height: 360px;
  overflow-x: auto;
  border: 1px solid red;
}

.tree-children {
  overflow: visible;
}

tree-node-content > span {
  white-space: nowrap;
}
```

Demo on StackBlitz: [https://angular-wmedqh.stackblitz.io](https://angular-wmedqh.stackblitz.io)
