### ISSUE TITLE
Error Mobx-angular Angular 9 RC12

### ISSUE THREAD

**Issue by hartjo** [500tech/angular-tree-component#788]
# Additional Info

Package.json

{
  "name": "apts-frontend",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --open",
    "start:dev": "npm run start -- --configuration=dev",
    "start:deploy": "npm run start -- --configuration=deploy",
    "start:http-server": "npm run build && http-server -g -p 4200 ./dist/apts-frontend",
    "start:dev:http-server": "npm run build:dev && http-server -g -p 4200 ./dist/apts-frontend",
    "start:deploy:http-server": "npm run build:deploy && http-server -g -p 4200 ./dist/apts-frontend",
    "start:analyze": "npm run build:analyze && webpack-bundle-analyzer ./dist/apts-frontend/stats.json",
    "build": "node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build",
    "build:dev": "npm run build -- --configuration=dev",
    "build:prod": "npm run build -- --configuration=deploy",
    "build:analyze": "npm run build -- --configuration=production --stats-json=true",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^9.0.0-rc.12",
    "@angular/common": "^9.0.0-rc.12",
    "@angular/compiler": "^9.0.0-rc.12",
    "@angular/core": "^9.0.0-rc.12",
    "@angular/forms": "^9.0.0-rc.12",
    "@angular/platform-browser": "^9.0.0-rc.12",
    "@angular/platform-browser-dynamic": "^9.0.0-rc.12",
    "@angular/router": "^9.0.0-rc.12",
    "@auth0/angular-jwt": "^3.0.1",
    "@ng-bootstrap/ng-bootstrap": "^5.1.0",
    "@ng-select/ng-select": "^3.0.7",
    "@ngrx/effects": "^8.3.0",
    "@ngrx/router-store": "^8.3.0",
    "@ngrx/store": "^8.3.0",
    "@nicky-lenaers/ngx-scroll-to": "^3.0.1",
    "@sweetalert2/ngx-sweetalert2": "^5.1.0",
    "angular-tree-component": "^8.5.2",
    "blob-util": "^2.0.2",
    "bootstrap": "^4.3.1",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "file-saver": "^2.0.2",
    "immer": "^3.2.0",
    "jquery": "^3.4.1",
    "jquery-ui": "^1.12.1",
    "jquery-ui-dist": "^1.12.1",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "ng-select2": "^1.1.2",
    "ng2-password-strength-bar": "^1.2.3",
    "ngx-bootstrap": "^5.1.1",
    "ngx-device-detector": "^1.3.9",
    "ngx-file-drop": "^8.0.8",
    "ngx-filesize": "^1.1.4",
    "ngx-mask": "^8.0.3",
    "ngx-progressive-image-loader": "^3.0.2",
    "ngx-toastr": "^11.3.2",
    "ngx-window-token": "^2.0.1",
    "popper.js": "^1.16.0",
    "pretty-checkbox": "^3.0.3",
    "rxjs": "6.5.3",
    "select2": "^4.0.10",
    "sweetalert2": "^8.16.2",
    "tslib": "^1.10.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.10.2",
    "zxcvbn": "^4.4.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.0-rc.12",
    "@angular/cli": "^9.0.0-rc.12",
    "@angular/compiler-cli": "^9.0.0-rc.12",
    "@ngrx/schematics": "^8.3.0",
    "@ngrx/store-devtools": "^8.3.0",
    "@types/jasmine": "^3.4.0",
    "@types/jasminewd2": "^2.0.6",
    "@types/jquery": "^3.3.31",
    "@types/jqueryui": "^1.12.7",
    "@types/node": "^12.11.1",
    "@types/select2": "^4.0.48",
    "codelyzer": "^5.1.2",
    "http-server": "^0.11.1",
    "jasmine-core": "^3.4.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^4.2.0",
    "karma-chrome-launcher": "^3.1.0",
    "karma-coverage-istanbul-reporter": "^2.1.0",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "nswag": "^12.3.1",
    "protractor": "^5.4.2",
    "ts-node": "^8.3.0",
    "tslint": "^5.19.0",
    "typescript": "3.7.5",
    "webpack-bundle-analyzer": "^3.4.1"
  }
}

> -ERROR in Failed to compile entry-point angular-tree-component (module as esm5) due to compilation errors:
> node_modules/mobx-angular/dist/mobx-angular.d.ts:5:22 - error NG6002: Appears in the NgModule.imports of TreeModule, but could not be resolved to an NgModule class
> 
> 5 export declare class MobxAngularModule {

# Use the Slack Channel
The fastest way to get an answer is via the slack channel:
https://angular-tree-component.herokuapp.com/

You will also get updates on releases, bugfixes and other announcements.

# Search Docs First
Please look for an answer in the docs before submitting an issue:
angular2-tree.readme.io.

**Comment by Rkubisiak** [comment]
ive got the same issue when using rc14

**Comment by kkuriata** [comment]
Same issue with 9.0.0 release.

**Comment by juliocardosoventura** [comment]
ERROR in Failed to compile entry-point angular-tree-component (module as esm5) due to compilation errors:
node_modules/angular-tree-component/node_modules/mobx-angular/dist/mobx-angular.d.ts:5:22 - error NG6002: Appears in the NgModule.imports of TreeModule, but could not be resolved to an NgModule class

5 export declare class MobxAngularModule {

"@angular/core": "~9.0.0",
"mobx-angular": "3.1.0", "mobx-angular": "3.0.3",

How do you fix this... it’s still a problem!

**Comment by KeithGillette** [comment]
We are facing the same issue with Angular 9 and have to disable Ivy in `tsconfig.app.json`:

```json
	"angularCompilerOptions": {
		"enableIvy": false,
	},
```

**Comment by LanderBeeuwsaert** [comment]
jep, same same

**Comment by sgruhier** [comment]
same. to bad to disable ivy for this

**Comment by martinpagesaal** [comment]
Same here! Any solution?

**Comment by michaill** [comment]
there is very new mobx-angular@3.1.1 solving this issue. please can you make new package of angular-tree-component?

**Comment by hugoj-goncalves** [comment]
I'm having the same issue even with mobx-angular@3.1.1 😢

**Comment by martinpagesaal** [comment]
I'm working in a angular-tree-component and mobx-angular upgrade to A9, as soon as I have it i'll create PRs and share branch here if anyone wants to use it. 

If someone has this already please let me know so I do not duplicate my work.

**Comment by martinpagesaal** [comment]
Update: Just FYI, tried to use 3.1.1 and did not worked. I'll need to fork mobx-angular now.

**Comment by sgruhier** [comment]
I tried locally with "mobx-angular": "3.1.1" and it worked. It would be nice if someone from 500tech have a look and publish a new version

**Comment by martinpagesaal** [comment]
> I tried locally with "mobx-angular": "3.1.1" and it worked. It would be nice if someone from 500tech have a look and publish a new version

Did you forked or something? I could not make it work, same issue.

**Comment by sgruhier** [comment]
no, I did a quick and dirty test by copying files in my project. I'm gonna fork it and see if I can make it work

**Comment by sgruhier** [comment]
no chance for now, and it's the end of the day for me

**Comment by martinpagesaal** [comment]
For right now as a temp solution you guys can use my branch with the fix, made it work

This should work: 

`
npm uninstall angular-tree-component
npm install git+ssh://git@github.com/martinpagesaal/angular-tree-component#angular-9-dist
`

**Comment by adamkleingit** [comment]
Released 8.5.4
Would be nice if someone does a PR to upgrade example/cli Angular version to 9

**Comment by adamkleingit** [comment]
I added cli9 example, but it would still be good if we change the main cli to be version 9, because that's where we run all the tests.
So either migrate example/cli to 9, or recreate all the routes and components in the new cli9

**Comment by korolevsa** [comment]
Hi !

```
"dependencies": {
"angular-tree-component": "^8.5.4"
}
 "devDependencies": {
"@angular/compiler-cli": "~9.0.0",
}
```

![image](https://user-images.githubusercontent.com/22637655/74328101-5f769580-4d9e-11ea-9d04-531ccb0a68ee.png)

Please tell me how to solve this.

**Comment by sgruhier** [comment]
Correct I also have that error
@martinpagesaa solution with his repo git+ssh://git@github.com/martinpagesaal/angular-tree-component#angular-9-dist worked for me

**Comment by shreykene** [comment]
Hi, 
`"dependencies": {
"angular-tree-component": "^8.5.4"
}
 "devDependencies": {
"@angular/compiler-cli": "~9.0.0",
}`

I have updated the existing dist folder with #angular-9-dist but still not succeeded. Please tell me how to solve this.

**Comment by hartjo** [comment]
> Hi,
> `"dependencies": { "angular-tree-component": "^8.5.4" } "devDependencies": { "@angular/compiler-cli": "~9.0.0", }`
> 
> I have updated the existing dist folder with #angular-9-dist but still not succeeded. Please tell me how to solve this.

can you confirm that the version of your Mobx and Mobx-angular is same as the new one?

mobx@4.15.4 
mobx-angular@3.1.1

**Comment by wupaz** [comment]
Same prob here 
I delete node module delete package-lock.json and re-install 

```
  "angular-tree-component": {
      "version": "8.5.4",
      "resolved": "https://registry.npmjs.org/angular-tree-component/-/angular-tree-component-8.5.4.tgz",
      "integrity": "sha512-HLAxFMjv4gPH80565/6XhO8/ZPfejX9gadPzigmY2pen0rka1eQXz9sAauFm9sb6y/nM8l7U1q6uly24ysaiOw==",
      "requires": {
        "lodash": "^4.17.11",
        "mobx": "^4.15.1",
        "mobx-angular": "3.1.1"
      }
```

**Comment by hartjo** [comment]
I haven't tried the new version yet cause we are on a tight schedule for production release so we are in ivy false right now.

**Comment by korolevsa** [comment]
npm list --depth=0
```
+-- @angular-devkit/build-angular@0.900.1
+-- @angular/animations@9.0.0
+-- @angular/cli@9.0.1
+-- @angular/common@9.0.0
+-- @angular/compiler@9.0.0
+-- @angular/compiler-cli@9.0.0
+-- @angular/core@9.0.0
+-- @angular/forms@9.0.0
+-- @angular/language-service@9.0.0
+-- @angular/platform-browser@9.0.0
+-- @angular/platform-browser-dynamic@9.0.0
+-- @angular/router@9.0.0
+-- @types/jasmine@3.5.3
+-- @types/jasminewd2@2.0.8
+-- @types/node@12.12.27
+-- angular-tree-component@8.5.4
+-- codelyzer@5.2.1
+-- UNMET PEER DEPENDENCY core-js@^2.4.1
+-- jasmine-core@3.5.0
+-- jasmine-spec-reporter@4.2.1
+-- karma@4.3.0
+-- karma-chrome-launcher@3.1.0
+-- karma-coverage-istanbul-reporter@2.1.1
+-- karma-jasmine@2.0.1
+-- karma-jasmine-html-reporter@1.5.2
+-- mobx@4.15.4
+-- mobx-angular@3.1.1
+-- protractor@5.4.3
+-- rxjs@6.5.4
+-- ts-node@8.3.0
+-- tslib@1.10.0
+-- tslint@5.18.0
+-- typescript@3.7.5
`-- zone.js@0.10.2
```
ng build 

![image](https://user-images.githubusercontent.com/22637655/74338391-2399fb00-4db3-11ea-8c3f-506d6e6c3a04.png)

**Comment by adamkleingit** [comment]
@sgruhier @korolevsa can you send a link to reproduce? It works inside example/cli9:
https://github.com/500tech/angular-tree-component/tree/master/example/cli9

**Comment by hugoj-goncalves** [comment]
It doesn't work here also...
Even the example fails... https://github.com/500tech/angular-tree-component/tree/master/example/cli9
Which node/npm version are you using for curiosity?

**Comment by korolevsa** [comment]
```
ng new test-at -g --style=scss
npm install --save mobx@4.15.4 mobx-angular@3.1.1 angular-tree-component
```

copy steps from https://angular2-tree.readme.io/docs/

ng build 
![image](https://user-images.githubusercontent.com/22637655/74340093-5e516280-4db6-11ea-8c0b-0a58d0d89af3.png)
```

+-- @angular-devkit/build-angular@0.900.1
+-- @angular/animations@9.0.0
+-- @angular/cli@9.0.1
+-- @angular/common@9.0.0
+-- @angular/compiler@9.0.0
+-- @angular/compiler-cli@9.0.0
+-- @angular/core@9.0.0
+-- @angular/forms@9.0.0
+-- @angular/language-service@9.0.0
+-- @angular/platform-browser@9.0.0
+-- @angular/platform-browser-dynamic@9.0.0
+-- @angular/router@9.0.0
+-- @types/jasmine@3.5.3
+-- @types/jasminewd2@2.0.8
+-- @types/node@12.12.27
+-- angular-tree-component@8.5.4
+-- codelyzer@5.2.1
+-- UNMET PEER DEPENDENCY core-js@^2.4.1
+-- jasmine-core@3.5.0
+-- jasmine-spec-reporter@4.2.1
+-- karma@4.3.0
+-- karma-chrome-launcher@3.1.0
+-- karma-coverage-istanbul-reporter@2.1.1
+-- karma-jasmine@2.0.1
+-- karma-jasmine-html-reporter@1.5.2
+-- mobx@4.15.4
+-- mobx-angular@3.1.1
+-- protractor@5.4.3
+-- rxjs@6.5.4
+-- ts-node@8.3.0
+-- tslib@1.10.0
+-- tslint@5.18.0
+-- typescript@3.7.5
`-- zone.js@0.10.2
```
npm -v
6.9.0
node -v
v10.16.3

THE TRUTH IS OUT THERE

**Comment by martinpagesaal** [comment]
Use my branch thill its fixed, mobx 3.1.1 does not work, I had to branch mobx as well.

```
npm uninstall angular-tree-component
npm install git+ssh://git@github.com/martinpagesaal/angular-tree-component#angular-9-dist
```

**Comment by korolevsa** [comment]
> Use my branch thill its fixed, mobx 3.1.1 does not work, I had to branch mobx as well.
> 
> ```
> npm uninstall angular-tree-component
> npm install git+ssh://git@github.com/martinpagesaal/angular-tree-component#angular-9-dist
> ```

This not work for me.
![image](https://user-images.githubusercontent.com/22637655/74349567-79779e80-4dc5-11ea-9d13-2d124b243dd7.png)

**Comment by martinpagesaal** [comment]
> > Use my branch thill its fixed, mobx 3.1.1 does not work, I had to branch mobx as well.
> > ```
> > npm uninstall angular-tree-component
> > npm install git+ssh://git@github.com/martinpagesaal/angular-tree-component#angular-9-dist
> > ```
> 
> This not work for me.
> ![image](https://user-images.githubusercontent.com/22637655/74349851-e25f1680-4dc5-11ea-9674-51351cf1c69f.png)

Try 
``` npm install https://github.com/martinpagesaal/angular-tree-component.git#angular-9-dist```

**Comment by korolevsa** [comment]
Hi, unfortunately, I tried this method.
![image](https://user-images.githubusercontent.com/22637655/74417007-10d90200-4e57-11ea-9175-447ec2f3cdbc.png)
And it does not work

**Comment by pmstss** [comment]
@korolevsa it's a separate windows git setup issue unrelated to initial one. Just google for "git windows host key verification failed".
Had similar one, hints from https://github.community/t5/How-to-use-Git-and-GitHub/Git-via-SSH-from-Windows-returns-Permission-Denied/td-p/9336 helped to quickly fix it.
@martinpagesaal forks work well 👍

**Comment by adamkleingit** [comment]
Oh very strange. I removed node_modules and re-installed and now it breaks

**Comment by adamkleingit** [comment]
I fixed it by removing mobx-angular as a dependency and assimilating its code inside.
Please use 8.5.6 and let me know if there are any issues

**Comment by sgruhier** [comment]
it works for me 
thanks

**Comment by iliyaeffati** [comment]
it works perfectly, thanks

**Comment by korolevsa** [comment]
It works for me. Thanks/

**Comment by adamkleingit** [comment]
Thanks everyone! I'm glad it works and we can now use the tree in Angular 9 :)
I still don't know what caused the problem though. Very strange because mobx-angular by itself works OK with Angular 9, so it's weird that using it from here fails

**Comment by rahulroykumar** [comment]
@adamkleingit 
with "postinstall": "ngcc" it works fine but
Tree component fails when using below postinstall script:

ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points"

![image](https://user-images.githubusercontent.com/8906476/74783773-3d2bbe80-525b-11ea-8040-7358dde7cc26.png)

can you please suggest? I need to create ivy entry points

**Comment by debender495** [comment]
> I fixed it by removing mobx-angular as a dependency and assimilating its code inside.
> Please use 8.5.6 and let me know if there are any issues

with this version, it gives below error

 node_modules/mobx/lib/api/flow.d.ts:9:108 - error TS2304: Cannot find name 'AsyncGenerator'.

    9 export declare function flow<R, Args extends any[]>(generator: (...args: Args) => Generator<any, R, any> | AsyncGenerator<any, R, any>): (...args: Args) => CancellablePromise<R>;
                                                                                                                 ~~~~~~~~~~~~~~

**Comment by debender495** [comment]
with the latest version 8.5.6 of angular-tree-component, I get below error with angular 9

 node_modules/mobx/lib/api/flow.d.ts:9:108 - error TS2304: Cannot find name 'AsyncGenerator'.

    9 export declare function flow<R, Args extends any[]>(generator: (...args: Args) => Generator<any, R, any> | AsyncGenerator<any, R, any>): (...args: Args) => CancellablePromise<R>;
                                                                                                                 ~~~~~~~~~~~~~~

some type crap,

**Comment by gmaggiodev** [comment]
Same issue with Angular 10

![image](https://user-images.githubusercontent.com/1485446/86117697-c687b300-bacf-11ea-8133-dd09e326ccf2.png)
