### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by saradalco** [500tech/angular-tree-component#87]
Hi,

the tree component is working fine on Chrome and IE 11. 
It doesn't work on older versions of IE.
Is there any possibility it can work on older versions?

Thank you

**Comment by EinArzt** [comment]
Angular2 only supports the latest browsers, so this is definitely not possible.
See here: https://angular.io/docs/ts/latest/guide/browser-support.html

**Comment by saradalco** [comment]
That's right, but the tree component only works in IE 10 and 11, not in 9.

**Comment by saradalco** [comment]
The error is:

EXCEPTION: Error in ./TreeNodeDropSlot class TreeNodeDropSlot - inline template:3:6 caused by: Unable to get property 'remove' of undefined or null reference

Error: Error in ./TreeNodeDropSlot class TreeNodeDropSlot - inline template:3:6 caused by: Unable to get property 'remove' of undefined or null reference

**Comment by EinArzt** [comment]
Seems like lodash only supports IE 11.

> Support
> Tested in Chrome 53-54, Firefox 48-49, IE 11, Edge 14, Safari 9-10, Node.js 4-6 & PhantomJS 2.1.1.
> https://lodash.com/

Either you change all occurences of lodash to native functions or you use the lodash.compat version, but it seems they discontinued support for it. 
https://github.com/lodash-archive/lodash-compat

**Comment by adamkleingit** [comment]
Does anyone know a polyfill that allows lodash to work on IE9-10?
