### ISSUE TITLE
Tree Table

### ISSUE THREAD

**Issue by sante85** [500tech/angular-tree-component#93]
When implement tree table?

**Comment by adamkleingit** [comment]
What do you mean? Tree inside a data table?
Currently there's no plan to implement this.

**Comment by karol-depka** [comment]
Perhaps @sante85 means something like JXTreeTable?

**Comment by osos** [comment]
Can this be achieved using custom templates?

I am looking to use this on a filestructure which would look pretty if data is organised in columns.

**Comment by abelkbil** [comment]
I have done something similar :  https://angular-9u9ml1.stackblitz.io/
https://stackblitz.com/edit/angular-9u9ml1?file=app%2Fapp.component.ts

Currently I am in a situation to implement all features [drag and drop, lazy laod ] of angular-tree-component. 

What can be the solution with existing library. @adamkleingit 
Thanks for library.

**Comment by aldrindizonh** [comment]
same problem. i want to implement tree table

**Comment by adamkleingit** [comment]
I recommend using grid solutions that offer tree inside grid.
Usually that comes with many other grid features like sorting, filtering, pagination, etc.
